from collections import OrderedDict

cards = [{'getal': 'O',
  'kernwoord': 'ONSCHULD',
  'kleur': 'groot',
  'naam': 'De Dwaas',
  'opmerking': 'De Zot',
  'steekwoorden': 'Onschuld, ongevormd, lichtzinnig, afgrond, nieuw begin, na\xc3\xafef, kinderlijk, ongericht',
  'symbolen': 'jonge man, roos, staf, zon, berg, hond, bloemenkrans, geel',
  'uitnodiging': 'Doe eens iets spontaans.',
  'waarschuwing': 'Waar is het kind je je gebleven?'},
 {'getal': 'I',
  'kernwoord': 'MEESTERSCHAP',
  'kleur': 'groot',
  'naam': 'De Magier',
  'opmerking': '',
  'steekwoorden': 'Bewust van kracht en mogelijkheden, je (leer)proces aangaan, diplomatie, zo boven zo beneden',
  'symbolen': 'natuur, roos, lelie,baldakijn, altaar, zwaard, staf, kelk, pentakel, jonge man, ourobouros, lemniscaat, bloemen, geel',
  'uitnodiging': 'Richt je op wat je w\xc3\xa9l kunt.',
  'waarschuwing': 'Je neemt teveel hooi op je vork.'},
 {'getal': 'II',
  'kernwoord': 'INTU\xc3\x8fTIE',
  'kleur': 'groot',
  'naam': 'De Hogepriesteres',
  'opmerking': 'De Pausin',
  'steekwoorden': 'Beschermkaart, verborgen wijsheid, esoterische kennis, innerlijk conflict, vooruitziend',
  'symbolen': 'maagd, sluier, kroon, troon, palmhart, granaatappel, maan, kruis, schriftrol, pilaren, boaz, jachin, blauw, waterbron, zwart',
  'uitnodiging': 'Laat je eens leiden door je innerlijke stem.',
  'waarschuwing': 'Laat de dingen niet te veel op hun beloop.'},
 {'getal': 'III',
  'kernwoord': 'VRUCHTBAARHEID',
  'kleur': 'groot',
  'naam': 'De Keizerin',
  'opmerking': '',
  'steekwoorden': 'Ontspanning, de overvloed van het leven en de kracht van de bloeiende aarde, moeder, liefde geven en ontvangen',
  'symbolen': 'volwassen vrouw, troon, kroon, parels, scepter, venussymbool, stroom, boom, koren',
  'uitnodiging': 'Kijk eens om je heen en geniet.',
  'waarschuwing': 'Leef je in harmonie met je omgeving/de natuur?'},
 {'getal': 'IV',
  'kernwoord': 'GEZAG',
  'kleur': 'groot',
  'naam': 'De Keizer',
  'opmerking': '',
  'steekwoorden': 'Verwezenlijking, verantwoordelijkheid, zelfhandhaving, bescherming, vader',
  'symbolen': 'volwassen man, stroom, berg, troon, kroon, rijksappel, rood kleed,harnas',
  'uitnodiging': 'Neem zelf het heft in handen.',
  'waarschuwing': 'Is er voldoende ruimte voor je gevoelens?'},
 {'getal': 'V',
  'kernwoord': 'LERAAR',
  'kleur': 'groot',
  'naam': 'De Hogepriester',
  'opmerking': 'De Hi\xc3\xabrofant, De Paus',
  'steekwoorden': 'Beschermkaart, religie, geestelijkheid, staan voor je mening, verkondigen, expertise, inspiratie, gewoontegetrouw',
  'symbolen': 'zegening, pilaren, kruis, kroon, adept, rood kleed, sleutel',
  'uitnodiging': 'Wees niet bang om je mening te delen.',
  'waarschuwing': 'Luister ook goed naar anderen.'},
 {'getal': 'VI',
  'kernwoord': 'KEUZE',
  'kleur': 'groot',
  'naam': 'De Geliefden',
  'opmerking': '',
  'steekwoorden': 'Dualiteit mannelijk - vrouwelijk; (sexuele) aantrekkingskracht, bewust van tegenstellingen, samenwerking, onvoorwaardelijk ja, zich losmaken',
  'symbolen': 'naaktheid, engel, zegening, appelboom, slang, wolken, bergtop, zon, jonge man, jonge vrouw, paars kleed',
  'uitnodiging': 'Maak een definitievem, bindende keuze.',
  'waarschuwing': 'Verlies jezelf niet in deze relatie.'},
 {'getal': 'VII',
  'kernwoord': 'VEROVERING',
  'kleur': 'groot',
  'naam': 'De Zegewagen',
  'opmerking': '',
  'steekwoorden': 'Wilskracht, zelfdiscipline, controle, tot stand brengen, sprong voorwaarts',
  'symbolen': 'jonge man, kroon, lauwerkrans, ster (achtpuntig), vierkant, yoni, lingam, sfinx, stadsmuur, hermesvleugels, maan, harnas, baldakijn',
  'uitnodiging': 'Bepaal je koers en hou die vast.',
  'waarschuwing': 'Teugels te strak of zwalkend.'},
 {'getal': 'VIII',
  'kernwoord': 'GERECHTIGHEID',
  'kleur': 'groot',
  'naam': 'Gerechtigheid',
  'opmerking': 'Waite XI',
  'steekwoorden': 'Oorzaak en gevolg, schuld en boete, rechtvaardig, zelfbeoordeling',
  'symbolen': 'man, zwaard geheven, weegschaal, vierkant, troon, pilaren, paars kleed, rood kleed, groen kleed, kubus, vrouw',
  'uitnodiging': 'Erken je eigen aandeel maar niet meer dan dat.',
  'waarschuwing': 'Zijn je motieven zuiver?'},
 {'getal': 'IX',
  'kernwoord': 'TOP',
  'kleur': 'groot',
  'naam': 'De Kluizenaar',
  'opmerking': 'De Heremiet',
  'steekwoorden': 'Je eigen weg gaan, op zoek zijn, dwalen, inkeer, teruggetrokken, voorzichtig, geduldig, zorgvuldig, baken',
  'symbolen': 'oude man, blauw, lantaarn, staf, ster (achtpuntig), afgewend, links, rechts',
  'uitnodiging': 'Volg je eigen licht.',
  'waarschuwing': 'Heb je genoeg aan jezelf?'},
 {'getal': 'X',
  'kernwoord': 'LOT',
  'kleur': 'groot',
  'naam': 'Het Rad van Fortuin',
  'opmerking': 'Wiel van Fortuin',
  'steekwoorden': 'Aanvaarding, succes of falen.',
  'symbolen': 'engel, stier, leeuw, sfinx, slang, hermanubis, tora, feniks',
  'uitnodiging': 'Wie niet waagt die niet wint.',
  'waarschuwing': 'Je laat teveel aan het toeval over.'},
 {'getal': 'XI',
  'kernwoord': 'BEHEERSING',
  'kleur': 'groot',
  'naam': 'Kracht',
  'opmerking': 'Waite VIII',
  'steekwoorden': 'Met respekt omgaan met kracht en emoties, temmen',
  'symbolen': 'jonge vrouw, leeuw, bloemenkrans, lemniscaat, bergtop, oranje',
  'uitnodiging': 'Een besliste maar zachte hand is nodig.',
  'waarschuwing': 'Die Leeuw mag best af en toe eens brullen.'},
 {'getal': 'XII',
  'kernwoord': 'PERSPECTIEF',
  'kleur': 'groot',
  'naam': 'De Gehangene',
  'opmerking': '',
  'steekwoorden': 'Ergens aan vast zitten, consequenties aanvaarden, beproeving, ommekeer, herprioriteren',
  'symbolen': 'volwassen man, ondersteboven, aureool, kruis, blauw, staf',
  'uitnodiging': 'Vrije wil is blijmoedig doen wat je moet doen.',
  'waarschuwing': 'Waardoor zit je vast?'},
 {'getal': 'XIII',
  'kernwoord': 'TRANSFORMATIE',
  'kleur': 'groot',
  'naam': 'De Dood',
  'opmerking': 'De Kaart zonder Naam',
  'steekwoorden': 'vernietiging van het oude, doorbraak, het onvermijdelijke, afsluiting, vergankelijkheid, voltooiing, overgang naar het onbekende',
  'symbolen': 'wit, vaandel, wolken, toren, zon, koning, bisschop, jonge vrouw, kind, boot, man, stroom, paard, afgewend, zwart, zon, roos, harnas, doodshoofd',
  'uitnodiging': 'Acceptatie is de eerste stap op weg naar verandering.',
  'waarschuwing': 'Steek je energie in iets wat onhaalbaar is?'},
 {'getal': 'XIV',
  'kernwoord': 'HARMONIE',
  'kleur': 'groot',
  'naam': 'Matigheid',
  'opmerking': '',
  'steekwoorden': 'Afwegen, evenwicht verstand en gevoel, integratie, zuinigheid, tact',
  'symbolen': 'engel, natuur, iris, kelken, pad, driehoek, stroom, berg, vierkant met driehoek',
  'uitnodiging': 'Wat kan je weglaten?',
  'waarschuwing': 'Overmaat schaadt, ondermaat ook.'},
 {'getal': 'XV',
  'kernwoord': 'VERLEIDING',
  'kleur': 'groot',
  'naam': 'De Duivel',
  'opmerking': '',
  'steekwoorden': 'Obsessie, de Schaduw, sexualiteit, zwart-wit denken, fanatisme, materialisme',
  'symbolen': 'geit, vleermuisvleugels, vogelpoten, borsten, troon, zegening, vierkant, toorts, naaktheid, ketens, pentagram, zwart',
  'uitnodiging': 'Welke principes zitten je in de weg?',
  'waarschuwing': 'Zit je verstrikt in dat wat niet goed voor je is?'},
 {'getal': 'XVI',
  'kernwoord': 'RAMPSPOED',
  'kleur': 'groot',
  'naam': 'De Toren',
  'opmerking': 'Het Huis Gods',
  'steekwoorden': 'Onvoorziene verandering, crisis, vertwijfeling, loslaten van zekerheid, noodlot, toren van Babel',
  'symbolen': 'toren, vuur, bergtop, wolken, bliksem, kroon, yod, zwart',
  'uitnodiging': 'Wat moet je openbreken?',
  'waarschuwing': 'Zit je gevangen in vastgeroeste patronen?'},
 {'getal': 'XVII',
  'kernwoord': 'HOOP',
  'kleur': 'groot',
  'naam': 'De Ster',
  'opmerking': '',
  'steekwoorden': 'bezieling, wees de ster in je eigen leven, de sterren bereiken',
  'symbolen': 'ster (achtpuntig), naaktheid, jonge vrouw, kelken, heuvels, feniks, water',
  'uitnodiging': 'Durf vol vertrouwen je toekomst tegemoet te zien.',
  'waarschuwing': 'Valse hoop, misplaatst vertrouwen.'},
 {'getal': 'XVIII',
  'kernwoord': 'SCHEMER',
  'kleur': 'groot',
  'naam': 'De Maan',
  'opmerking': '',
  'steekwoorden': 'verlangens, droom en daad, behoefte aan bescherming,uit je schulp kruipen, dwaling, stemmingswisselingen, onbestemde angst, hersenschimmen, betovering',
  'symbolen': 'maan, pad, hond + wolf, water, kreeft, yod, toren, pilaren',
  'uitnodiging': 'Durf je angsten onder ogen te zien',
  'waarschuwing': 'Waar ben je zo bang voor?'},
 {'getal': 'XIX',
  'kernwoord': 'OPTIMISME',
  'kleur': 'groot',
  'naam': 'De Zon',
  'opmerking': '',
  'steekwoorden': 'creativiteit, speelsheid, levenslust, zelfvertrouwen, je hart, je kern',
  'symbolen': 'kind, bloemenkrans, wit, rood kleed, zon, zonnebloem, golven',
  'uitnodiging': 'Wees ongedwongen jezelf',
  'waarschuwing': 'Het speelkwartier is allang voorbij.'},
 {'getal': 'XX',
  'kernwoord': 'VERLOSSING',
  'kleur': 'groot',
  'naam': 'Het Oordeel',
  'opmerking': '',
  'steekwoorden': 'Transformatie, het laatste oordeel, verrijzenis',
  'symbolen': 'engel, wolken, bazuin, volwassen man, volwassen vrouw, kind, grijs, naaktheid, berg',
  'uitnodiging': 'Laat het verleden los.',
  'waarschuwing': 'Waar heb je je de hele tijd van afgesloten?'},
 {'getal': 'XXI',
  'kernwoord': 'LEVEN',
  'kleur': 'groot',
  'naam': 'De Wereld',
  'opmerking': '',
  'steekwoorden': 'Het leven aangaan zonder jezelf er in te verliezen, hervonden paradijs',
  'symbolen': 'jonge vrouw, staven, lauwerkrans, leeuw, stier, arend, engel',
  'uitnodiging': 'Ga voluit voor wat je wilt bereiken.',
  'waarschuwing': 'Het is tijd voor bezinning.'},
 {'getal': '',
  'kernwoord': 'DROOM',
  'kleur': 'Staven',
  'naam': 'Aas',
  'opmerking': '',
  'steekwoorden': 'visie, enthousiasme, vitaliteit.',
  'symbolen': 'wolken, stroom, heuvels, burcht, hand, rechts, grijs',
  'uitnodiging': 'Sta open om te groeien',
  'waarschuwing': 'Wat doe ik aan mijn ontplooiing?'},
 {'getal': '2',
  'kernwoord': 'PLANNEN',
  'kleur': 'Staven',
  'naam': 'II',
  'opmerking': '',
  'steekwoorden': 'pionieren, opties afwegen',
  'symbolen': 'links, water, muur, globe, roos, lelie, berg, rood kleed, grijs',
  'uitnodiging': 'Alle begin is moeilijk.',
  'waarschuwing': 'Vernieuwing is nog geen verbetering.'},
 {'getal': '3',
  'kernwoord': 'AFWACHTEN',
  'kleur': 'Staven',
  'naam': 'III',
  'opmerking': '',
  'steekwoorden': 'vooruitzien, handel, ontdekkingsreizen',
  'symbolen': 'rechts, rood kleed, groen kleed, boot, water, heuvels, geel',
  'uitnodiging': 'Wacht rustig af',
  'waarschuwing': 'Je kunt nu niet meer terug.'},
 {'getal': '4',
  'kernwoord': 'OOGSTEN',
  'kleur': 'Staven',
  'naam': 'IV',
  'opmerking': '',
  'steekwoorden': 'resultaten vieren, harmonieuze samenwerking, terugkerende feesten',
  'symbolen': 'kasteel, wit kleed, rood kleed, blauw kleed, bloemen, oranje',
  'uitnodiging': 'Je initiatief is vruchtbaar.',
  'waarschuwing': 'Het is nog te vroeg om op je lauweren te rusten.'},
 {'getal': '5',
  'kernwoord': 'WEDIJVEREN',
  'kleur': 'Staven',
  'naam': 'V',
  'opmerking': '',
  'steekwoorden': 'schijngevecht, rellen',
  'symbolen': '',
  'uitnodiging': 'Laat je niet zomaar opzij zetten',
  'waarschuwing': 'Blijf niet hangen in gekissebis.'},
 {'getal': '6',
  'kernwoord': 'TRIOMFEREN',
  'kleur': 'Staven',
  'naam': 'VI',
  'opmerking': '',
  'steekwoorden': 'zegevieren, mijlpaal, beginnend succes, waardering, groot nieuws',
  'symbolen': 'groen kleed, lauwerkrans, paard',
  'uitnodiging': 'Stel je op als een leider',
  'waarschuwing': 'E\xc3\xa9n zwaluw maakt nog geen zomer'},
 {'getal': '7',
  'kernwoord': 'HANDHAVEN',
  'kleur': 'Staven',
  'naam': 'VII',
  'opmerking': '',
  'steekwoorden': 'staande houden, vaak alleen, overmacht, gunstige positie',
  'symbolen': 'stroom, heuvels',
  'uitnodiging': 'Neem het voor jezelf op.',
  'waarschuwing': 'Vraag niet voortdurend goedkeuring. Doe het gewoon!'},
 {'getal': '8',
  'kernwoord': 'OPLIJNEN',
  'kleur': 'Staven',
  'naam': 'VIII',
  'opmerking': '',
  'steekwoorden': 'veel energie, alles op \xc3\xa9\xc3\xa9n lijn, van een lijen dakje, haast, liefdespijlen',
  'symbolen': 'stroom, heuvels, linksboven, rechtsonder',
  'uitnodiging': 'Laat je meevoeren',
  'waarschuwing': 'Blijf zelf aan het roer'},
 {'getal': '9',
  'kernwoord': 'WAKEN',
  'kleur': 'Staven',
  'naam': 'IX',
  'opmerking': '',
  'steekwoorden': 'op krachten komen, verzet, achterdocht, oponthoud, uitstel',
  'symbolen': 'muur',
  'uitnodiging': 'Bekijk het eens uit het perspectief van de ander',
  'waarschuwing': 'Is de dreiging wel echt?'},
 {'getal': '10',
  'kernwoord': 'VOLHOUDEN',
  'kleur': 'Staven',
  'naam': 'X',
  'opmerking': '',
  'steekwoorden': 'afmaken, heroverwegen, opstand tegen onderdrukking',
  'symbolen': 'stadsmuur',
  'uitnodiging': 'Wie kan je helpen om deze last te dragen?',
  'waarschuwing': 'Laat op tijd los'},
 {'getal': '',
  'kernwoord': 'BOODSCHAPPER',
  'kleur': 'Staven',
  'naam': 'Page',
  'opmerking': '',
  'steekwoorden': 'op idee\xc3\xabn komen.',
  'symbolen': 'heuvels, pyramide, rood kleed, blauw',
  'uitnodiging': 'Grijp je kans!',
  'waarschuwing': 'Pas op voor (te) mooie verhalen'},
 {'getal': '',
  'kernwoord': 'VURIG',
  'kleur': 'Staven',
  'naam': 'Ridder',
  'opmerking': '',
  'steekwoorden': 'idealen koesteren, overtuigingskracht.',
  'symbolen': 'salamander, geel, oranje, paard, harnas, vuur, pyramide',
  'uitnodiging': 'Laat jezelf eens lekker gaan',
  'waarschuwing': 'Wie/wat zet je in vuur en vlam?'},
 {'getal': '',
  'kernwoord': 'KUNDIG',
  'kleur': 'Staven',
  'naam': 'Koningin',
  'opmerking': '',
  'steekwoorden': 'je eigen belevings- en verbeeldingswereld, onafhankelijk, identiteit, zelfvertrouwen',
  'symbolen': 'geel kleed, grijs kleed, troon, leeuw, zonnebloem, kroon, bloemenkrans, zwarte kat',
  'uitnodiging': 'Geloof in jezelf.',
  'waarschuwing': 'Neem ook eens iets van een ander aan'},
 {'getal': '',
  'kernwoord': 'INTEGER',
  'kleur': 'Staven',
  'naam': 'Koning',
  'opmerking': '',
  'steekwoorden': 'creatief, inspirerend, charmant, geestig, rechtvaardig, gedreven',
  'symbolen': 'salamander, geel, rood kleed, groen kleed, troon, kroon, ourobouros, afgewend, leeuw, oranje',
  'uitnodiging': 'Hoe zou hij het aanpakken?',
  'waarschuwing': 'Eerlijk duurt het langst'},
 {'getal': '',
  'kernwoord': 'POTENTIE',
  'kleur': 'Pentakels',
  'naam': 'Aas',
  'opmerking': '',
  'steekwoorden': 'kunde, tot stand brengen, realisme, waarde',
  'symbolen': 'hand, wolken, boog, bloemen, links, roos, lelie, pad, bergtop, blauw',
  'uitnodiging': 'Hoe kan je deze kans verzilveren?',
  'waarschuwing': 'Lever een constructieve bijdrage.'},
 {'getal': '2',
  'kernwoord': 'JONGLEREN',
  'kleur': 'Pentakels',
  'naam': 'II',
  'opmerking': '',
  'steekwoorden': 'evenwicht zoeken/houden, uitgekiende inzet van middelen, oefenen, schijnplezier',
  'symbolen': 'lemniscaat, golven, boot, jonge man, blauw',
  'uitnodiging': 'Speel met je mogelijkheden',
  'waarschuwing': 'Je kan niet alle opties open houden'},
 {'getal': '3',
  'kernwoord': 'BEWIJZEN',
  'kleur': 'Pentakels',
  'naam': 'III',
  'opmerking': '',
  'steekwoorden': 'waardering, vakmanschap, uitvoering, inzet, proef, presenteren',
  'symbolen': 'monnik, hamer, grijs, zwart',
  'uitnodiging': 'Waarmee kan je jezelf bewijzen?',
  'waarschuwing': 'Sta open voor feedback'},
 {'getal': '4',
  'kernwoord': 'VASTHOUDEN',
  'kleur': 'Pentakels',
  'naam': 'IV',
  'opmerking': '',
  'steekwoorden': 'houden wat je hebt, energiestroom blokkeren, hebzucht',
  'symbolen': 'toren, paars',
  'uitnodiging': 'Wees zuinig op je mogelijkheden.',
  'waarschuwing': 'Wat probeer je te krampachtig vast te houden?'},
 {'getal': '5',
  'kernwoord': 'VREZEN',
  'kleur': 'Pentakels',
  'naam': 'V',
  'opmerking': '',
  'steekwoorden': '(angst voor) ontbering, gebrek, kou, angst voor de toekoms',
  'symbolen': 'bel',
  'uitnodiging': 'Wat heb je echt nodig?',
  'waarschuwing': 'Angst is een slechte raadgever.'},
 {'getal': '6',
  'kernwoord': 'BEDELEN',
  'kleur': 'Pentakels',
  'naam': 'VI',
  'opmerking': '',
  'steekwoorden': 'Bedelen vs beDElen, arm vs rijk, zaaien',
  'symbolen': 'rood kleed, zegening, boom, burcht, weegschaal, geel kleed, blauw kleed',
  'uitnodiging': 'Delen = vermenigvuldigen',
  'waarschuwing': 'Ben je bereid hulp te accepteren?'},
 {'getal': '7',
  'kernwoord': 'VERLANGEN',
  'kleur': 'Pentakels',
  'naam': 'VII',
  'opmerking': '',
  'steekwoorden': 'ongeduld, onvrede, beheren',
  'symbolen': 'staf, paars',
  'uitnodiging': 'Kijk het nog even aan. Zie je voortgang.',
  'waarschuwing': 'Blijf niet toekijken'},
 {'getal': '8',
  'kernwoord': 'OEFENEN',
  'kleur': 'Pentakels',
  'naam': 'VIII',
  'opmerking': '',
  'steekwoorden': 'oefenen, nederig werk, ambachten, kundigheid',
  'symbolen': 'hamer, geel',
  'uitnodiging': 'Wat zou je willen leren?',
  'waarschuwing': 'Moet je niet eens iets nieuws proberen?'},
 {'getal': '9',
  'kernwoord': 'GENIETEN',
  'kleur': 'Pentakels',
  'naam': 'IX',
  'opmerking': '',
  'steekwoorden': 'vervulling, verfraaien, zekerheid, meevaller',
  'symbolen': 'druiven, kasteel, geel, valk, wijnhuisslak',
  'uitnodiging': 'Geniet van wat je doet.',
  'waarschuwing': 'Ben je alert op nieuwe kansen?'},
 {'getal': '10',
  'kernwoord': 'DOORGEVEN',
  'kleur': 'Pentakels',
  'naam': 'X',
  'opmerking': '',
  'steekwoorden': 'traditie, iets opbouwen, zekerheid, welvaart, familiezaken',
  'symbolen': 'druiven, hond, burcht, toren, poort, weegschaal, oude man',
  'uitnodiging': 'Draag bij aan het grotere geheel.',
  'waarschuwing': 'Wees niet te gefixeerd op zekerheid.'},
 {'getal': '',
  'kernwoord': 'LEERGIERIG',
  'kleur': 'Pentakels',
  'naam': 'Page',
  'opmerking': '',
  'steekwoorden': 'behulpzaam, precies, kritisch, student, ijverig',
  'symbolen': 'natuur, heuvels, bloemen, groen kleed, stroom, geel',
  'uitnodiging': 'Hoe kun je jezelf nuttig maken?',
  'waarschuwing': 'Pas op voor vluchtige belangstelling'},
 {'getal': '',
  'kernwoord': 'STANDVASTIG',
  'kleur': 'Pentakels',
  'naam': 'Ridder',
  'opmerking': '',
  'steekwoorden': 'organisatievermogen, degelijk, plichtgetrouw, praktisch',
  'symbolen': 'paard, harnas, rood kleed, afgewend, geel',
  'uitnodiging': 'Richt je op het haalbare.',
  'waarschuwing': 'Hoe stevig is je basis?'},
 {'getal': '',
  'kernwoord': 'ZORGZAAM',
  'kleur': 'Pentakels',
  'naam': 'Koningin',
  'opmerking': '',
  'steekwoorden': 'innerlijke zekerheid, zelfwaardering, royaal',
  'symbolen': 'natuur, troon, kroon, bloemen, berg, cupido, geit, haas, afgewend, geel',
  'uitnodiging': 'Kies voor rust en geleidelijkheid.',
  'waarschuwing': 'Je hoeft niet alles te behouden'},
 {'getal': '',
  'kernwoord': 'ONDERNEMER',
  'kleur': 'Pentakels',
  'naam': 'Koning',
  'opmerking': '',
  'steekwoorden': 'standvastigheid, autoriteit, realiserende intelligentie, rechtlijnig, besluitvaardig',
  'symbolen': 'stier, druiven, troon, kroon, harnas, geel',
  'uitnodiging': 'Ga voor realistische ambitie',
  'waarschuwing': 'Bezit maakt niet gelukkig'},
 {'getal': '',
  'kernwoord': 'VISIE',
  'kleur': 'Zwaarden',
  'naam': 'Aas',
  'opmerking': '',
  'steekwoorden': 'helderheid van geest, objectiviteit',
  'symbolen': 'wolken, hand, kroon, robijn, olijfblad, palmtak, zwaard geheven, blauw',
  'uitnodiging': 'Welke beslissing moet je nu nemen?',
  'waarschuwing': 'Heb je alles goed overwogen?'},
 {'getal': '2',
  'kernwoord': 'TWIJFELEN',
  'kleur': 'Zwaarden',
  'naam': 'II',
  'opmerking': '',
  'steekwoorden': 'relativeren, twee kanten van de medaille zien, dilemma, elke keuze is beter dan geen keuze',
  'symbolen': 'wit kleed, water, heuvels, kubus, blinddoek, maan, blauw',
  'uitnodiging': 'Luister naar je innerlijke stem',
  'waarschuwing': 'Is het belangrijk om alles zo veel te analyseren?'},
 {'getal': '3',
  'kernwoord': 'DOORBOREN',
  'kleur': 'Zwaarden',
  'naam': 'III',
  'opmerking': '',
  'steekwoorden': 'pijn, verdriet',
  'symbolen': 'hartvorm, wolken, grijs, regen',
  'uitnodiging': 'Ben je sterk genoeg om te doen wat noodzakelijk is?',
  'waarschuwing': 'Laat je niet beheersen door je verdriet'},
 {'getal': '4',
  'kernwoord': 'BEZINNEN',
  'kleur': 'Zwaarden',
  'naam': 'IV',
  'opmerking': '',
  'steekwoorden': 'overwegen, rusten, herstellen, retraite, testament',
  'symbolen': 'grijs, ridder',
  'uitnodiging': 'Slaap er een nachtje over.',
  'waarschuwing': 'Waarom staat alles stil?'},
 {'getal': '5',
  'kernwoord': 'MISGUNNEN',
  'kleur': 'Zwaarden',
  'naam': 'V',
  'opmerking': '',
  'steekwoorden': 'debatteren, negatieve gedachtepatronen, verraad, degradatie, oneer',
  'symbolen': 'afgewend, oranje, blauw',
  'uitnodiging': 'Eerlijk duurt het langst',
  'waarschuwing': 'Is het belangrijk om pers\xc3\xa9 te winnen?'},
 {'getal': '6',
  'kernwoord': 'OVERSTEKEN',
  'kleur': 'Zwaarden',
  'naam': 'VI',
  'opmerking': '',
  'steekwoorden': 'je terug trekken, vlucht',
  'symbolen': 'water, golven',
  'uitnodiging': 'Maak een nieuw begin',
  'waarschuwing': 'Is het gras echt groener?'},
 {'getal': '7',
  'kernwoord': 'SLUIPEN',
  'kleur': 'Zwaarden',
  'naam': 'VII',
  'opmerking': '',
  'steekwoorden': 'slimheid, spitsvondigheid, oneerlijkheid',
  'symbolen': 'oranje',
  'uitnodiging': 'Verzin een list.',
  'waarschuwing': 'Je wordt in de maling genomen.'},
 {'getal': '8',
  'kernwoord': 'VASTLOPEN',
  'kleur': 'Zwaarden',
  'naam': 'VIII',
  'opmerking': '',
  'steekwoorden': 'negatieve gedachtenpatronen, censuur, ziekte, schaamte, verdenking',
  'symbolen': 'blinddoek, burcht, stroom, berg, grijs',
  'uitnodiging': 'Laat alle remmende gedachten los',
  'waarschuwing': 'Wat houdt je tegen?'},
 {'getal': '9',
  'kernwoord': 'ONTWAKEN',
  'kleur': 'Zwaarden',
  'naam': 'IX',
  'opmerking': '',
  'steekwoorden': 'dagend inzicht, zelfverwijt, vertwijfeling',
  'symbolen': 'afgewend, roos, wit kleed, oosten, vrouw, zwart',
  'uitnodiging': 'Laat dit eerst bezinken.',
  'waarschuwing': 'zijn je zorgen terecht?'},
 {'getal': '10',
  'kernwoord': 'BEEINDIGEN',
  'kleur': 'Zwaarden',
  'naam': 'X',
  'opmerking': '',
  'steekwoorden': 'destructieve gedachten, voortijdig einde',
  'symbolen': 'water, zon, heuvels, rood kleed, zegening, zwart',
  'uitnodiging': 'Waar moet je nu rigoureus een streep onder zetten?',
  'waarschuwing': 'Is het verstandig om er nu radicaal mee te breken?'},
 {'getal': '',
  'kernwoord': 'ALERT',
  'kleur': 'Zwaarden',
  'naam': 'Page',
  'opmerking': '',
  'steekwoorden': 'verstand van zaken, opmerkzaam, escalatie',
  'symbolen': 'wolken, heuvels, vogel, water, grijs, zwaard geheven',
  'uitnodiging': 'Laat het over je heen komen',
  'waarschuwing': 'Komt de dreiging wel van buiten?'},
 {'getal': '',
  'kernwoord': 'ONSTUIMIG',
  'kleur': 'Zwaarden',
  'naam': 'Ridder',
  'opmerking': '',
  'steekwoorden': 'onverwachte doorbraak, confrontatie, bekwaamheid, dapperheid',
  'symbolen': 'oranje, rood kleed, paard, harnas, vogel',
  'uitnodiging': 'Bezint, eer ge begint',
  'waarschuwing': 'Is dit geen storm in een glas water?'},
 {'getal': '',
  'kernwoord': 'WIJS',
  'kleur': 'Zwaarden',
  'naam': 'Koningin',
  'opmerking': '',
  'steekwoorden': 'innerlijke overtuiging, eerlijkheid, levenswijsheid, heldere/rustige geest, deugdzaam, streng',
  'symbolen': 'afgewend, wolken, troon, kroon, wit kleed, volwassen vrouw, zwaard geheven, cupido, vogel, grijs',
  'uitnodiging': 'Blijf bij de hoofdzaken',
  'waarschuwing': 'Wat is de meest logische verklaring?'},
 {'getal': '',
  'kernwoord': 'DENKER',
  'kleur': 'Zwaarden',
  'naam': 'Koning',
  'opmerking': '',
  'steekwoorden': 'De gedachte gaat aan de manifestatie vooraf, handhaver, rationeel, skeptisch, hard, dominant',
  'symbolen': 'troon, kroon, blauw, paars kleed, wolken, heuvels, boom, zwaard geheven, vogel',
  'uitnodiging': 'Kom tot een conclusie',
  'waarschuwing': 'Schenk ook aandacht aan de relatie'},
 {'getal': '',
  'kernwoord': 'OVERVLOED',
  'kleur': 'Kelken',
  'naam': 'Aas',
  'opmerking': '',
  'steekwoorden': 'verlangen naar eenheid en verbondenheid, overgave, bewustwording, de bron, de Graal.',
  'symbolen': 'rechts, hand, wolken, waterbron, duif, yod, lelie, hostie, blauw',
  'uitnodiging': 'Laat je gevoel stromen.',
  'waarschuwing': 'Laat deze kans niet schieten'},
 {'getal': '2',
  'kernwoord': 'VERBINDEN',
  'kleur': 'Kelken',
  'naam': 'II',
  'opmerking': '',
  'steekwoorden': 'verlangen naar een partner (eventueel platonisch), gevoel vs verstand, valse liefde',
  'symbolen': 'lauwerkrans, roos, slang, leeuw, heuvels, hermesvleugels',
  'uitnodiging': 'Treed de ander liefdevol tegemoet',
  'waarschuwing': 'Sta ik open voor een eerlijk compromis?'},
 {'getal': '3',
  'kernwoord': 'FEESTEN',
  'kleur': 'Kelken',
  'naam': 'III',
  'opmerking': '',
  'steekwoorden': 'plezier hebben, blijheid, genezing, troost',
  'symbolen': 'druiven, bloemen, rood kleed, geel kleed, wit kleed, blauw',
  'uitnodiging': 'Laat jezelf eens lekker gaan.',
  'waarschuwing': 'Succes moet je vieren'},
 {'getal': '4',
  'kernwoord': 'MOPPEREN',
  'kleur': 'Kelken',
  'naam': 'IV',
  'opmerking': '',
  'steekwoorden': 'verlangen naar meer, lusteloosheid',
  'symbolen': 'hand, wolken, boom, links',
  'uitnodiging': 'Wat heb je w\xc3\xa9l?',
  'waarschuwing': 'Is je onvrede wel terecht?'},
 {'getal': '5',
  'kernwoord': 'BETREUREN',
  'kleur': 'Kelken',
  'naam': 'V',
  'opmerking': '',
  'steekwoorden': 'teleurstelling, verlies, desillusie',
  'symbolen': 'grijs, stroom, brug, burcht, afgewend, zwart kleed, bloed, groen',
  'uitnodiging': 'Wat blijft er over?',
  'waarschuwing': 'Blijven hangen in verdriet.'},
 {'getal': '6',
  'kernwoord': 'HERINNEREN',
  'kleur': 'Kelken',
  'naam': 'VI',
  'opmerking': '',
  'steekwoorden': 'verbinden, delen vanuit overvloed, vreugde schenken, (zinloze) nostalgie',
  'symbolen': 'dwaas, vrouw, lelie, burcht',
  'uitnodiging': 'Verheug je in kleine dingen.',
  'waarschuwing': 'Behoudt het goede'},
 {'getal': '7',
  'kernwoord': 'MISLEIDEN',
  'kleur': 'Kelken',
  'naam': 'VII',
  'opmerking': '',
  'steekwoorden': 'visioenen, illusie, mystery guest, verbeelding, vergankelijke weelde',
  'symbolen': 'slang, lauwerkrans, draak, edelstenen, burcht, engel, wolken, afgewend, doodshoofd, zwart',
  'uitnodiging': 'Wat heb je werkelijk nodig?',
  'waarschuwing': 'Klatergoud.'},
 {'getal': '8',
  'kernwoord': 'WEGLOPEN',
  'kleur': 'Kelken',
  'naam': 'VIII',
  'opmerking': '',
  'steekwoorden': 'illusies achter je laten, het roer om, een nieuw pad kiezen',
  'symbolen': 'maan, water, berg, rood kleed, blauw',
  'uitnodiging': 'Laat het verleden los.',
  'waarschuwing': 'Een nieuwe illusie najagen.'},
 {'getal': '9',
  'kernwoord': 'WAARDEREN',
  'kleur': 'Kelken',
  'naam': 'IX',
  'opmerking': '',
  'steekwoorden': 'evenwichtigheid, dromen zijn werkelijkheid geworden, innerlijk geluk',
  'symbolen': 'blauw kleed',
  'uitnodiging': 'Sta eens stil om \xc3\xa9cht te genieten',
  'waarschuwing': 'Kan je je zorgen loslaten en genieten?'},
 {'getal': '10',
  'kernwoord': 'THUISKOMEN',
  'kleur': 'Kelken',
  'naam': 'X',
  'opmerking': '',
  'steekwoorden': 'welzijn, voltooiing, samen (gezin/dorp/gemeente), veilig, geborgen',
  'symbolen': 'regenboog, stroom, gezin, huis, afgewend',
  'uitnodiging': 'Maak ruimte voor gezamenlijk geluk',
  'waarschuwing': 'Wat van ver komt is niet altijd lekkerder'},
 {'getal': '',
  'kernwoord': 'VERWONDERD',
  'kleur': 'Kelken',
  'naam': 'Page',
  'opmerking': '',
  'steekwoorden': 'fantasie, verbeelding, puberteit, vlijtige jeugd',
  'symbolen': 'lotus, vis, golven, blauw',
  'uitnodiging': 'Laat je verwonderen',
  'waarschuwing': 'Pas op voor goedgelovigheid.'},
 {'getal': '',
  'kernwoord': 'VERZOENER',
  'kleur': 'Kelken',
  'naam': 'Ridder',
  'opmerking': '',
  'steekwoorden': 'aanvoelen, betrokkenheid, waarheidsvinding, voorstel',
  'symbolen': 'hermesvleugels, harnas, paard, stroom, heuvels, vis, afgewend, blauw',
  'uitnodiging': 'Met wie wil je vrede sluiten?',
  'waarschuwing': 'Zorg voor een goede verstandhouding.'},
 {'getal': '',
  'kernwoord': 'ZIENER',
  'kleur': 'Kelken',
  'naam': 'Koningin',
  'opmerking': '',
  'steekwoorden': 'inlevingsvermogen, innerlijk weten, visioenen/dromerig, gedistingeerd',
  'symbolen': 'golven, troon, kroon, wit kleed, afgewend, blauw',
  'uitnodiging': 'Erover praten kan je beeld verhelderen.',
  'waarschuwing': 'Vergeet jezelf niet'},
 {'getal': '',
  'kernwoord': 'RAADSMAN',
  'kleur': 'Kelken',
  'naam': 'Koning',
  'opmerking': '',
  'steekwoorden': 'bewustwording, compassie, gevoelig man, onderhandelaar, brede belangstelling, wetsman, wetenschapper',
  'symbolen': 'golven, vis, boot, kroon, troon, scepter, geel kleed, blauw',
  'uitnodiging': 'Ben jij een rots in de branding?',
  'waarschuwing': 'Vergeet je eigen gevoelens niet'}]

symbols = [{'betekenis': 'de grote geheimen van het leven, archetypes',
  'naam': 'Grote Arcana',
  'zie': ''},
 {'betekenis': 'verwerven van eigenschappen en innerlijke kwaliteiten',
  'naam': 'Grote Arcana 1-10',
  'zie': ''},
 {'betekenis': 'leren omgaan met de ervaringen die het leven brengt',
  'naam': 'Grote Arcana 11-20',
  'zie': ''},
 {'betekenis': 'geheimen van het alledaagse leven',
  'naam': 'Kleine Arcana',
  'zie': ''},
 {'betekenis': '', 'naam': '', 'zie': ''},
 {'betekenis': 'Doen (dingen die je zelf in de hand hebt)',
  'naam': 'getallen',
  'zie': ''},
 {'betekenis': 'Zijn (invloeden van/naar je omgeving)',
  'naam': 'hofkaart',
  'zie': ''},
 {'betekenis': '', 'naam': '', 'zie': ''},
 {'betekenis': 'willen/initiatief, intu\xc3\xaftie/idee\xc3\xabn, uitvoerend, boeren/arbeiders',
  'naam': 'Staven',
  'zie': 'vuur'},
 {'betekenis': 'doen, zintuigen/praktisch, operationeel, ambachtslieden/handelaars',
  'naam': 'Pentakels',
  'zie': 'Aarde, V'},
 {'betekenis': 'denken, verstand, tactisch, adel',
  'naam': 'Zwaarden',
  'zie': 'lucht'},
 {'betekenis': 'voelen, emotie, strategisch, geestelijkheid/staatslieden',
  'naam': 'Kelken',
  'zie': 'water'},
 {'betekenis': '', 'naam': '', 'zie': ''},
 {'betekenis': '', 'naam': 'staf', 'zie': 'staven'},
 {'betekenis': '', 'naam': 'Pentakel', 'zie': 'pentakels'},
 {'betekenis': '', 'naam': 'zwaard', 'zie': 'zwaarden'},
 {'betekenis': '', 'naam': 'Kelk', 'zie': 'kelken'},
 {'betekenis': '', 'naam': '', 'zie': ''},
 {'betekenis': '', 'naam': 'klavers', 'zie': 'staven'},
 {'betekenis': '', 'naam': 'ruiten', 'zie': 'pentakels'},
 {'betekenis': '', 'naam': 'schoppen', 'zie': 'zwaarden'},
 {'betekenis': '', 'naam': 'harten', 'zie': 'kelken'},
 {'betekenis': '', 'naam': '', 'zie': ''},
 {'betekenis': '', 'naam': '', 'zie': ''},
 {'betekenis': 'leegte, alomvattendheid, kosmische invloed',
  'naam': 'O',
  'zie': ''},
 {'betekenis': 'Potentie, eenheid, oorsprong', 'naam': 'I', 'zie': ''},
 {'betekenis': 'Dualiteit, spiegelbeeld', 'naam': 'II', 'zie': ''},
 {'betekenis': 'groei, vruchtbaarheid, gilden: leerling',
  'naam': 'III',
  'zie': 'Drie-eenheid'},
 {'betekenis': 'stabiliteit, vorming, rechtvaardig, materie',
  'naam': 'IV',
  'zie': 'elementen'},
 {'betekenis': 'doorzetten, zoeken, zingeving, gilden: gezel',
  'naam': 'V',
  'zie': 'zintuigen'},
 {'betekenis': 'kantelpunt, dienstvaardigheid', 'naam': 'VI', 'zie': ''},
 {'betekenis': 'Zelfkennnis, paradox, toeval, gilden: meester',
  'naam': 'VII',
  'zie': ''},
 {'betekenis': 'kiezen, karma, promiscu', 'naam': 'VIII', 'zie': ''},
 {'betekenis': 'vervulling, horizon, gilden: bouwmeester',
  'naam': 'IX',
  'zie': ''},
 {'betekenis': 'Climax, overgang, einde=begin', 'naam': 'X', 'zie': ''},
 {'betekenis': 'openbaring, inspiratie', 'naam': 'XI', 'zie': ''},
 {'betekenis': 'volledigheid, perfectie, deelbaarheid',
  'naam': 'XII',
  'zie': ''},
 {'betekenis': '', 'naam': '', 'zie': ''},
 {'betekenis': 'waar je mee begint', 'naam': 'aas', 'zie': 'I'},
 {'betekenis': 'boodschapper, nieuwsgierig, kans',
  'naam': 'page',
  'zie': 'jonge man'},
 {'betekenis': 'strijder, werker, beschermen van zwakkeren ',
  'naam': 'ridder',
  'zie': ''},
 {'betekenis': 'wijsheid, volwassenheid',
  'naam': 'koningin',
  'zie': 'volwassen vrouw'},
 {'betekenis': 'gezag, competentie, wereldlijke macht',
  'naam': 'koning',
  'zie': 'volwassen man'},
 {'betekenis': '', 'naam': '', 'zie': ''},
 {'betekenis': 'vruchtbaarheid', 'naam': 'aarde', 'zie': ''},
 {'betekenis': '', 'naam': 'adept', 'zie': 'monnik'},
 {'betekenis': 'terugblikken', 'naam': 'afgewend', 'zie': ''},
 {'betekenis': 'religie', 'naam': 'altaar', 'zie': ''},
 {'betekenis': 'eeuwig leven', 'naam': 'ankh', 'zie': 'scepter'},
 {'betekenis': '', 'naam': 'ankh', 'zie': 'jakhalsgod'},
 {'betekenis': 'boom van kennis (van goed en kwaad), bewustzijn',
  'naam': 'appelboom',
  'zie': ''},
 {'betekenis': 'geheimen', 'naam': 'arcana', 'zie': ''},
 {'betekenis': 'god ziet de mens', 'naam': 'arend', 'zie': 'water, feniks'},
 {'betekenis': 'diepe trance, verandering in bewustzijn',
  'naam': 'aureool',
  'zie': ''},
 {'betekenis': '', 'naam': 'baldakijn', 'zie': 'troonhemel'},
 {'betekenis': 'melaatsheid, ziekte', 'naam': 'bel', 'zie': ''},
 {'betekenis': 'standvastigheid, aarde, mystieke reis',
  'naam': 'berg',
  'zie': ''},
 {'betekenis': 'plaats dicht bij god', 'naam': 'bergtop', 'zie': 'berg'},
 {'betekenis': 'uiterlijke religie, kerkelijke macht',
  'naam': 'bisschop',
  'zie': 'geestelijke'},
 {'betekenis': 'rust, vrede, intelligentie, stabiliteit, loyaal, conservatief, koelheid',
  'naam': 'blauw',
  'zie': ''},
 {'betekenis': '', 'naam': 'blauw kleed', 'zie': 'blauw'},
 {'betekenis': 'goddelijke communicatie, vernietiging',
  'naam': 'bliksem',
  'zie': ''},
 {'betekenis': 'onwetendheid, verblinding, overgeleverd zijn aan het lot',
  'naam': 'blinddoek',
  'zie': ''},
 {'betekenis': 'liefde, levenskracht', 'naam': 'bloed', 'zie': ''},
 {'betekenis': 'natuurlijke levenskracht, levensvreugde, actief en viriel',
  'naam': 'bloemen',
  'zie': ''},
 {'betekenis': '', 'naam': 'Bloemenkrans', 'zie': 'bloemen'},
 {'betekenis': 'bevestigen, strengheid (intentie)', 'naam': 'Boaz', 'zie': ''},
 {'betekenis': 'kennisbron', 'naam': 'boek', 'zie': ''},
 {'betekenis': 'intu\xc3\xaftieve bron', 'naam': 'boekrol', 'zie': 'boek'},
 {'betekenis': '', 'naam': 'boog', 'zie': 'poort'},
 {'betekenis': 'levenskracht', 'naam': 'boom', 'zie': ''},
 {'betekenis': 'Verre reis (door de onderwereld?)', 'naam': 'boot', 'zie': ''},
 {'betekenis': 'verborgen vruchtbaarheid, de mogelijkheid te cree\xc3\xabren en te vermenigvuldigen zonder de ander/Ander, androgyne figuur',
  'naam': 'borsten',
  'zie': ''},
 {'betekenis': 'overgang', 'naam': 'brug', 'zie': ''},
 {'betekenis': 'bescherming, veilige thuishaven', 'naam': 'burcht', 'zie': ''},
 {'betekenis': 'liefde', 'naam': 'cupido', 'zie': ''},
 {'betekenis': 'harmonie', 'naam': 'davidsster', 'zie': ''},
 {'betekenis': 'de dood, sterfelijkheid', 'naam': 'doodshoofd', 'zie': ''},
 {'betekenis': 'tegenstander, schatbewaker, onsterfelijkheid',
  'naam': 'draak',
  'zie': 'vuur, slang'},
 {'betekenis': 'geest/ziel/lichaam, vader/zoon/heilige geest, hemel/aarde/hel',
  'naam': 'drie-eenheid',
  'zie': ''},
 {'betekenis': 'geest', 'naam': 'driehoek', 'zie': 'III, vuur'},
 {'betekenis': 'overvloed, rijke oogst', 'naam': 'druiven', 'zie': ''},
 {'betekenis': 'genade, vrede, hoop', 'naam': 'druppel', 'zie': ''},
 {'betekenis': 'brenger van vrede, heilige geest', 'naam': 'duif', 'zie': ''},
 {'betekenis': '', 'naam': 'dwaas', 'zie': 'de dwaas'},
 {'betekenis': 'hebzucht, materialisme', 'naam': 'edelstenen', 'zie': ''},
 {'betekenis': '', 'naam': 'elementen', 'zie': 'water, vuur, lucht, aarde'},
 {'betekenis': 'boodschapper van god, oorsprong van de mens',
  'naam': 'engel',
  'zie': 'lucht'},
 {'betekenis': 'verjonging (door drievoudige onderdompeling in water), herboren ziel',
  'naam': 'feniks',
  'zie': ''},
 {'betekenis': '(zon) levenskracht en warmte, nadenken, vrolijkheid, creativiteit, afgunst, onrust',
  'naam': 'geel',
  'zie': ''},
 {'betekenis': '', 'naam': 'geel kleed', 'zie': 'geel'},
 {'betekenis': 'toewijding, toetreding',
  'naam': 'geestelijke',
  'zie': 'hi\xc3\xabrofant'},
 {'betekenis': 'voedster, doorzettingsvermogen, seksueel plezier',
  'naam': 'geit',
  'zie': ''},
 {'betekenis': 'huiselijk geluk', 'naam': 'gezin', 'zie': ''},
 {'betekenis': 'de wereld ontdekken/veroveren', 'naam': 'globe', 'zie': ''},
 {'betekenis': 'wisselende stemmingen, wisselend succes',
  'naam': 'golven',
  'zie': 'water'},
 {'betekenis': '', 'naam': 'graan', 'zie': 'koren'},
 {'betekenis': 'mensen in groep', 'naam': 'granaatappel', 'zie': ''},
 {'betekenis': 'harmonie (zwart en wit gemengd), rust en onopvallendheid, evenwicht, wijsheid',
  'naam': 'grijs',
  'zie': 'zwart, wit'},
 {'betekenis': 'eenvoud, bewust leven', 'naam': 'grijs kleed', 'zie': 'grijs'},
 {'betekenis': 'groei, ontwikkeling, harmonie, ontspanning, verveling, weerstand',
  'naam': 'groen',
  'zie': 'blauw, geel'},
 {'betekenis': 'afremmen, rusten, verlagen',
  'naam': 'groen kleed',
  'zie': 'groen'},
 {'betekenis': '', 'naam': 'groene omgeving', 'zie': 'natuur'},
 {'betekenis': '', 'naam': 'haag', 'zie': 'muur'},
 {'betekenis': 'vruchtbaarheid, opofferingsgezindheid, loyaal',
  'naam': 'haas',
  'zie': ''},
 {'betekenis': 'kracht, activiteit', 'naam': 'hamer', 'zie': ''},
 {'betekenis': 'hand van god', 'naam': 'hand', 'zie': ''},
 {'betekenis': 'mannelijkheid, beschermer, streng, onbuigzaam',
  'naam': 'harnas',
  'zie': ''},
 {'betekenis': 'vrouw, aantrekkingskracht, emoties, het onbewuste',
  'naam': 'hartvorm',
  'zie': ''},
 {'betekenis': '', 'naam': 'hermanubis', 'zie': 'jakhalsgod'},
 {'betekenis': 'boodschapper van de goden', 'naam': 'hermes', 'zie': ''},
 {'betekenis': '', 'naam': 'hermesvleugels', 'zie': 'hermes'},
 {'betekenis': 'initiatie, vruchtbaarheid', 'naam': 'heuvels', 'zie': ''},
 {'betekenis': '', 'naam': 'hi\xc3\xabrofant', 'zie': 'hogepriester'},
 {'betekenis': 'trouw, waakzaam, getemd, kent de weg, ongebreidelde lust, instinct',
  'naam': 'hond',
  'zie': ''},
 {'betekenis': 'getemde en ongetemde energi\xc3\xabn (in de mens)',
  'naam': 'hond + wolf',
  'zie': ''},
 {'betekenis': 'offer', 'naam': 'hostie', 'zie': ''},
 {'betekenis': 'geborgenheid, thuis', 'naam': 'huis', 'zie': 'gezin'},
 {'betekenis': 'boodschappers', 'naam': 'iris', 'zie': ''},
 {'betekenis': 'kracht, mededogen (vorm)', 'naam': 'Jachin', 'zie': ''},
 {'betekenis': 'voorbode van de dood, begeleider van zielen naar onderwereld',
  'naam': 'jakhalsgod',
  'zie': ''},
 {'betekenis': 'de geheime, onuitspreekbare naam van God',
  'naam': 'Jahwe',
  'zie': ''},
 {'betekenis': '', 'naam': 'jod', 'zie': 'yod'},
 {'betekenis': 'energie, initiatief', 'naam': 'jonge man', 'zie': 'man'},
 {'betekenis': 'vruchtbaar, zuiver', 'naam': 'jonge vrouw', 'zie': 'vrouw'},
 {'betekenis': '', 'naam': 'kasteel', 'zie': 'burcht'},
 {'betekenis': 'gebondenheid, verbondenheid', 'naam': 'ketens', 'zie': ''},
 {'betekenis': 'goddelijke onschuld, het resultaat van de samensmelting tussen de mannelijke en vrouwelijke energie, einde van de dualiteit, vernieuwde eenheid',
  'naam': 'kind',
  'zie': ''},
 {'betekenis': 'wereldse bezittingen', 'naam': 'knapzak', 'zie': ''},
 {'betekenis': 'rijke oogst, toegeweid moederschap, scheppende kracht',
  'naam': 'koren',
  'zie': ''},
 {'betekenis': 'primitief dier, de angsten en illusies willen zich manifesteren, rusteloosheid',
  'naam': 'kreeft',
  'zie': ''},
 {'betekenis': 'circulair proces, eenheid van alles',
  'naam': 'kringloop',
  'zie': ''},
 {'betekenis': 'wereldse macht, talent, meesterschap',
  'naam': 'kroon',
  'zie': ''},
 {'betekenis': 'religie', 'naam': 'kruis', 'zie': ''},
 {'betekenis': 'het aardse', 'naam': 'kubus', 'zie': ''},
 {'betekenis': 'geest', 'naam': 'kwik', 'zie': ''},
 {'betekenis': 'wegwijzen', 'naam': 'lantaarn', 'zie': ''},
 {'betekenis': 'vergankelijke macht, zegeviering na (innerlijke) strijd',
  'naam': 'lauwerkrans ',
  'zie': ''},
 {'betekenis': 'moedige bewaker van grenzen, gevestigde macht, eenling, koning der dieren',
  'naam': 'leeuw',
  'zie': 'vuur'},
 {'betekenis': 'hartverlangens, maagdelijkheid, reinheid, onschuld, goddelijke genade/gaven',
  'naam': 'lelie',
  'zie': ''},
 {'betekenis': 'oneindige verbondenheid, heilige geest',
  'naam': 'lemniscaat',
  'zie': ''},
 {'betekenis': 'fallussymbool (zie ook yoni)', 'naam': 'lingam', 'zie': ''},
 {'betekenis': 'vrouwelijke kant, intu\xc3\xaftie, binnen, verleden',
  'naam': 'links',
  'zie': ''},
 {'betekenis': 'gedachtenwereld', 'naam': 'linksboven', 'zie': ''},
 {'betekenis': 'spiritualiteit, kunst, inzicht, zelfvernieuwing',
  'naam': 'lotus',
  'zie': ''},
 {'betekenis': 'denken, liefhebben, van iedereen', 'naam': 'lucht', 'zie': ''},
 {'betekenis': '(nog) niet seksueel actief',
  'naam': 'maagd',
  'zie': 'jonge vrouw'},
 {'betekenis': 'gids in donkere tijden (de maan reflecteert het licht van de zon), passiviteit',
  'naam': 'maan',
  'zie': 'vrouw'},
 {'betekenis': 'zichtbare, spirituele leider', 'naam': 'man', 'zie': ''},
 {'betekenis': 'liefde, huwelijk, vruchtbaarheid', 'naam': 'mirte', 'zie': ''},
 {'betekenis': 'aanbidding, onderwerping', 'naam': 'monnik', 'zie': ''},
 {'betekenis': 'veiligheid, bescherming, het sensitieve leven is afgescheiden van het goddelijke leven',
  'naam': 'muur',
  'zie': ''},
 {'betekenis': 'vrijheid, niets te verbergen, kwetsbaarheid',
  'naam': 'naaktheid',
  'zie': ''},
 {'betekenis': 'werken met en in de natuur', 'naam': 'natuur', 'zie': ''},
 {'betekenis': 'vrede', 'naam': 'olijfblad', 'zie': ''},
 {'betekenis': 'omgekeerde zienswijze', 'naam': 'ondersteboven', 'zie': ''},
 {'betekenis': 'zegebrengend', 'naam': 'oosten', 'zie': ''},
 {'betekenis': 'passie, hartstocht, optimisme, overdaad, losbandig',
  'naam': 'oranje',
  'zie': 'geel, rood'},
 {'betekenis': 'ervaren, bewust van zijn pad', 'naam': 'oude man', 'zie': ''},
 {'betekenis': 'wijsheid', 'naam': 'oude man', 'zie': ''},
 {'betekenis': 'slangengordel', 'naam': 'ourobouros', 'zie': 'kringloop'},
 {'betekenis': 'kracht en vitaliteit, edel en intelligent, fierheid, werklust',
  'naam': 'paard',
  'zie': ''},
 {'betekenis': 'inventiviteit, inspiratie, originaliteit, spiritualiteit, boete doen',
  'naam': 'paars',
  'zie': ''},
 {'betekenis': '', 'naam': 'paars kleed', 'zie': 'paars'},
 {'betekenis': 'reis, bestemming, herkomst', 'naam': 'pad', 'zie': ''},
 {'betekenis': 'stijgen naar hoger niveau', 'naam': 'palmhart', 'zie': ''},
 {'betekenis': 'overwinning', 'naam': 'palmtak', 'zie': ''},
 {'betekenis': 'vrouw, verleiding', 'naam': 'parels', 'zie': ''},
 {'betekenis': 'de nieuwe mens, het universum, elementen + ether (geest)',
  'naam': 'pentagram',
  'zie': 'pentakel, zintuigen'},
 {'betekenis': 'wijsheid, evenwicht in de wereld',
  'naam': 'pilaren',
  'zie': ''},
 {'betekenis': 'doorgang, toegang, naar hemel/hel',
  'naam': 'poort',
  'zie': ''},
 {'betekenis': 'energie, occulte wijsheid, universele wetten',
  'naam': 'pyramide',
  'zie': ''},
 {'betekenis': 'cyclus', 'naam': 'rad', 'zie': ''},
 {'betekenis': 'daadkracht, onvoorzichtig, onvoorspelbaar, autoriteit, leiderschap, aggressiviteit',
  'naam': 'ram',
  'zie': ''},
 {'betekenis': 'fysieke wereld', 'naam': 'rechtsonder', 'zie': ''},
 {'betekenis': 'mannelijke kant, verstand, buiten, toekomst',
  'naam': 'rechts',
  'zie': 'oosten'},
 {'betekenis': 'schoonspoelen', 'naam': 'regen', 'zie': ''},
 {'betekenis': 'zegen van boven, goddelijke bescherming, (geestelijke) rijkdom',
  'naam': 'regenboog',
  'zie': ''},
 {'betekenis': 'macht over aarde', 'naam': 'rijksappel', 'zie': ''},
 {'betekenis': 'waterbron', 'naam': 'rivier', 'zie': ''},
 {'betekenis': 'koninklijke waardigheid, hartstochtelijke liefde, levenskracht',
  'naam': 'robijn',
  'zie': ''},
 {'betekenis': 'Hartstocht, fysieke manifestatie, actie, macht, levenskracht',
  'naam': 'rood',
  'zie': ''},
 {'betekenis': '', 'naam': 'rood kleed', 'zie': 'rood'},
 {'betekenis': 'hartverlangens', 'naam': 'roos', 'zie': ''},
 {'betekenis': 'geeft gemoedsrust,  fysieke/geestelijke/spirituele harmonie, helpt te concentreren, verlicht stress, verbondenheid met de Goddelijke wereld',
  'naam': 'saffier',
  'zie': ''},
 {'betekenis': 'geestelijk inzicht, ziel',
  'naam': 'salamander',
  'zie': 'vuur'},
 {'betekenis': 'wereldse macht', 'naam': 'scepter', 'zie': ''},
 {'betekenis': '', 'naam': 'schip', 'zie': 'boot'},
 {'betekenis': '', 'naam': 'schriftrol', 'zie': 'tora'},
 {'betekenis': 'wijsheid, levensvragen, macht, middelpunt, balans',
  'naam': 'sfinx',
  'zie': ''},
 {'betekenis': 'verleiding, onderwereld, dodenrijk',
  'naam': 'slang',
  'zie': 'kringloop'},
 {'betekenis': 'meesterschap, toegang (tot de hemel), open en sluiten',
  'naam': 'sleutel',
  'zie': ''},
 {'betekenis': 'mysterie, ontdekken', 'naam': 'sluier', 'zie': ''},
 {'betekenis': 'herkomst', 'naam': 'stadsmuur', 'zie': ''},
 {'betekenis': 'verdrijft als ochtendster de duisternis,  vruchtbaarheid',
  'naam': 'ster (achtpuntig)',
  'zie': ''},
 {'betekenis': 'hemel', 'naam': 'sterren', 'zie': ''},
 {'betekenis': 'offeren, mannelijke vruchtbaarheid, agressie, vechtlust',
  'naam': 'stier',
  'zie': 'aarde'},
 {'betekenis': 'zichtbare mysterie', 'naam': 'stroom', 'zie': 'waterbron'},
 {'betekenis': 'goddelijke energie, verschroe\xc3\xafng',
  'naam': 'toorts',
  'zie': ''},
 {'betekenis': 'goddelijke wet of leer', 'naam': 'tora', 'zie': ''},
 {'betekenis': 'menselijke hoogmoed, huis van God, toren van Babel, de hel',
  'naam': 'toren',
  'zie': ''},
 {'betekenis': 'oproep van de Hogere Natuur ', 'naam': 'bazuin', 'zie': ''},
 {'betekenis': 'macht', 'naam': 'troon', 'zie': ''},
 {'betekenis': '', 'naam': 'troonhemel', 'zie': 'troon'},
 {'betekenis': 'keuze', 'naam': 'tweesprong', 'zie': ''},
 {'betekenis': 'zijn wapen is het leven zelf', 'naam': 'vaandel', 'zie': ''},
 {'betekenis': 'adel, koninklijk, alziend oog, onkwetsbaar',
  'naam': 'valk',
  'zie': ''},
 {'betekenis': 'godin van liefde en vruchtbaarheid',
  'naam': 'venussymbool',
  'zie': ''},
 {'betekenis': 'materie', 'naam': 'vierkant', 'zie': 'IV, aarde'},
 {'betekenis': 'het stoffelijke en het geestelijke',
  'naam': 'vierkant met driehoek',
  'zie': 'vierkant, driehoek, VII'},
 {'betekenis': 'verschuilen', 'naam': 'vijgenblad', 'zie': ''},
 {'betekenis': 'diepgaande transformatie, inwijding',
  'naam': 'vis',
  'zie': ''},
 {'betekenis': 'onze tijd van leven vervliegt bij dag en nacht, bij goed en kwaad',
  'naam': 'vleermuisvleugels',
  'zie': ''},
 {'betekenis': 'vrijheid, van ver halen', 'naam': 'vogel', 'zie': ''},
 {'betekenis': '', 'naam': 'vogelpoten', 'zie': ''},
 {'betekenis': 'viriele, beschermende kracht',
  'naam': 'volwassen man',
  'zie': 'man'},
 {'betekenis': 'actieve, vruchtbare kracht, moeder',
  'naam': 'Volwassen vrouw',
  'zie': 'vrouw'},
 {'betekenis': 'verborgen, innerlijk (tegenovergesteld bij ontbreken)',
  'naam': 'voorhang (bij pilaren)',
  'zie': ''},
 {'betekenis': 'intu\xc3\xaftie, ontvankelijk', 'naam': 'vrouw', 'zie': ''},
 {'betekenis': 'kracht, zowel verterend als reinigend',
  'naam': 'vuur',
  'zie': ''},
 {'betekenis': 'Emoties, gevoelens, oerzee, spiegel, de diepte van de ziel, het nog niet gemanifesteerde',
  'naam': 'water',
  'zie': ''},
 {'betekenis': 'geneeskrachtig', 'naam': 'waterbron', 'zie': 'water'},
 {'betekenis': 'evenwicht, rechtvaardigheid, juiste verhoudingen, voortdurende aanpassing om gerechtigheid te garanderen',
  'naam': 'weegschaal',
  'zie': ''},
 {'betekenis': '', 'naam': 'wereldbol', 'zie': 'globe'},
 {'betekenis': 'wedergeboorte, opstanding', 'naam': 'wijnhuisslak', 'zie': ''},
 {'betekenis': "onschuld, open, zuiver, \xe2\x80\x98ware' spiritualiteit, na\xc3\xafviteit, leegte, perfectionisme",
  'naam': 'wit',
  'zie': ''},
 {'betekenis': '', 'naam': 'wit kleed', 'zie': 'wit'},
 {'betekenis': 'scheiding tussen zichtbare en onzichtbare wereld',
  'naam': 'wolken',
  'zie': ''},
 {'betekenis': 'zie tweesprong', 'naam': 'Y-vorm', 'zie': ''},
 {'betekenis': 'het kleinste teken van het Hebreeuwse alfabet (druppel/blad-vorm) en de eerste letter van de naam van God: JHWH',
  'naam': 'yod',
  'zie': 'druppel'},
 {'betekenis': 'vrouwelijke geslachtsorganen (zie lingam)',
  'naam': 'yoni',
  'zie': ''},
 {'betekenis': 'cree\xc3\xabren van evenwicht', 'naam': 'zegening', 'zie': ''},
 {'betekenis': 'horen, zien, ruiken, proeven, voelen',
  'naam': 'zintuigen',
  'zie': ''},
 {'betekenis': 'het licht dat de mensheid leidt, schepper, God, levenskracht',
  'naam': 'zon',
  'zie': ''},
 {'betekenis': 'waarheidslievend, wilskracht en vitaliteit, roem en overwinning',
  'naam': 'zonnebloem',
  'zie': 'zon'},
 {'betekenis': 'fysiek lichaam', 'naam': 'zout', 'zie': ''},
 {'betekenis': 'scherpzinnigheid, gerechtigheid',
  'naam': 'zwaard geheven',
  'zie': ''},
 {'betekenis': 'nacht, duisternis, rebellie, mysterie',
  'naam': 'zwart',
  'zie': ''},
 {'betekenis': 'rouw, verdriet', 'naam': 'zwart kleed', 'zie': 'zwart'},
 {'betekenis': 'Vrijheidsdrang, intu\xc3\xaftieve gaven, magie, ongeluk, waarschuwer',
  'naam': 'zwarte kat',
  'zie': 'zwart'},
 {'betekenis': 'ziel', 'naam': 'zwavel', 'zie': ''}]
