from collections import OrderedDict

cards = [OrderedDict([('serie', 'groot'),
              ('nummer', 'O'),
              ('naam', 'De Dwaas'),
              ('opmerking', 'De Zot'),
              ('kernwoord', 'NAÏVITEIT'),
              ('steekwoord',
               'Onschuld, onervarenheid, het ongevormde, ijdelheid'),
              ('advies', 'Je spontaniteit is een pré.'),
              ('waarschuwing',
               'Gedachteloosheid, je overziet de consequenties niet.'),
              ('symbolen',
               'jonge man, roos, staf, zon, berg, hond, bloemenkrans')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'I'),
              ('naam', 'De Magier'),
              ('opmerking', ''),
              ('kernwoord', 'BEGAAFDHEID'),
              ('steekwoord',
               'Bewust van kracht en mogelijkheden, je (leer)proces aangaan, '
               'diplomatie'),
              ('advies', 'Richt je op wat je wél kunt.'),
              ('waarschuwing', 'Je neemt teveel hooi op je vork.'),
              ('symbolen',
               'natuur, roos, lelie,baldakijn, altaar, zwaard, staf, kelk, '
               'pentakel, jonge man, ourobouros, lemniscaat, bloemen')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'II'),
              ('naam', 'De Hogepriesteres'),
              ('opmerking', ''),
              ('kernwoord', 'INTUÏTIE'),
              ('steekwoord',
               'Gebruik je verbeelding om het mysterie te ontsluieren. Je '
               'eigen wijsheid, diepgang.'),
              ('advies', 'Vertrouw op je eigen gevoel.'),
              ('waarschuwing', 'Betovering, hou je bij de feiten.'),
              ('symbolen',
               'jonge vrouw, sluier, kroon, troon, palmhart, granaatappel, '
               'maan, kruis, schriftrol, pilaren, boaz, jachin, blauw')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'III'),
              ('naam', 'De Keizerin'),
              ('opmerking', ''),
              ('kernwoord', 'SCHOONHEID'),
              ('steekwoord',
               'Ontspanning, de overvloed van het leven en de kracht van de '
               'bloeiende aarde.'),
              ('advies', 'Geniet van wat je hebt.'),
              ('waarschuwing', 'Luiheid, hebzucht.'),
              ('symbolen',
               'volwassen vrouw, troon, kroon, parels, scepter, venussymbool, '
               'stroom, boom, koren')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'IV'),
              ('naam', 'De Keizer'),
              ('opmerking', ''),
              ('kernwoord', 'MACHT'),
              ('steekwoord',
               'Autoriteit, besturen, verantwoordelijkheid, zelfhandhaving, '
               'bescherming'),
              ('advies', 'Neem zelf het heft in handen.'),
              ('waarschuwing', 'On- of over-verantwoordelijkheid.'),
              ('symbolen',
               'volwassen man, stroom, berg, troon, kroon, rijksappel, rood '
               'kleed,harnas')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'V'),
              ('naam', 'De Hogepriester'),
              ('opmerking', 'De Hiërofant'),
              ('kernwoord', 'OVERTUIGING'),
              ('steekwoord',
               'Staan voor je mening, verkondigen, expertise, inspiratie'),
              ('advies', 'Kom naar buiten met wat jij vindt.'),
              ('waarschuwing', 'Je luistert slecht naar anderen.'),
              ('symbolen',
               'zegening, pilaren, kruis, kroon, adept, rood kleed, sleutel')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'VI'),
              ('naam', 'De Geliefden'),
              ('opmerking', ''),
              ('kernwoord', 'KIEZEN'),
              ('steekwoord',
               'Dualiteit mannelijk - vrouwelijk; (sexuele) '
               'aantrekkingskracht, bewust van tegenstellingen.'),
              ('advies', 'Probeer dit met liefde te overwinnen.'),
              ('waarschuwing', 'Je houdt teveel rekening met anderen.'),
              ('symbolen',
               'naaktheid, engel, zegening, appelboom, slang, wolken, bergtop, '
               'zon')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'VII'),
              ('naam', 'De Zegewagen'),
              ('opmerking', ''),
              ('kernwoord', 'STUREN'),
              ('steekwoord',
               'Wilskracht, zelfdiscipline, controle, tot stand brengen.'),
              ('advies', 'Bepaal je koers en hou die vast.'),
              ('waarschuwing', 'Teugels te strak of zwalkend.'),
              ('symbolen',
               'jonge man, kroon, lauwerkrans, ster (achtpuntig), vierkant, '
               'yoni, lingam, sfinx, stadsmuur, hermesvleugels')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'VIII'),
              ('naam', 'Gerechtigheid'),
              ('opmerking', 'Waite XI'),
              ('kernwoord', 'RECHTVAARDIGHEID'),
              ('steekwoord', 'Oorzaak en gevolg, schuld en boete.'),
              ('advies', 'Erken je eigen aandeel maar niet meer dan dat.'),
              ('waarschuwing',
               'Schuldgevoelens, onrechtvaardigheid, strengheid'),
              ('symbolen',
               'man, zwaard (verticaal), weegschaal, vierkant, troon, pilaren, '
               'paars kleed, rood kleed')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'IX'),
              ('naam', 'De Kluizenaar'),
              ('opmerking', 'De Heremiet'),
              ('kernwoord', 'ALLEEN'),
              ('steekwoord',
               'Je eigen weg gaan, op zoek zijn, dwalen, inkeer, onthechting, '
               'voorzichtigheid'),
              ('advies', 'Volg je eigen licht.'),
              ('waarschuwing', 'verdwaald, te eigengereid, eenzaam'),
              ('symbolen',
               'oude man, grijs, lantaarn, staf, ster (achtpuntig), rood '
               'kleed, groen kleed, afgewend, links, rechts')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'X'),
              ('naam', 'Het Rad van Fortuin'),
              ('opmerking', ''),
              ('kernwoord', 'LOT'),
              ('steekwoord', 'Aanvaarding, succes of falen.'),
              ('advies', 'Wie niet waagt die niet wint.'),
              ('waarschuwing', 'Je laat teveel aan het toeval over.'),
              ('symbolen',
               'engel, stier, leeuw, sfinx, slang, hermanubis, tora, feniks')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XI'),
              ('naam', 'Kracht'),
              ('opmerking', 'Waite VIII'),
              ('kernwoord', 'BEHEERSING'),
              ('steekwoord',
               'Met respekt omgaan met kracht en emoties, temmen'),
              ('advies', 'Een besliste maar zachte hand is nodig.'),
              ('waarschuwing', 'Die Leeuw mag best af en toe eens brullen.'),
              ('symbolen',
               'jonge vrouw, leeuw, bloemenkrans, lemniscaat, bergtop')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XII'),
              ('naam', 'De Gehangene'),
              ('opmerking', ''),
              ('kernwoord', 'PERSPECTIEF'),
              ('steekwoord',
               'Ergens aan vast zitten, consequenties aanvaarden, beproeving.'),
              ('advies', 'Vrije wil is blijmoedig doen wat je moet doen.'),
              ('waarschuwing', 'Je zit vast.'),
              ('symbolen',
               'volwassen man, ondersteboven, aureool, kruis, blauw, staf')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XIII'),
              ('naam', 'De Dood'),
              ('opmerking', ''),
              ('kernwoord', 'VERGANKELIJKHEID'),
              ('steekwoord', 'Het onvermijdelijke, afscheid, angst, verlies.'),
              ('advies', 'Wat moet dood zodat je verder kunt?'),
              ('waarschuwing', 'Angst is een slechte raadgever.'),
              ('symbolen',
               'wit, vaandel, wolken, toren, zon, koning, bisschop, jonge '
               'vrouw, kind, boot, man, stroom, paard, afgewend')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XIV'),
              ('naam', 'Matigheid'),
              ('opmerking', ''),
              ('kernwoord', 'BALANS'),
              ('steekwoord',
               'Afwegen, evenwicht verstand en gevoel. Integratie, zuinigheid'),
              ('advies', 'In harmonie komen met jezelf.'),
              ('waarschuwing', 'Overmaat schaadt,  ondermaat ook.'),
              ('symbolen',
               'engel, natuur, iris, kelken, pad, driehoek, water, berg, '
               'vierkant')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XV'),
              ('naam', 'De Duivel'),
              ('opmerking', ''),
              ('kernwoord', 'VERLEIDING'),
              ('steekwoord',
               'Obsessie, de Schaduw, sexualiteit, zwart-wit denken, '
               'fanatisme'),
              ('advies', 'Doorzie de verleiding / angst.'),
              ('waarschuwing', 'Slaaf zijn van je verlangens.'),
              ('symbolen',
               'geit, vleermuisvleugels, vogelpoten, borsten, troon, zegening, '
               'vierkant, toorts, naaktheid, ketens, pentagram')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XVI'),
              ('naam', 'De Toren'),
              ('opmerking', ''),
              ('kernwoord', 'RAMPSPOED'),
              ('steekwoord',
               'Onvoorziene verandering, crisis, vertwijfeling, loslaten van '
               'zekerheid, noodlot'),
              ('advies', 'Hou het geloof in jezelf vast.'),
              ('waarschuwing', 'Wachten tot de bom barst.'),
              ('symbolen',
               'toren, vuur, bergtop, wolken, bliksem, kroon, druppel')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XVII'),
              ('naam', 'De Ster'),
              ('opmerking', ''),
              ('kernwoord', 'HOOP'),
              ('steekwoord', 'Geloof, een nieuwe richting. Spiritualiteit.'),
              ('advies', 'Vertrouw op het bestaan.'),
              ('waarschuwing', 'Valse hoop, misplaatst vertrouwen.'),
              ('symbolen',
               'ster (achtpuntig), naaktheid, jonge vrouw, kelken, heuvels, '
               'boom met vogel, water')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XVIII'),
              ('naam', 'De Maan'),
              ('opmerking', ''),
              ('kernwoord', 'SCHEMER'),
              ('steekwoord',
               'Verlangens, droom en daad, behoefte aan bescherming,uit je '
               'schulp kruipen, dwaling'),
              ('advies', 'Bevrijding van beperkende conditioneringen.'),
              ('waarschuwing',
               'Kwetsbaarheid, gebondenheid. Angst voor verraad.'),
              ('symbolen',
               'maan, pad, hond + wolf, hond, water, kreeft, druppel, toren, '
               'pilaren')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XIX'),
              ('naam', 'De Zon'),
              ('opmerking', ''),
              ('kernwoord', 'SUCCES'),
              ('steekwoord',
               'Creativiteit, speelsheid, levenslust, zelfvertrouwen. Je hart, '
               'je kern.'),
              ('advies', 'Plezier en ongedwongen jezelf zijn.'),
              ('waarschuwing', 'Het speelkwartier is allang voorbij.'),
              ('symbolen',
               'kind, bloemenkrans, wit, rood kleed, zon, zonnebloem, '
               'golven')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XX'),
              ('naam', 'Het Oordeel'),
              ('opmerking', ''),
              ('kernwoord', 'OPSTANDING'),
              ('steekwoord',
               'Transformatie, het laatste oordeel, verrijzenis.'),
              ('advies', 'Laat het verleden los.'),
              ('waarschuwing', 'Schuldgevoelens en zelfkritiek.'),
              ('symbolen',
               'engel, wolken, trompet, volwassen man, volwassen vrouw, kind, '
               'grijs, naaktheid, berg')]),
 OrderedDict([('serie', 'groot'),
              ('nummer', 'XXI'),
              ('naam', 'De Wereld'),
              ('opmerking', ''),
              ('kernwoord', 'LEVEN'),
              ('steekwoord',
               'Het leven aangaan zonder jezelf er in te verliezen.'),
              ('advies', 'Ga voluit voor wat je wilt bereiken.'),
              ('waarschuwing', 'Het is tijd voor bezinning.'),
              ('symbolen',
               'jonge vrouw, staven, lauwerkrans, leeuw, stier, arend, '
               'engel')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', ''),
              ('naam', 'Aas'),
              ('opmerking', ''),
              ('kernwoord', 'DROMEN'),
              ('steekwoord', 'visie, enthousiasme, vitaliteit.'),
              ('advies', 'Bezieling.'),
              ('waarschuwing', 'Overmoed.'),
              ('symbolen', 'wolken, stroom, heuvels, burcht, hand, rechts')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', '2'),
              ('naam', 'II'),
              ('opmerking', ''),
              ('kernwoord', 'OVERWEGEN'),
              ('steekwoord', 'pionieren, opties afwegen'),
              ('advies', 'Alle begin is moeilijk.'),
              ('waarschuwing', 'Vernieuwing is nog geen verbetering.'),
              ('symbolen',
               'links, water, muur, globe, roos, lelie, berg, rood kleed')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', '3'),
              ('naam', 'III'),
              ('opmerking', ''),
              ('kernwoord', 'AFWACHTEN'),
              ('steekwoord', 'vooruitzien, handel, ontdekkingsreizen'),
              ('advies', 'Formuleer een helder doel.'),
              ('waarschuwing', 'Je kunt nu niet meer terug.'),
              ('symbolen',
               'rechts, rood kleed, groen kleed, boot, water, heuvels')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', '4'),
              ('naam', 'IV'),
              ('opmerking', ''),
              ('kernwoord', 'OOGST'),
              ('steekwoord',
               'oogst, resultaten vieren, harmonieuze samenwerking, '
               'terugkerende feesten'),
              ('advies', 'Je initiatief is vruchtbaar.'),
              ('waarschuwing', 'Op je lauweren rusten.'),
              ('symbolen',
               'kasteel, wit kleed, rood kleed, blauw kleed, bloemen')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', '5'),
              ('naam', 'V'),
              ('opmerking', ''),
              ('kernwoord', 'WEDIJVER'),
              ('steekwoord', 'schijngevecht, rellen'),
              ('advies', 'Strijd haalt het beste in je naar voren.'),
              ('waarschuwing', 'Blijven hangen in gekissebis.'),
              ('symbolen', '')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', '6'),
              ('naam', 'VI'),
              ('opmerking', ''),
              ('kernwoord', 'TRIOMF'),
              ('steekwoord',
               'zegevieren, mijlpaal, beginnend succes, waardering, groot '
               'nieuws'),
              ('advies', 'Je verwachtingen komen uit.'),
              ('waarschuwing', 'Te resultaatgericht.'),
              ('symbolen', 'groen kleed, lauwerkrans, paard')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', '7'),
              ('naam', 'VII'),
              ('opmerking', ''),
              ('kernwoord', 'HANDHAVEN'),
              ('steekwoord',
               'staande houden, vaak alleen, overmacht, gunstige positie'),
              ('advies', 'Neem het voor jezelf op.'),
              ('waarschuwing',
               'Vraag niet voortdurend goedkeuring. Doe het gewoon!'),
              ('symbolen', 'stroom, heuvels')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', '8'),
              ('naam', 'VIII'),
              ('opmerking', ''),
              ('kernwoord', 'OPGELIJND'),
              ('steekwoord',
               'veel energie, alles op één lijn, van een lijen dakje, haast'),
              ('advies', 'Energie kanaliseren'),
              ('waarschuwing', 'Teveel tegelijk.'),
              ('symbolen', 'stroom, heuvels, linksboven, rechtsonder')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', '9'),
              ('naam', 'IX'),
              ('opmerking', ''),
              ('kernwoord', 'BEDUCHT'),
              ('steekwoord',
               'op krachten komen, verzet, achterdocht, oponthoud, uitstel'),
              ('advies', 'De laatste loodjes: zet door'),
              ('waarschuwing', 'opgebrand: laat los'),
              ('symbolen', 'muur')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', '10'),
              ('naam', 'X'),
              ('opmerking', ''),
              ('kernwoord', 'VOLHOUDEN'),
              ('steekwoord', 'afmaken, heroverwegen, onderdrukking'),
              ('advies', 'Consolideer'),
              ('waarschuwing', 'Je verdeelt je krachten verkeerd'),
              ('symbolen', 'stadsmuur')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', ''),
              ('naam', 'Page'),
              ('opmerking', ''),
              ('kernwoord', 'INSPIRATIE'),
              ('steekwoord', 'op ideeën komen.'),
              ('advies', 'Oriënteer je op mogelijkheden.'),
              ('waarschuwing', 'Tunnelvisie.'),
              ('symbolen', 'heuvels, pyramide, rood kleed')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', ''),
              ('naam', 'Ridder'),
              ('opmerking', ''),
              ('kernwoord', 'BESTORMEN'),
              ('steekwoord', 'idealen koesteren, overtuigingskracht.'),
              ('advies', 'Verruim je horizon.'),
              ('waarschuwing', 'Te idealistisch.'),
              ('symbolen',
               'salamander, geel, oranje, paard, harnas, vuur, pyramide')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', ''),
              ('naam', 'Koningin'),
              ('opmerking', ''),
              ('kernwoord', 'IDENTITEIT'),
              ('steekwoord',
               'je eigen belevings- en verbeeldingswereld, onafhankelijk, '
               'kundig, zelfvertrouwen'),
              ('advies', 'Geloof in jezelf.'),
              ('waarschuwing', 'Te eigengereid.'),
              ('symbolen',
               'geel kleed, grijs kleed, troon, leeuw, zonnebloem, kroon, '
               'bloemenkrans, zwarte kat')]),
 OrderedDict([('serie', 'Staven'),
              ('nummer', ''),
              ('naam', 'Koning'),
              ('opmerking', ''),
              ('kernwoord', 'GEDREVEN'),
              ('steekwoord',
               'creativiteit, inspirerend, charmant, geestig, rechtvaardig, '
               'gedisciplineerd'),
              ('advies', 'Hoe zou jij het aanpakken?'),
              ('waarschuwing', 'ongeduld.'),
              ('symbolen',
               'salamander, geel, rood kleed, groen kleed, troon, kroon, '
               'ourobouros, afgewend')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', ''),
              ('naam', 'Aas'),
              ('opmerking', ''),
              ('kernwoord', 'POTENTIE'),
              ('steekwoord', 'kunde, tot stand brengen, realisme, waarde.'),
              ('advies', 'Lever een constructieve bijdrage.'),
              ('waarschuwing', 'Perfectionisme.'),
              ('symbolen',
               'hand, wolken, boog, bloemen, links, roos, lelie, pad, '
               'bergtop')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', '2'),
              ('naam', 'II'),
              ('opmerking', ''),
              ('kernwoord', 'JONGLEREN'),
              ('steekwoord',
               'evenwicht zoeken/houden, uitgekiende inzet van middelen, '
               'oefenen, schijnplezier'),
              ('advies', 'Trek de zaak weer vlot.'),
              ('waarschuwing', 'Het ene gat met het andere stoppen.'),
              ('symbolen', 'lemniscaat, water, boot, jonge man')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', '3'),
              ('naam', 'III'),
              ('opmerking', ''),
              ('kernwoord', 'PROEF'),
              ('steekwoord', 'waardering, vakmanschap, uitvoering, inzet'),
              ('advies', 'Voer je plan uit.'),
              ('waarschuwing', 'Gevoelig voor kritiek.'),
              ('symbolen', 'monnik, hamer')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', '4'),
              ('naam', 'IV'),
              ('opmerking', ''),
              ('kernwoord', 'VASTHOUDEN'),
              ('steekwoord',
               'houden wat je hebt, energiestroom blokkeren, hebzucht'),
              ('advies', 'Wees zuinig op je mogelijkheden.'),
              ('waarschuwing', 'Materialisme.'),
              ('symbolen', 'toren')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', '5'),
              ('naam', 'V'),
              ('opmerking', ''),
              ('kernwoord', 'ARMOEDE'),
              ('steekwoord',
               '(angst voor) ontbering, gebrek, kou, angst voor de toekoms'),
              ('advies', 'Wat heb je echt nodig?'),
              ('waarschuwing', 'Jezelf onderwaarderen.'),
              ('symbolen', 'bel')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', '6'),
              ('naam', 'VI'),
              ('opmerking', ''),
              ('kernwoord', 'BEDELEN'),
              ('steekwoord',
               'Delen = vermenigvuldigen, arm vs rijk, zaaien, Bedelen vs '
               'beDElen'),
              ('advies', 'Geven en nemen.'),
              ('waarschuwing', 'Wrok over onrecht / te kort komen.'),
              ('symbolen',
               'rood kleed, zegening, boom, burcht, weegschaal, geel kleed, '
               'blauw kleed')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', '7'),
              ('naam', 'VII'),
              ('opmerking', ''),
              ('kernwoord', 'GEDULD'),
              ('steekwoord', 'afwachten, beheren'),
              ('advies', 'Kijk het nog even aan. Zie je voortgang.'),
              ('waarschuwing', 'Toekijken, er buiten staan.'),
              ('symbolen', '')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', '8'),
              ('naam', 'VIII'),
              ('opmerking', ''),
              ('kernwoord', 'ROUTINE'),
              ('steekwoord', 'oefenen, nederig werk, ambachten, kundigheid'),
              ('advies', 'Verbeter je effectiviteit.'),
              ('waarschuwing', 'Sleur, geen plezier in je werk.'),
              ('symbolen', 'hamer')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', '9'),
              ('naam', 'IX'),
              ('opmerking', ''),
              ('kernwoord', 'VERVULLING'),
              ('steekwoord', 'genieten, verfraaien, zekerheid'),
              ('advies', 'Geniet van wat je doet.'),
              ('waarschuwing', 'Gericht op uiterlijkheden.'),
              ('symbolen',
               'druiven, kasteel, geel kleed, valk, wijnhuisslak')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', '10'),
              ('naam', 'X'),
              ('opmerking', ''),
              ('kernwoord', 'WELSTAND'),
              ('steekwoord',
               'traditie, iets opbouwen, zekerheid, welvaart, familiezaken'),
              ('advies', 'Draag bij aan het grotere geheel.'),
              ('waarschuwing', 'Gefixeerd op zekerheid.'),
              ('symbolen',
               'druiven, hond, burcht, toren, poort, weegschaal, oude man')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', ''),
              ('naam', 'Page'),
              ('opmerking', ''),
              ('kernwoord', 'LEREN'),
              ('steekwoord', 'behulpzaam, precies, kritisch, student, ijverig'),
              ('advies', 'Hoe kun je jezelf nuttig maken?'),
              ('waarschuwing', 'detaillistisch, vluchtige belangstelling'),
              ('symbolen', 'natuur, heuvels, bloemen, groen kleed')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', ''),
              ('naam', 'Ridder'),
              ('opmerking', ''),
              ('kernwoord', 'MANAGER'),
              ('steekwoord',
               'organisatievermogen, degelijk, plichtgetrouw, praktisch'),
              ('advies', 'Richt je op het haalbare.'),
              ('waarschuwing', 'Veeleisend.'),
              ('symbolen', 'paard, harnas, rood kleed, afgewend')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', ''),
              ('naam', 'Koningin'),
              ('opmerking', ''),
              ('kernwoord', 'ZORGVULDIG BEHEREN'),
              ('steekwoord', 'innerlijke zekerheid, zelfwaardering, royaal'),
              ('advies', 'Rust en geleidelijkheid.'),
              ('waarschuwing', 'Behoudzucht.'),
              ('symbolen',
               'natuur, troon, kroon, bloemen, berg, cupido, geit, haas, '
               'afgewend')]),
 OrderedDict([('serie', 'Pentakels'),
              ('nummer', ''),
              ('naam', 'Koning'),
              ('opmerking', ''),
              ('kernwoord', 'ONDERNEMER'),
              ('steekwoord',
               'standvastigheid, autoriteit, realiserende intelligentie, '
               'zakelijk'),
              ('advies', 'Realisme.'),
              ('waarschuwing', 'Rechtlijnig, onbuigzaam.'),
              ('symbolen',
               'stier, druiven, troon, kroon, harnas, groen kleed')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', ''),
              ('naam', 'Aas'),
              ('opmerking', ''),
              ('kernwoord', 'VISIE'),
              ('steekwoord', 'helderheid van geest, objectiviteit'),
              ('advies', 'Een verstandelijke benadering.'),
              ('waarschuwing', 'In je hoofd zitten.'),
              ('symbolen',
               'wolken, hand, kroon, robijn, olijfblad, palmtak, zwaard '
               '(verticaal)')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', '2'),
              ('naam', 'II'),
              ('opmerking', ''),
              ('kernwoord', 'DILEMMA'),
              ('steekwoord',
               'relativeren, twee kanten van de medaille zien, twijfel'),
              ('advies', 'Analyseer voor en tegen.'),
              ('waarschuwing', 'Twijfelen.'),
              ('symbolen',
               'wit kleed, water, heuvels, kubus, blinddoek, maan')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', '3'),
              ('naam', 'III'),
              ('opmerking', ''),
              ('kernwoord', 'VERDRIET'),
              ('steekwoord', 'en die kan zeer doen.'),
              ('advies', 'Wind er geen doekjes om.'),
              ('waarschuwing', 'Onredelijkheid.'),
              ('symbolen', 'hartvorm, wolken, grijs')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', '4'),
              ('naam', 'IV'),
              ('opmerking', ''),
              ('kernwoord', 'BEZINNING'),
              ('steekwoord',
               'overwegen, bezinnen, rusten, herstellen, retraite, testament'),
              ('advies', 'Slaap er een nachtje over.'),
              ('waarschuwing', 'Besluiteloosheid.'),
              ('symbolen', 'grijs, ridder')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', '5'),
              ('naam', 'V'),
              ('opmerking', ''),
              ('kernwoord', 'AFGUNST'),
              ('steekwoord',
               'debatteren, negatieve gedachtepatronen, verraad, degradatie, '
               'oneer'),
              ('advies', 'Wapen je met argumenten.'),
              ('waarschuwing', 'Altijd gelijk willen hebben.'),
              ('symbolen', 'afgewend')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', '6'),
              ('naam', 'VI'),
              ('opmerking', ''),
              ('kernwoord', 'VLUCHT'),
              ('steekwoord', 'je terug trekken'),
              ('advies', 'Deze zaak is niet met argumenten te winnen.'),
              ('waarschuwing', 'Is het gras echt groener?'),
              ('symbolen', 'water, golven')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', '7'),
              ('naam', 'VII'),
              ('opmerking', ''),
              ('kernwoord', 'LIST'),
              ('steekwoord', 'slimheid, spitsvondigheid, oneerlijkheid'),
              ('advies', 'Verzin een list.'),
              ('waarschuwing', 'Je wordt in de maling genomen.'),
              ('symbolen', '')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', '8'),
              ('naam', 'VIII'),
              ('opmerking', ''),
              ('kernwoord', 'GEVANGEN'),
              ('steekwoord',
               'negatieve gedachtenpatronen, censuur, ziekte, schaamte, '
               'verdenking'),
              ('advies', 'Je redenering klopt niet.'),
              ('waarschuwing', 'Cirkelredeneringen.'),
              ('symbolen', 'blinddoek, burcht, water, berg')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', '9'),
              ('naam', 'IX'),
              ('opmerking', ''),
              ('kernwoord', 'ONTWAKEN'),
              ('steekwoord', 'dagend inzicht, zelfverwijt, vertwijfeling'),
              ('advies', 'Laat dit eerst bezinken.'),
              ('waarschuwing', 'Verwarring.'),
              ('symbolen', 'afgewend, roos, wit kleed, oosten, vrouw')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', '10'),
              ('naam', 'X'),
              ('opmerking', ''),
              ('kernwoord', 'EINDE'),
              ('steekwoord', 'destructieve gedachten, voortijdig einde'),
              ('advies', 'Een overtuiging volkomen loslaten.'),
              ('waarschuwing', 'Faalangst.'),
              ('symbolen', 'water, zon, heuvels, rood kleed, zegening')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', ''),
              ('naam', 'Page'),
              ('opmerking', ''),
              ('kernwoord', 'WAAKZAAM'),
              ('steekwoord', 'verstand van zaken, opmerkzaam, escalatie'),
              ('advies', 'Stel jezelf op de hoogte.'),
              ('waarschuwing', 'Betweterigheid.'),
              ('symbolen', 'wolken, heuvels, vogel')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', ''),
              ('naam', 'Ridder'),
              ('opmerking', ''),
              ('kernwoord', 'DURF'),
              ('steekwoord',
               'onverwachte doorbraak, confrontatie, bekwaamheid, dapperheid'),
              ('advies', 'Staan voor je overtuiging.'),
              ('waarschuwing', 'Te theoretisch.'),
              ('symbolen', 'oranje, rood kleed, paard, harnas, vogel')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', ''),
              ('naam', 'Koningin'),
              ('opmerking', ''),
              ('kernwoord', 'WIJSHEID'),
              ('steekwoord',
               'innerlijke overtuiging, eerlijkheid, levenswijsheid, '
               'heldere/rustige geest, deugdzaam, streng'),
              ('advies', 'Rechtvaardigheid.'),
              ('waarschuwing', 'Rechtlijnigheid.'),
              ('symbolen',
               'afgewend, wolken, troon, kroon, wit kleed, volwassen vrouw, '
               'zwaard (verticaal)')]),
 OrderedDict([('serie', 'Zwaarden'),
              ('nummer', ''),
              ('naam', 'Koning'),
              ('opmerking', ''),
              ('kernwoord', 'DENKER'),
              ('steekwoord',
               'De gedachte gaat aan de manifestatie vooraf, handhaver, '
               'rationeel, skeptisch, hard, dominant'),
              ('advies', 'Vel een oordeel.'),
              ('waarschuwing', 'Te rationeel. Wreed'),
              ('symbolen',
               'troon, kroon, blauw kleed, paars kleed, wolken, heuvels, boom, '
               'zwaard (verticaal)')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', ''),
              ('naam', 'Aas'),
              ('opmerking', ''),
              ('kernwoord', 'BEZIELING'),
              ('steekwoord',
               'verlangen naar eenheid en verbondenheid, overgave, '
               'bewustwording, de bron, de Graal.'),
              ('advies', 'Laat je gevoel stromen.'),
              ('waarschuwing', 'Over-emotioneel.'),
              ('symbolen',
               'rechts, hand, wolken, water, duif, yod, lelie, hostie')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', '2'),
              ('naam', 'II'),
              ('opmerking', ''),
              ('kernwoord', 'GELOFTES'),
              ('steekwoord',
               'verlangen naar een partner (eventueel platonisch), gevoel vs '
               'verstand, valse liefde'),
              ('advies', 'Samenwerking, verbondenheid.'),
              ('waarschuwing', 'Gefixeerd op relatie.'),
              ('symbolen',
               'lauwerkrans, roos, slang, leeuw, heuvels, hermesvleugels')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', '3'),
              ('naam', 'III'),
              ('opmerking', ''),
              ('kernwoord', 'FEEST'),
              ('steekwoord', 'plezier hebben, blijheid, genezing, troost'),
              ('advies', 'Laat jezelf eens gaan.'),
              ('waarschuwing', 'Losbandigheid.'),
              ('symbolen',
               'druiven, bloemen, rood kleed, geel kleed, wit kleed')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', '4'),
              ('naam', 'IV'),
              ('opmerking', ''),
              ('kernwoord', 'MEDITATIE'),
              ('steekwoord', 'verlangen naar meer, lusteloosheid'),
              ('advies', 'Het is tijd voor verandering.'),
              ('waarschuwing', 'Onvervuld.'),
              ('symbolen', 'hand, wolken, boom, links')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', '5'),
              ('naam', 'V'),
              ('opmerking', ''),
              ('kernwoord', 'DESILLUSIE'),
              ('steekwoord', 'teleurstelling, verlies'),
              ('advies', 'Wat blijft er over?'),
              ('waarschuwing', 'Blijven hangen in verdriet.'),
              ('symbolen',
               'grijs, water, brug, burcht, afgewend, zwart kleed, bloed, '
               'groen')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', '6'),
              ('naam', 'VI'),
              ('opmerking', ''),
              ('kernwoord', 'NOSTALGIE'),
              ('steekwoord',
               'verbinden, delen vanuit overvloed, vreugde schenken'),
              ('advies', 'Verheug je in kleine dingen.'),
              ('waarschuwing', 'verloren onschuld, zinloze nostalgie'),
              ('symbolen', 'dwaas, vrouw, lelie, burcht')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', '7'),
              ('naam', 'VII'),
              ('opmerking', ''),
              ('kernwoord', 'ILLUSIES'),
              ('steekwoord',
               'visioenen, misleiding, mystery guest, verbeelding, '
               'vergankelijke weelde'),
              ('advies', 'Wat heb je werkelijk nodig?'),
              ('waarschuwing', 'Klatergoud.'),
              ('symbolen',
               'slang, lauwerkrans, draak, edelstenen, burcht, engel, wolken, '
               'afgewend, doodshoofd')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', '8'),
              ('naam', 'VIII'),
              ('opmerking', ''),
              ('kernwoord', 'NIEUW PAD'),
              ('steekwoord', 'illusies achter je laten, het roer om'),
              ('advies', 'Laat het verleden los.'),
              ('waarschuwing', 'Een nieuwe illusie najagen.'),
              ('symbolen', 'maan, water, berg, rood kleed')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', '9'),
              ('naam', 'IX'),
              ('opmerking', ''),
              ('kernwoord', 'VOLDAAN'),
              ('steekwoord',
               'evenwichtigheid, dromen zijn werkelijkheid geworden, innerlijk '
               'geluk'),
              ('advies', 'Bewaar je gemoedsrust.'),
              ('waarschuwing', 'Luiheid en arrogantie'),
              ('symbolen', 'blauw kleed,')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', '10'),
              ('naam', 'X'),
              ('opmerking', ''),
              ('kernwoord', 'GELUK'),
              ('steekwoord',
               'welzijn, voltooiing, samen (gezin/dorp/gemeente)'),
              ('advies', 'Definieer wat je gelukkig zou maken.'),
              ('waarschuwing', 'Ophemelen.'),
              ('symbolen', 'regenboog, water, gezin, huis, afgewend')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', ''),
              ('naam', 'Page'),
              ('opmerking', ''),
              ('kernwoord', 'VERWONDERING'),
              ('steekwoord',
               'fantasie, verbeelding, puberteit, vlijtige jeugd'),
              ('advies', 'Ontwikkel je creativiteit.'),
              ('waarschuwing', 'Goedgelovigheid.'),
              ('symbolen', 'lotus, vis, golven')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', ''),
              ('naam', 'Ridder'),
              ('opmerking', ''),
              ('kernwoord', 'ZOEKTOCHT'),
              ('steekwoord',
               'aanvoelen, betrokkenheid, waarheidsvinding, voorstel'),
              ('advies', 'Zorg voor een goede verstandhouding.'),
              ('waarschuwing', 'Overbezorgheid.'),
              ('symbolen',
               'hermesvleugels, harnas, paard, water, heuvels, vis, '
               'afgewend')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', ''),
              ('naam', 'Koningin'),
              ('opmerking', ''),
              ('kernwoord', 'OBSERVEREN'),
              ('steekwoord',
               'inlevingsvermogen, innerlijk weten, visioenen/dromerig, '
               'gedistingeerd'),
              ('advies', 'Erover praten kan je beeld verhelderen.'),
              ('waarschuwing', 'Navelstaarderij.'),
              ('symbolen', 'water, troon, kroon, wit kleed, afgewend')]),
 OrderedDict([('serie', 'Kelken'),
              ('nummer', ''),
              ('naam', 'Koning'),
              ('opmerking', ''),
              ('kernwoord', 'INTEGRITEIT'),
              ('steekwoord',
               'bewustwording, verdraagzaamheid, gevoelig man, onderhandelaar, '
               'brede belangstelling, wetsman, wetenschapper'),
              ('advies', 'Een rots in de branding.'),
              ('waarschuwing', 'Onderdrukte gevoelens'),
              ('symbolen',
               'golven, vis, boot, kroon, troon, scepter, geel kleed, blauw '
               'kleed')])]

symbols = [OrderedDict([('naam', 'Grote Arcana 1-10'),
              ('zie', ''),
              ('betekenis',
               'verwerven van eigenschappen en innerlijke kwaliteiten')]),
 OrderedDict([('naam', 'Grote Arcana 11-20'),
              ('zie', ''),
              ('betekenis',
               'leren omgaan met de ervaringen die het leven brengt')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'nummerkaart'),
              ('zie', ''),
              ('betekenis', 'dingen die je zelf in de hand hebt')]),
 OrderedDict([('naam', 'hofkaart'),
              ('zie', ''),
              ('betekenis', 'invloeden (van/naar je omgeving)')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'Staven'),
              ('zie', ''),
              ('betekenis',
               'geest, intuïtie/ideeën, vuur, boeren/werkende klasse')]),
 OrderedDict([('naam', 'Pentakels'),
              ('zie', ''),
              ('betekenis',
               'thuis, zintuigen, aarde/praktisch, burgers/handelaars')]),
 OrderedDict([('naam', 'Zwaarden'),
              ('zie', ''),
              ('betekenis', 'verstand, denken, lucht, adel/militairen')]),
 OrderedDict([('naam', 'Kelken'),
              ('zie', ''),
              ('betekenis',
               'hart, emotie, water, geestelijkheid/staatslieden')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'staf'), ('zie', 'staven'), ('betekenis', '')]),
 OrderedDict([('naam', 'Pentakel'), ('zie', 'pentakels'), ('betekenis', '')]),
 OrderedDict([('naam', 'zwaard'), ('zie', 'zwaarden'), ('betekenis', '')]),
 OrderedDict([('naam', 'Kelk'), ('zie', 'kelken'), ('betekenis', '')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'klavers'), ('zie', 'staven'), ('betekenis', '')]),
 OrderedDict([('naam', 'ruiten'), ('zie', 'pentakels'), ('betekenis', '')]),
 OrderedDict([('naam', 'schoppen'), ('zie', 'zwaarden'), ('betekenis', '')]),
 OrderedDict([('naam', 'harten'), ('zie', 'kelken'), ('betekenis', '')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'O'),
              ('zie', ''),
              ('betekenis', 'leegte, alomvattendheid')]),
 OrderedDict([('naam', 'I'),
              ('zie', ''),
              ('betekenis', 'eenheid, begin, potentie, oorsprong')]),
 OrderedDict([('naam', 'II'),
              ('zie', ''),
              ('betekenis', 'tweestrijd, vergelijking, dualiteit')]),
 OrderedDict([('naam', 'III'),
              ('zie', 'Drie-eenheid'),
              ('betekenis',
               'harmonie, gemak, groei, vruchtbaarheid, leerling')]),
 OrderedDict([('naam', 'IV'),
              ('zie', 'elementen'),
              ('betekenis', 'ordening, volmaaktheid')]),
 OrderedDict([('naam', 'V'),
              ('zie', 'zintuigen'),
              ('betekenis',
               'doorzetten, problemen oplossen, beweging, moraal, gezel')]),
 OrderedDict([('naam', 'VI'),
              ('zie', ''),
              ('betekenis', 'verantwoordelijkheid, dienstvaardigheid')]),
 OrderedDict([('naam', 'VII'),
              ('zie', ''),
              ('betekenis', 'Succesvol toepassen, de meester')]),
 OrderedDict([('naam', 'VIII'),
              ('zie', ''),
              ('betekenis', 'crisis, gevaar, karma')]),
 OrderedDict([('naam', 'IX'),
              ('zie', ''),
              ('betekenis', 'vervulling, perspectief, de bouwmeester')]),
 OrderedDict([('naam', 'X'),
              ('zie', ''),
              ('betekenis', 'overgang, einde=begin')]),
 OrderedDict([('naam', 'XI'),
              ('zie', ''),
              ('betekenis', 'openbaring, inspiratie')]),
 OrderedDict([('naam', 'XII'),
              ('zie', ''),
              ('betekenis', 'volledigheid, perfectie, deelbaarheid')]),
 OrderedDict([('naam', 'XXII'), ('zie', ''), ('betekenis', 'de bouwmeester')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'aas'), ('zie', 'I'), ('betekenis', '')]),
 OrderedDict([('naam', 'page'),
              ('zie', 'jonge man'),
              ('betekenis', 'boodschapper, nieuwsgierig, kans')]),
 OrderedDict([('naam', 'ridder'),
              ('zie', ''),
              ('betekenis', 'strijder, werker, beschermen van zwakkeren ')]),
 OrderedDict([('naam', 'koningin'),
              ('zie', 'volwassen vrouw'),
              ('betekenis', 'wijsheid, volwassenheid')]),
 OrderedDict([('naam', 'koning'),
              ('zie', 'volwassen man'),
              ('betekenis', 'gezag, competentie')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'aarde'), ('zie', ''), ('betekenis', 'vruchtbaarheid')]),
 OrderedDict([('naam', 'adept'), ('zie', 'monnik'), ('betekenis', '')]),
 OrderedDict([('naam', 'afgewend'),
              ('zie', ''),
              ('betekenis', 'terugblikken')]),
 OrderedDict([('naam', 'altaar'), ('zie', ''), ('betekenis', 'religie')]),
 OrderedDict([('naam', 'ankh'),
              ('zie', 'scepter'),
              ('betekenis', 'eeuwig leven')]),
 OrderedDict([('naam', 'ankh'), ('zie', 'jakhalsgod'), ('betekenis', '')]),
 OrderedDict([('naam', 'appelboom'),
              ('zie', ''),
              ('betekenis',
               'boom van kennis (van goed en kwaad), bewustzijn')]),
 OrderedDict([('naam', 'arend'),
              ('zie', 'water, feniks'),
              ('betekenis', 'god ziet de mens')]),
 OrderedDict([('naam', 'aureool'),
              ('zie', ''),
              ('betekenis', 'diepe trance, verandering in bewustzijn')]),
 OrderedDict([('naam', 'baldakijn'), ('zie', 'troonhemel'), ('betekenis', '')]),
 OrderedDict([('naam', 'bel'),
              ('zie', ''),
              ('betekenis', 'melaatsheid, ziekte')]),
 OrderedDict([('naam', 'berg'),
              ('zie', ''),
              ('betekenis', 'standvastigheid, aarde, mystieke reis')]),
 OrderedDict([('naam', 'bergtop'),
              ('zie', 'berg'),
              ('betekenis', 'plaats dicht bij god')]),
 OrderedDict([('naam', 'bisschop'),
              ('zie', 'geestelijke'),
              ('betekenis', 'uiterlijke religie')]),
 OrderedDict([('naam', 'blaadjes'), ('zie', 'yod'), ('betekenis', '')]),
 OrderedDict([('naam', 'blauw'),
              ('zie', ''),
              ('betekenis',
               'rust, vrede, intelligentie, stabiliteit, loyaal, '
               'conservatief')]),
 OrderedDict([('naam', 'blauw kleed'), ('zie', 'blauw'), ('betekenis', '')]),
 OrderedDict([('naam', 'bliksem'),
              ('zie', ''),
              ('betekenis', 'goddelijke communicatie, vernietiging')]),
 OrderedDict([('naam', 'blinddoek'),
              ('zie', ''),
              ('betekenis',
               'onwetendheid, verblinding, overgeleverd zijn aan het lot')]),
 OrderedDict([('naam', 'bloed'),
              ('zie', ''),
              ('betekenis', 'liefde, levenskracht')]),
 OrderedDict([('naam', 'bloemen'),
              ('zie', ''),
              ('betekenis',
               'natuurlijke levenskracht, levensvreugde, actief en viriel')]),
 OrderedDict([('naam', 'Bloemenkrans'), ('zie', 'bloemen'), ('betekenis', '')]),
 OrderedDict([('naam', 'Boaz'),
              ('zie', ''),
              ('betekenis', 'bevestigen, strengheid (intentie)')]),
 OrderedDict([('naam', 'boek'), ('zie', ''), ('betekenis', 'kennisbron')]),
 OrderedDict([('naam', 'boekrol'),
              ('zie', 'boek'),
              ('betekenis', 'intuïtieve bron')]),
 OrderedDict([('naam', 'boog'), ('zie', 'poort'), ('betekenis', '')]),
 OrderedDict([('naam', 'boom'), ('zie', ''), ('betekenis', 'levenskracht')]),
 OrderedDict([('naam', 'Boom met vogel'),
              ('zie', ''),
              ('betekenis', 'kennis, intelligentie, het goddelijke Woord')]),
 OrderedDict([('naam', 'boot'),
              ('zie', ''),
              ('betekenis', 'Verre reis (door de onderwereld?)')]),
 OrderedDict([('naam', 'borsten'),
              ('zie', ''),
              ('betekenis',
               'verborgen vruchtbaarheid, de mogelijkheid te creeëren en te '
               'vermenigvuldigen zonder de ander/Ander, androgyne figuur')]),
 OrderedDict([('naam', 'brug'), ('zie', ''), ('betekenis', 'overgang')]),
 OrderedDict([('naam', 'burcht'),
              ('zie', ''),
              ('betekenis', 'bescherming, veilige thuishaven')]),
 OrderedDict([('naam', 'cupido'), ('zie', ''), ('betekenis', 'liefde')]),
 OrderedDict([('naam', 'davidsster'), ('zie', ''), ('betekenis', 'harmonie')]),
 OrderedDict([('naam', 'doodshoofd'),
              ('zie', ''),
              ('betekenis', 'de dood, sterfelijkheid')]),
 OrderedDict([('naam', 'draak'),
              ('zie', 'vuur, slang'),
              ('betekenis', 'tegenstander, schatbewaker, onsterfelijkheid')]),
 OrderedDict([('naam', 'drie-eenheid'),
              ('zie', ''),
              ('betekenis',
               'geest/ziel/lichaam, vader/zoon/heilige geest, '
               'hemel/aarde/hel')]),
 OrderedDict([('naam', 'driehoek'),
              ('zie', 'Drie-eenheid, vuur'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'druiven'),
              ('zie', ''),
              ('betekenis', 'overvloed, rijke oogst')]),
 OrderedDict([('naam', 'druppel'),
              ('zie', 'dauw, yod'),
              ('betekenis', 'genade, vrede, hoop')]),
 OrderedDict([('naam', 'duif'),
              ('zie', ''),
              ('betekenis', 'brenger van vrede, heilige geest')]),
 OrderedDict([('naam', 'dwaas'), ('zie', 'de dwaas'), ('betekenis', '')]),
 OrderedDict([('naam', 'edelstenen'),
              ('zie', ''),
              ('betekenis', 'hebzucht, materialisme')]),
 OrderedDict([('naam', 'elementen'),
              ('zie', 'water, vuur, lucht, aarde'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'engel'),
              ('zie', 'lucht'),
              ('betekenis', 'boodschapper van god, oorsprong van de mens')]),
 OrderedDict([('naam', 'feniks'),
              ('zie', ''),
              ('betekenis',
               'verjonging (door drievoudige onderdompeling in water)')]),
 OrderedDict([('naam', 'geel'),
              ('zie', ''),
              ('betekenis',
               '(zon) levenskracht en warmte, bevordert concentratie, '
               'geestelijke activiteit, nadenken, vrolijkheid, fantasie, '
               'jaloezie, lafheid, onrust')]),
 OrderedDict([('naam', 'geel kleed'), ('zie', 'geel'), ('betekenis', '')]),
 OrderedDict([('naam', 'geestelijke'),
              ('zie', 'hiërofant'),
              ('betekenis', 'toewijding, toetreding')]),
 OrderedDict([('naam', 'geit'),
              ('zie', ''),
              ('betekenis',
               'voedster, doorzettingsvermogen, seksueel plezier')]),
 OrderedDict([('naam', 'gezin'),
              ('zie', ''),
              ('betekenis', 'huiselijk geluk')]),
 OrderedDict([('naam', 'globe'),
              ('zie', ''),
              ('betekenis', 'de wereld ontdekken/veroveren')]),
 OrderedDict([('naam', 'golven'),
              ('zie', 'water'),
              ('betekenis', 'wisselende stemmingen, wisselend succes')]),
 OrderedDict([('naam', 'graan'), ('zie', 'koren'), ('betekenis', '')]),
 OrderedDict([('naam', 'granaatappel'),
              ('zie', ''),
              ('betekenis', 'mensen in groep')]),
 OrderedDict([('naam', 'grijs'),
              ('zie', 'zwart, wit'),
              ('betekenis',
               'harmonie (zwart en wit gemengd), rust en onopvallendheid, '
               'intelligentie en creativiteit')]),
 OrderedDict([('naam', 'grijs kleed'),
              ('zie', 'grijs'),
              ('betekenis', 'eenvoud, bewust leven')]),
 OrderedDict([('naam', 'groen'),
              ('zie', 'blauw, geel'),
              ('betekenis',
               'groei, ontwikkeling, harmonie, ontspanning, verveling, '
               'weerstand')]),
 OrderedDict([('naam', 'groen kleed'),
              ('zie', 'groen'),
              ('betekenis', 'afremmen, rusten, verlagen')]),
 OrderedDict([('naam', 'groene omgeving'),
              ('zie', 'natuur'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'haag'), ('zie', 'muur'), ('betekenis', '')]),
 OrderedDict([('naam', 'haas'),
              ('zie', ''),
              ('betekenis', 'vruchtbaarheid, opofferingsgezindheid, loyaal')]),
 OrderedDict([('naam', 'hamer'),
              ('zie', ''),
              ('betekenis', 'kracht, activiteit')]),
 OrderedDict([('naam', 'hand'), ('zie', ''), ('betekenis', 'hand van god')]),
 OrderedDict([('naam', 'harnas'),
              ('zie', ''),
              ('betekenis', 'mannelijkheid, beschermer')]),
 OrderedDict([('naam', 'hartvorm'),
              ('zie', ''),
              ('betekenis',
               'vrouw, aantrekkingskracht, emoties, het onbewuste')]),
 OrderedDict([('naam', 'hermanubis'),
              ('zie', 'jakhalsgod'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'hermes'),
              ('zie', ''),
              ('betekenis', 'boodschapper van de goden')]),
 OrderedDict([('naam', 'hermesvleugels'),
              ('zie', 'hermes'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'heuvels'),
              ('zie', ''),
              ('betekenis', 'initiatie, vruchtbaarheid')]),
 OrderedDict([('naam', 'hiërofant'),
              ('zie', 'hogepriester'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'Hond'),
              ('zie', ''),
              ('betekenis',
               'trouw, waakzaam, getemd, kent de weg, ongebreidelde lust')]),
 OrderedDict([('naam', 'Hond + wolf'),
              ('zie', ''),
              ('betekenis', 'getemde en ongetemde energiën (in de mens)')]),
 OrderedDict([('naam', 'hostie'), ('zie', ''), ('betekenis', 'offer')]),
 OrderedDict([('naam', 'huis'),
              ('zie', 'gezin'),
              ('betekenis', 'geborgenheid, thuis')]),
 OrderedDict([('naam', 'iris'), ('zie', ''), ('betekenis', 'boodschappers')]),
 OrderedDict([('naam', 'Jachin'),
              ('zie', ''),
              ('betekenis', 'kracht, mededogen (vorm)')]),
 OrderedDict([('naam', 'jakhalsgod'),
              ('zie', ''),
              ('betekenis',
               'voorbode van de dood, begeleider van zielen naar '
               'onderwereld')]),
 OrderedDict([('naam', 'jod'), ('zie', 'yod'), ('betekenis', '')]),
 OrderedDict([('naam', 'jonge man'), ('zie', 'man'), ('betekenis', '')]),
 OrderedDict([('naam', 'jonge vrouw'),
              ('zie', 'vrouw'),
              ('betekenis', 'maagd, (nog) niet seksueel actief')]),
 OrderedDict([('naam', 'kasteel'), ('zie', 'burcht'), ('betekenis', '')]),
 OrderedDict([('naam', 'ketens'),
              ('zie', ''),
              ('betekenis', 'gebondenheid, verbondenheid')]),
 OrderedDict([('naam', 'kind'),
              ('zie', ''),
              ('betekenis',
               'goddelijke onschuld, het resultaat van de samensmelting tussen '
               'de mannelijke en vrouwelijke energie, einde van de dualiteit, '
               'vernieuwde eenheid')]),
 OrderedDict([('naam', 'koren'),
              ('zie', ''),
              ('betekenis',
               'rijke oogst, toegeweid moederschap, scheppende kracht')]),
 OrderedDict([('naam', 'kreeft'),
              ('zie', ''),
              ('betekenis',
               'de angsten en illusies willen zich manifesteren, '
               'rusteloosheid')]),
 OrderedDict([('naam', 'kringloop'),
              ('zie', ''),
              ('betekenis', 'circulair proces, eenheid van alles')]),
 OrderedDict([('naam', 'kroon'),
              ('zie', ''),
              ('betekenis', 'wereldse macht, talent, meesterschap')]),
 OrderedDict([('naam', 'kruis'), ('zie', ''), ('betekenis', 'religie')]),
 OrderedDict([('naam', 'kubus'), ('zie', ''), ('betekenis', 'het aardse')]),
 OrderedDict([('naam', 'kwik'), ('zie', ''), ('betekenis', 'geest')]),
 OrderedDict([('naam', 'lantaarn'), ('zie', ''), ('betekenis', 'wegwijzen')]),
 OrderedDict([('naam', 'lauwerkrans '),
              ('zie', ''),
              ('betekenis',
               'vergankelijke macht, zegeviering na (innerlijke) strijd')]),
 OrderedDict([('naam', 'leeuw'),
              ('zie', 'vuur'),
              ('betekenis',
               'moedige bewaker van grenzen, gevestigde macht, eenling, koning '
               'der dieren')]),
 OrderedDict([('naam', 'lelie'),
              ('zie', ''),
              ('betekenis',
               'hartverlangens, maagdelijkheid, reinheid, onschuld, goddelijke '
               'genade/gaven')]),
 OrderedDict([('naam', 'lemniscaat'),
              ('zie', ''),
              ('betekenis', 'oneindige verbondenheid')]),
 OrderedDict([('naam', 'lingam'),
              ('zie', ''),
              ('betekenis', 'fallussymbool (zie ook yoni)')]),
 OrderedDict([('naam', 'links'),
              ('zie', ''),
              ('betekenis', 'vrouwelijke kant, intuïtie, binnen, verleden')]),
 OrderedDict([('naam', 'linksboven'),
              ('zie', ''),
              ('betekenis', 'gedachtenwereld')]),
 OrderedDict([('naam', 'lotus'),
              ('zie', ''),
              ('betekenis',
               'spiritualiteit, kunst, inzicht, zelfvernieuwing')]),
 OrderedDict([('naam', 'lucht'),
              ('zie', ''),
              ('betekenis', 'denken, liefhebben')]),
 OrderedDict([('naam', 'maan'),
              ('zie', 'vrouw'),
              ('betekenis',
               'gids in donkere tijden (de maan reflecteert het licht van de '
               'zon), passiviteit')]),
 OrderedDict([('naam', 'man'),
              ('zie', ''),
              ('betekenis', 'zichtbare, spirituele leider')]),
 OrderedDict([('naam', 'mirte'),
              ('zie', ''),
              ('betekenis', 'liefde, huwelijk, vruchtbaarheid')]),
 OrderedDict([('naam', 'monnik'),
              ('zie', ''),
              ('betekenis', 'aanbidding, onderwerping')]),
 OrderedDict([('naam', 'muur'),
              ('zie', ''),
              ('betekenis',
               'veiligheid, bescherming, het sensitieve leven is afgescheiden '
               'van het goddelijke leven')]),
 OrderedDict([('naam', 'naaktheid'),
              ('zie', ''),
              ('betekenis', 'goddelijkheid')]),
 OrderedDict([('naam', 'natuur'),
              ('zie', ''),
              ('betekenis', 'werken met en in de natuur')]),
 OrderedDict([('naam', 'olijfblad'), ('zie', ''), ('betekenis', 'vrede')]),
 OrderedDict([('naam', 'ondersteboven'),
              ('zie', ''),
              ('betekenis', 'omgekeerde zienswijze')]),
 OrderedDict([('naam', 'oosten'), ('zie', ''), ('betekenis', 'zegebrengend')]),
 OrderedDict([('naam', 'oranje'),
              ('zie', 'geel, rood'),
              ('betekenis',
               'passie, hartstocht, optimisme, overdaad, losbandig')]),
 OrderedDict([('naam', 'oude man'),
              ('zie', ''),
              ('betekenis', 'ervaren, bewust van zijn pad')]),
 OrderedDict([('naam', 'oude man'), ('zie', ''), ('betekenis', 'wijsheid')]),
 OrderedDict([('naam', 'ourobouros'), ('zie', 'kringloop'), ('betekenis', '')]),
 OrderedDict([('naam', 'paard'),
              ('zie', ''),
              ('betekenis',
               'kracht en vitaliteit, edel en intelligent, fierheid, '
               'werklust')]),
 OrderedDict([('naam', 'paars'),
              ('zie', ''),
              ('betekenis',
               'inventiviteit, inspiratie, originaliteit, spiritualiteit, '
               'boete doen')]),
 OrderedDict([('naam', 'paars kleed'), ('zie', 'paars'), ('betekenis', '')]),
 OrderedDict([('naam', 'pad'),
              ('zie', ''),
              ('betekenis', 'reis, bestemming, herkomst')]),
 OrderedDict([('naam', 'palmhart'),
              ('zie', ''),
              ('betekenis', 'stijgen naar hoger niveau')]),
 OrderedDict([('naam', 'palmtak'), ('zie', ''), ('betekenis', 'overwinning')]),
 OrderedDict([('naam', 'parels'),
              ('zie', ''),
              ('betekenis', 'vrouw, verleiding')]),
 OrderedDict([('naam', 'pentagram'),
              ('zie', 'pentakel, zintuigen'),
              ('betekenis',
               'de nieuwe mens, het universum, elementen + ether (geest)')]),
 OrderedDict([('naam', 'pilaren'),
              ('zie', ''),
              ('betekenis', 'wijsheid, evenwicht in de wereld')]),
 OrderedDict([('naam', 'poort'),
              ('zie', ''),
              ('betekenis', 'doorgang, toegang, naar hemel/hel')]),
 OrderedDict([('naam', 'pyramide'),
              ('zie', ''),
              ('betekenis', 'energie, occulte wijsheid, universele wetten')]),
 OrderedDict([('naam', 'rad'), ('zie', ''), ('betekenis', 'cyclus')]),
 OrderedDict([('naam', 'ram'),
              ('zie', ''),
              ('betekenis',
               'daadkracht, onvoorzichtig, onvoorspelbaar, autoriteit, '
               'leiderschap, aggressiviteit')]),
 OrderedDict([('naam', 'rechtsonder'),
              ('zie', ''),
              ('betekenis', 'fysieke wereld')]),
 OrderedDict([('naam', 'rechts'),
              ('zie', 'oosten'),
              ('betekenis', 'mannelijke kant, verstand, buiten, toekomst')]),
 OrderedDict([('naam', 'regenboog'),
              ('zie', ''),
              ('betekenis',
               'zegen van boven, goddelijke bescherming, (geestelijke) '
               'rijkdom')]),
 OrderedDict([('naam', 'rijksappel'),
              ('zie', ''),
              ('betekenis', 'macht over aarde')]),
 OrderedDict([('naam', 'rivier'), ('zie', ''), ('betekenis', 'waterbron')]),
 OrderedDict([('naam', 'robijn'),
              ('zie', ''),
              ('betekenis',
               'koninklijke waardigheid, hartstochtelijke liefde, '
               'levenskracht')]),
 OrderedDict([('naam', 'rood'),
              ('zie', ''),
              ('betekenis',
               'fysieke manifestatie, lichamelijkheid, macht, levenskracht')]),
 OrderedDict([('naam', 'rood kleed'), ('zie', 'rood'), ('betekenis', '')]),
 OrderedDict([('naam', 'roos'), ('zie', ''), ('betekenis', 'hartverlangens')]),
 OrderedDict([('naam', 'saffier'),
              ('zie', ''),
              ('betekenis',
               'geeft gemoedsrust,  fysieke/geestelijke/spirituele harmonie, '
               'helpt te concentreren, verlicht stress, verbondenheid met de '
               'Goddelijke wereld')]),
 OrderedDict([('naam', 'salamander'),
              ('zie', 'vuur'),
              ('betekenis', 'geestelijk inzicht, ziel')]),
 OrderedDict([('naam', 'scepter'),
              ('zie', ''),
              ('betekenis', 'wereldse macht')]),
 OrderedDict([('naam', 'schip'), ('zie', 'boot'), ('betekenis', '')]),
 OrderedDict([('naam', 'schriftrol'), ('zie', 'tora'), ('betekenis', '')]),
 OrderedDict([('naam', 'sfinx'),
              ('zie', ''),
              ('betekenis',
               'wijsheid, levensvragen, macht, middelpunt, balans')]),
 OrderedDict([('naam', 'slang'),
              ('zie', 'kringloop'),
              ('betekenis', 'verleiding, onderwereld, dodenrijk')]),
 OrderedDict([('naam', 'sleutel'),
              ('zie', ''),
              ('betekenis',
               'meesterschap, toegang (tot de hemel), open en sluiten')]),
 OrderedDict([('naam', 'sluier'),
              ('zie', ''),
              ('betekenis', 'mysterie, ontdekken')]),
 OrderedDict([('naam', 'stadsmuur'), ('zie', ''), ('betekenis', 'herkomst')]),
 OrderedDict([('naam', 'ster (achtpuntig)'),
              ('zie', ''),
              ('betekenis',
               'verdrijft als ochtendster de duisternis,  vruchtbaarheid')]),
 OrderedDict([('naam', 'sterren'), ('zie', ''), ('betekenis', 'hemel')]),
 OrderedDict([('naam', 'stier'),
              ('zie', 'aarde'),
              ('betekenis',
               'offeren, mannelijke vruchtbaarheid, agressie, vechtlust')]),
 OrderedDict([('naam', 'stroom'),
              ('zie', 'water'),
              ('betekenis', 'zichtbare mysterie')]),
 OrderedDict([('naam', 'toorts'),
              ('zie', ''),
              ('betekenis', 'goddelijke energie, verschroeïng')]),
 OrderedDict([('naam', 'tora'),
              ('zie', ''),
              ('betekenis', 'goddelijke wet of leer')]),
 OrderedDict([('naam', 'toren'),
              ('zie', ''),
              ('betekenis',
               'menselijke hoogmoed, huis van God, toren van Babel, de hel')]),
 OrderedDict([('naam', 'trompet'),
              ('zie', ''),
              ('betekenis', 'oproep van de Hogere Natuur ')]),
 OrderedDict([('naam', 'troon'), ('zie', ''), ('betekenis', 'macht')]),
 OrderedDict([('naam', 'troonhemel'), ('zie', 'troon'), ('betekenis', '')]),
 OrderedDict([('naam', 'tweesprong'), ('zie', ''), ('betekenis', 'keuze')]),
 OrderedDict([('naam', 'vaandel'),
              ('zie', ''),
              ('betekenis', 'zijn wapen is het leven zelf')]),
 OrderedDict([('naam', 'valk'),
              ('zie', ''),
              ('betekenis', 'adel, koninklijk, alziend oog, onkwetsbaar')]),
 OrderedDict([('naam', 'venussymbool'),
              ('zie', ''),
              ('betekenis', 'godin van liefde en vruchtbaarheid')]),
 OrderedDict([('naam', 'vierkant'), ('zie', 'aarde'), ('betekenis', '')]),
 OrderedDict([('naam', 'vijgenblad'),
              ('zie', ''),
              ('betekenis', 'verschuilen')]),
 OrderedDict([('naam', 'vis'),
              ('zie', ''),
              ('betekenis', 'diepgaande transformatie, inwijding')]),
 OrderedDict([('naam', 'vleermuisvleugels'),
              ('zie', ''),
              ('betekenis',
               'onze tijd van leven vervliegt bij dag en nacht, bij goed en '
               'kwaad')]),
 OrderedDict([('naam', 'vogel'),
              ('zie', ''),
              ('betekenis', 'vrijheid, van ver halen')]),
 OrderedDict([('naam', 'vogelpoten'), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'volwassen man'),
              ('zie', 'man'),
              ('betekenis', 'viriele, beschermende kracht')]),
 OrderedDict([('naam', 'Volwassen vrouw'),
              ('zie', 'vrouw'),
              ('betekenis', 'actieve, vruchtbare kracht, moeder')]),
 OrderedDict([('naam', 'voorhang (bij pilaren)'),
              ('zie', ''),
              ('betekenis',
               'verborgen, innerlijk (tegenovergesteld bij ontbreken)')]),
 OrderedDict([('naam', 'vrouw'), ('zie', ''), ('betekenis', 'intuïtie')]),
 OrderedDict([('naam', 'vuur'),
              ('zie', ''),
              ('betekenis', 'kracht, zowel verterend als reinigend')]),
 OrderedDict([('naam', 'water'),
              ('zie', ''),
              ('betekenis',
               'Emoties, gevoelens, oerzee, universele energie, spiegel, de '
               'diepte van de ziel, het nog niet gemanifesteerde')]),
 OrderedDict([('naam', 'weegschaal'),
              ('zie', ''),
              ('betekenis',
               'evenwicht, rechtvaardigheid, juiste verhoudingen, voortdurende '
               'aanpassing om gerechtigheid te garanderen')]),
 OrderedDict([('naam', 'wereldbol'), ('zie', 'globe'), ('betekenis', '')]),
 OrderedDict([('naam', 'wijnhuisslak'),
              ('zie', ''),
              ('betekenis', 'wedergeboorte, opstanding')]),
 OrderedDict([('naam', 'wit'),
              ('zie', ''),
              ('betekenis',
               "onschuld, open, zuiver, ‘ware' spiritualiteit, naïviteit, "
               'leegte, perfectionisme')]),
 OrderedDict([('naam', 'wit kleed'), ('zie', 'wit'), ('betekenis', '')]),
 OrderedDict([('naam', 'wolken'),
              ('zie', ''),
              ('betekenis',
               'scheiding tussen zichtbare en onzichtbare wereld')]),
 OrderedDict([('naam', 'Y-vorm'),
              ('zie', ''),
              ('betekenis', 'zie tweesprong')]),
 OrderedDict([('naam', 'yod'),
              ('zie', ''),
              ('betekenis',
               'het kleinste teken van het Hebreeuwse alfabet '
               '(druppel/blad-vorm) en de eerste letter van de naam van God: '
               'JHWH')]),
 OrderedDict([('naam', 'yoni'),
              ('zie', ''),
              ('betekenis', 'vrouwelijke geslachtsorganen (zie lingam)')]),
 OrderedDict([('naam', 'zegening'),
              ('zie', ''),
              ('betekenis', 'creeëren van evenwicht')]),
 OrderedDict([('naam', 'zintuigen'),
              ('zie', ''),
              ('betekenis', 'horen, zien, ruiken, proeven, voelen')]),
 OrderedDict([('naam', 'zon'),
              ('zie', ''),
              ('betekenis',
               'het licht dat de mensheid leidt, schepper, God, '
               'levenskracht')]),
 OrderedDict([('naam', 'zonnebloem'),
              ('zie', 'zo'),
              ('betekenis',
               'waarheidslievend, wilskracht en vitaliteit, roem en '
               'overwinning')]),
 OrderedDict([('naam', 'zout'), ('zie', ''), ('betekenis', 'fysiek lichaam')]),
 OrderedDict([('naam', 'zwaard (verticaal)'),
              ('zie', ''),
              ('betekenis', 'scherpzinnigheid, gerechtigheid')]),
 OrderedDict([('naam', 'zwart'),
              ('zie', ''),
              ('betekenis', 'nacht, duisternis, rebellie')]),
 OrderedDict([('naam', 'zwart kleed'),
              ('zie', 'zwart'),
              ('betekenis', 'rouw, verdriet')]),
 OrderedDict([('naam', 'zwarte kat'),
              ('zie', 'zwart'),
              ('betekenis',
               'Vrijheidsdrang, intuïtieve gaven, magie, ongeluk, '
               'waarschuwer')]),
 OrderedDict([('naam', 'zwavel'), ('zie', ''), ('betekenis', 'ziel')])]
