from collections import OrderedDict

cards = [OrderedDict([('kleur', 'groot'),
              ('getal', 'O'),
              ('naam', 'De Dwaas'),
              ('opmerking', 'De Zot'),
              ('kernwoord', 'ONSCHULD'),
              ('steekwoorden',
               'Onschuld, ongevormd, lichtzinnig, afgrond, nieuw begin, naïef, '
               'kinderlijk, ongericht'),
              ('uitnodiging', 'Je spontaniteit is een pré.'),
              ('waarschuwing',
               'Gedachteloosheid, je overziet de consequenties niet.'),
              ('symbolen',
               'jonge man, roos, staf, zon, berg, hond, bloemenkrans, geel')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'I'),
              ('naam', 'De Magier'),
              ('opmerking', ''),
              ('kernwoord', 'MEESTERSCHAP'),
              ('steekwoorden',
               'Bewust van kracht en mogelijkheden, je (leer)proces aangaan, '
               'diplomatie, zo boven zo beneden'),
              ('uitnodiging', 'Richt je op wat je wél kunt.'),
              ('waarschuwing', 'Je neemt teveel hooi op je vork.'),
              ('symbolen',
               'natuur, roos, lelie,baldakijn, altaar, zwaard, staf, kelk, '
               'pentakel, jonge man, ourobouros, lemniscaat, bloemen, geel')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'II'),
              ('naam', 'De Hogepriesteres'),
              ('opmerking', 'De Pausin'),
              ('kernwoord', 'INTUÏTIE'),
              ('steekwoorden',
               'Beschermkaart, verborgen wijsheid, esoterische kennis, '
               'innerlijk conflict'),
              ('uitnodiging',
               'Gebruik je verbeelding om het mysterie te ontsluieren.'),
              ('waarschuwing', 'Betovering, hou je bij de feiten.'),
              ('symbolen',
               'maagd, sluier, kroon, troon, palmhart, granaatappel, maan, '
               'kruis, schriftrol, pilaren, boaz, jachin, blauw, waterbron, '
               'zwart')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'III'),
              ('naam', 'De Keizerin'),
              ('opmerking', ''),
              ('kernwoord', 'VRUCHTBAARHEID'),
              ('steekwoorden',
               'Ontspanning, de overvloed van het leven en de kracht van de '
               'bloeiende aarde, moeder, liefde geven en ontvangen'),
              ('uitnodiging', 'Geniet van wat je hebt.'),
              ('waarschuwing', 'Luiheid, hebzucht.'),
              ('symbolen',
               'volwassen vrouw, troon, kroon, parels, scepter, venussymbool, '
               'stroom, boom, koren')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'IV'),
              ('naam', 'De Keizer'),
              ('opmerking', ''),
              ('kernwoord', 'GEZAG'),
              ('steekwoorden',
               'Verwezenlijking, verantwoordelijkheid, zelfhandhaving, '
               'bescherming, vader'),
              ('uitnodiging', 'Neem zelf het heft in handen.'),
              ('waarschuwing', 'On- of over-verantwoordelijkheid.'),
              ('symbolen',
               'volwassen man, stroom, berg, troon, kroon, rijksappel, rood '
               'kleed,harnas')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'V'),
              ('naam', 'De Hogepriester'),
              ('opmerking', 'De Hiërofant, De Paus'),
              ('kernwoord', 'GEESTELIJKHEID'),
              ('steekwoorden',
               'Beschermkaart, religie, staan voor je mening, verkondigen, '
               'expertise, inspiratie, gewoontegetrouw'),
              ('uitnodiging', 'Kom naar buiten met wat jij vindt.'),
              ('waarschuwing', 'Je luistert slecht naar anderen.'),
              ('symbolen',
               'zegening, pilaren, kruis, kroon, adept, rood kleed, sleutel')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'VI'),
              ('naam', 'De Geliefden'),
              ('opmerking', ''),
              ('kernwoord', 'KEUZE'),
              ('steekwoorden',
               'Dualiteit mannelijk - vrouwelijk; (sexuele) '
               'aantrekkingskracht, bewust van tegenstellingen, samenwerking, '
               'onvoorwaardelijk ja, zich losmaken'),
              ('uitnodiging', 'Probeer dit met liefde te overwinnen.'),
              ('waarschuwing', 'Je houdt teveel rekening met anderen.'),
              ('symbolen',
               'naaktheid, engel, zegening, appelboom, slang, wolken, bergtop, '
               'zon, jonge man, jonge vrouw, paars kleed')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'VII'),
              ('naam', 'De Zegewagen'),
              ('opmerking', ''),
              ('kernwoord', 'VEROVERING'),
              ('steekwoorden',
               'Wilskracht, zelfdiscipline, controle, tot stand brengen, '
               'sprong voorwaarts'),
              ('uitnodiging', 'Bepaal je koers en hou die vast.'),
              ('waarschuwing', 'Teugels te strak of zwalkend.'),
              ('symbolen',
               'jonge man, kroon, lauwerkrans, ster (achtpuntig), vierkant, '
               'yoni, lingam, sfinx, stadsmuur, hermesvleugels')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'VIII'),
              ('naam', 'Gerechtigheid'),
              ('opmerking', 'Waite XI'),
              ('kernwoord', 'OPRECHTHEID'),
              ('steekwoorden',
               'Oorzaak en gevolg, schuld en boete, rechtvaardig'),
              ('uitnodiging', 'Erken je eigen aandeel maar niet meer dan dat.'),
              ('waarschuwing',
               'Schuldgevoelens, onrechtvaardigheid, strengheid'),
              ('symbolen',
               'man, zwaard geheven, weegschaal, vierkant, troon, pilaren, '
               'paars kleed, rood kleed, groen kleed, kubus')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'IX'),
              ('naam', 'De Kluizenaar'),
              ('opmerking', 'De Heremiet'),
              ('kernwoord', 'BEZINNING'),
              ('steekwoorden',
               'Je eigen weg gaan, op zoek zijn, dwalen, inkeer, '
               'teruggetrokken, voorzichtig, geduldig, zorgvuldig'),
              ('uitnodiging', 'Volg je eigen licht.'),
              ('waarschuwing', 'verdwaald, te eigengereid, eenzaam'),
              ('symbolen',
               'oude man, blauw, lantaarn, staf, ster (achtpuntig), afgewend, '
               'links, rechts')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'X'),
              ('naam', 'Het Rad van Fortuin'),
              ('opmerking', 'Wiel van Fortuin'),
              ('kernwoord', 'LOT'),
              ('steekwoorden', 'Aanvaarding, succes of falen.'),
              ('uitnodiging', 'Wie niet waagt die niet wint.'),
              ('waarschuwing', 'Je laat teveel aan het toeval over.'),
              ('symbolen',
               'engel, stier, leeuw, sfinx, slang, hermanubis, tora, feniks')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XI'),
              ('naam', 'Kracht'),
              ('opmerking', 'Waite VIII'),
              ('kernwoord', 'BEHEERSING'),
              ('steekwoorden',
               'Met respekt omgaan met kracht en emoties, temmen'),
              ('uitnodiging', 'Een besliste maar zachte hand is nodig.'),
              ('waarschuwing', 'Die Leeuw mag best af en toe eens brullen.'),
              ('symbolen',
               'jonge vrouw, leeuw, bloemenkrans, lemniscaat, bergtop, '
               'oranje')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XII'),
              ('naam', 'De Gehangene'),
              ('opmerking', ''),
              ('kernwoord', 'PERSPECTIEF'),
              ('steekwoorden',
               'Ergens aan vast zitten, consequenties aanvaarden, beproeving, '
               'ommekeer, herprioriteren'),
              ('uitnodiging', 'Vrije wil is blijmoedig doen wat je moet doen.'),
              ('waarschuwing', 'Je zit vast.'),
              ('symbolen',
               'volwassen man, ondersteboven, aureool, kruis, blauw, staf')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XIII'),
              ('naam', 'De Dood'),
              ('opmerking', 'De Kaart zonder Naam'),
              ('kernwoord', 'AFSLUITING'),
              ('steekwoorden',
               'vernietiging van het oude, doorbraak, het onvermijdelijke, '
               'afscheid, vergankelijkheid'),
              ('uitnodiging', 'Wat moet dood zodat je verder kunt?'),
              ('waarschuwing', 'Angst is een slechte raadgever.'),
              ('symbolen',
               'wit, vaandel, wolken, toren, zon, koning, bisschop, jonge '
               'vrouw, kind, boot, man, stroom, paard, afgewend, zwart')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XIV'),
              ('naam', 'Matigheid'),
              ('opmerking', ''),
              ('kernwoord', 'HARMONIE'),
              ('steekwoorden',
               'Afwegen, evenwicht verstand en gevoel, integratie, zuinigheid, '
               'tact'),
              ('uitnodiging', 'In harmonie komen met jezelf.'),
              ('waarschuwing', 'Overmaat schaadt,  ondermaat ook.'),
              ('symbolen',
               'engel, natuur, iris, kelken, pad, driehoek, stroom, berg, '
               'vierkant')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XV'),
              ('naam', 'De Duivel'),
              ('opmerking', ''),
              ('kernwoord', 'VERLEIDING'),
              ('steekwoorden',
               'Obsessie, de Schaduw, sexualiteit, zwart-wit denken, '
               'fanatisme, materialisme'),
              ('uitnodiging', 'Doorzie de verleiding / angst.'),
              ('waarschuwing', 'Slaaf zijn van je verlangens.'),
              ('symbolen',
               'geit, vleermuisvleugels, vogelpoten, borsten, troon, zegening, '
               'vierkant, toorts, naaktheid, ketens, pentagram, zwart')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XVI'),
              ('naam', 'De Toren'),
              ('opmerking', 'Het Huis Gods'),
              ('kernwoord', 'RAMPSPOED'),
              ('steekwoorden',
               'Onvoorziene verandering, crisis, vertwijfeling, loslaten van '
               'zekerheid, noodlot, toren van Babel'),
              ('uitnodiging', 'Hou het geloof in jezelf vast.'),
              ('waarschuwing', 'Wachten tot de bom barst.'),
              ('symbolen',
               'toren, vuur, bergtop, wolken, bliksem, kroon, yod, zwart')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XVII'),
              ('naam', 'De Ster'),
              ('opmerking', ''),
              ('kernwoord', 'HOOP'),
              ('steekwoorden',
               'bezieling, wees de ster in je eigen leven, de sterren '
               'bereiken'),
              ('uitnodiging', 'Vertrouw op het bestaan.'),
              ('waarschuwing', 'Valse hoop, misplaatst vertrouwen.'),
              ('symbolen',
               'ster (achtpuntig), naaktheid, jonge vrouw, kelken, heuvels, '
               'feniks, water')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XVIII'),
              ('naam', 'De Maan'),
              ('opmerking', ''),
              ('kernwoord', 'SCHEMER'),
              ('steekwoorden',
               'verlangens, droom en daad, behoefte aan bescherming,uit je '
               'schulp kruipen, dwaling, stemmingswisselingen'),
              ('uitnodiging', 'Bevrijding van beperkende conditioneringen.'),
              ('waarschuwing',
               'Kwetsbaarheid, gebondenheid. Angst voor verraad.'),
              ('symbolen',
               'maan, pad, hond + wolf, hond, water, kreeft, yod, toren, '
               'pilaren')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XIX'),
              ('naam', 'De Zon'),
              ('opmerking', ''),
              ('kernwoord', 'OPTIMISME'),
              ('steekwoorden',
               'creativiteit, speelsheid, levenslust, zelfvertrouwen, je hart, '
               'je kern'),
              ('uitnodiging', 'Plezier en ongedwongen jezelf zijn.'),
              ('waarschuwing', 'Het speelkwartier is allang voorbij.'),
              ('symbolen',
               'kind, bloemenkrans, wit, rood kleed, zon, zonnebloem, '
               'golven')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XX'),
              ('naam', 'Het Oordeel'),
              ('opmerking', ''),
              ('kernwoord', 'VERLOSSING'),
              ('steekwoorden',
               'Transformatie, het laatste oordeel, verrijzenis'),
              ('uitnodiging', 'Laat het verleden los.'),
              ('waarschuwing', 'Schuldgevoelens en zelfkritiek.'),
              ('symbolen',
               'engel, wolken, bazuin, volwassen man, volwassen vrouw, kind, '
               'grijs, naaktheid, berg')]),
 OrderedDict([('kleur', 'groot'),
              ('getal', 'XXI'),
              ('naam', 'De Wereld'),
              ('opmerking', ''),
              ('kernwoord', 'LEVEN'),
              ('steekwoorden',
               'Het leven aangaan zonder jezelf er in te verliezen, hervonden '
               'paradijs'),
              ('uitnodiging', 'Ga voluit voor wat je wilt bereiken.'),
              ('waarschuwing', 'Het is tijd voor bezinning.'),
              ('symbolen',
               'jonge vrouw, staven, lauwerkrans, leeuw, stier, arend, '
               'engel')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', ''),
              ('naam', 'Aas'),
              ('opmerking', ''),
              ('kernwoord', 'DROOM'),
              ('steekwoorden', 'visie, enthousiasme, vitaliteit.'),
              ('uitnodiging', 'Bezieling.'),
              ('waarschuwing', 'Overmoed.'),
              ('symbolen',
               'wolken, stroom, heuvels, burcht, hand, rechts, grijs')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', '2'),
              ('naam', 'II'),
              ('opmerking', ''),
              ('kernwoord', 'PLANNEN'),
              ('steekwoorden', 'pionieren, opties afwegen'),
              ('uitnodiging', 'Alle begin is moeilijk.'),
              ('waarschuwing', 'Vernieuwing is nog geen verbetering.'),
              ('symbolen',
               'links, water, muur, globe, roos, lelie, berg, rood kleed, '
               'grijs')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', '3'),
              ('naam', 'III'),
              ('opmerking', ''),
              ('kernwoord', 'AFWACHTEN'),
              ('steekwoorden', 'vooruitzien, handel, ontdekkingsreizen'),
              ('uitnodiging', 'Formuleer een helder doel.'),
              ('waarschuwing', 'Je kunt nu niet meer terug.'),
              ('symbolen',
               'rechts, rood kleed, groen kleed, boot, water, heuvels, geel')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', '4'),
              ('naam', 'IV'),
              ('opmerking', ''),
              ('kernwoord', 'OOGSTEN'),
              ('steekwoorden',
               'resultaten vieren, harmonieuze samenwerking, terugkerende '
               'feesten'),
              ('uitnodiging', 'Je initiatief is vruchtbaar.'),
              ('waarschuwing', 'Op je lauweren rusten.'),
              ('symbolen',
               'kasteel, wit kleed, rood kleed, blauw kleed, bloemen, '
               'oranje')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', '5'),
              ('naam', 'V'),
              ('opmerking', ''),
              ('kernwoord', 'WEDIJVEREN'),
              ('steekwoorden', 'schijngevecht, rellen'),
              ('uitnodiging', 'Strijd haalt het beste in je naar voren.'),
              ('waarschuwing', 'Blijven hangen in gekissebis.'),
              ('symbolen', '')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', '6'),
              ('naam', 'VI'),
              ('opmerking', ''),
              ('kernwoord', 'TRIOMFEREN'),
              ('steekwoorden',
               'zegevieren, mijlpaal, beginnend succes, waardering, groot '
               'nieuws'),
              ('uitnodiging', 'Je verwachtingen komen uit.'),
              ('waarschuwing', 'Te resultaatgericht.'),
              ('symbolen', 'groen kleed, lauwerkrans, paard')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', '7'),
              ('naam', 'VII'),
              ('opmerking', ''),
              ('kernwoord', 'HANDHAVEN'),
              ('steekwoorden',
               'staande houden, vaak alleen, overmacht, gunstige positie'),
              ('uitnodiging', 'Neem het voor jezelf op.'),
              ('waarschuwing',
               'Vraag niet voortdurend goedkeuring. Doe het gewoon!'),
              ('symbolen', 'stroom, heuvels')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', '8'),
              ('naam', 'VIII'),
              ('opmerking', ''),
              ('kernwoord', 'OPLIJNEN'),
              ('steekwoorden',
               'veel energie, alles op één lijn, van een lijen dakje, haast, '
               'liefdespijlen'),
              ('uitnodiging', 'Energie kanaliseren'),
              ('waarschuwing', 'Teveel tegelijk.'),
              ('symbolen', 'stroom, heuvels, linksboven, rechtsonder')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', '9'),
              ('naam', 'IX'),
              ('opmerking', ''),
              ('kernwoord', 'WAKEN'),
              ('steekwoorden',
               'op krachten komen, verzet, achterdocht, oponthoud, uitstel'),
              ('uitnodiging', 'De laatste loodjes: zet door'),
              ('waarschuwing', 'opgebrand: laat los'),
              ('symbolen', 'muur')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', '10'),
              ('naam', 'X'),
              ('opmerking', ''),
              ('kernwoord', 'VOLHOUDEN'),
              ('steekwoorden',
               'afmaken, heroverwegen, opstand tegen onderdrukking'),
              ('uitnodiging', 'Consolideer'),
              ('waarschuwing', 'Je verdeelt je krachten verkeerd'),
              ('symbolen', 'stadsmuur')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', ''),
              ('naam', 'Page'),
              ('opmerking', ''),
              ('kernwoord', 'BOODSCHAPPER'),
              ('steekwoorden', 'op ideeën komen.'),
              ('uitnodiging', 'Oriënteer je op mogelijkheden.'),
              ('waarschuwing', 'Tunnelvisie.'),
              ('symbolen', 'heuvels, pyramide, rood kleed, blauw')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', ''),
              ('naam', 'Ridder'),
              ('opmerking', ''),
              ('kernwoord', 'VURIG'),
              ('steekwoorden', 'idealen koesteren, overtuigingskracht.'),
              ('uitnodiging', 'Verruim je horizon.'),
              ('waarschuwing', 'Te idealistisch.'),
              ('symbolen',
               'salamander, geel, oranje, paard, harnas, vuur, pyramide')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', ''),
              ('naam', 'Koningin'),
              ('opmerking', ''),
              ('kernwoord', 'KUNDIG'),
              ('steekwoorden',
               'je eigen belevings- en verbeeldingswereld, onafhankelijk, '
               'identiteit, zelfvertrouwen'),
              ('uitnodiging', 'Geloof in jezelf.'),
              ('waarschuwing', 'Te eigengereid.'),
              ('symbolen',
               'geel kleed, grijs kleed, troon, leeuw, zonnebloem, kroon, '
               'bloemenkrans, zwarte kat')]),
 OrderedDict([('kleur', 'Staven'),
              ('getal', ''),
              ('naam', 'Koning'),
              ('opmerking', ''),
              ('kernwoord', 'RECHTVAARDIG'),
              ('steekwoorden',
               'creatief, inspirerend, charmant, geestig, rechtvaardig, '
               'gedreven'),
              ('uitnodiging', 'Hoe zou jij het aanpakken?'),
              ('waarschuwing', 'ongeduld.'),
              ('symbolen',
               'salamander, geel, rood kleed, groen kleed, troon, kroon, '
               'ourobouros, afgewend, leeuw, oranje')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', ''),
              ('naam', 'Aas'),
              ('opmerking', ''),
              ('kernwoord', 'POTENTIE'),
              ('steekwoorden',
               'kunde, tot stand brengen, realisme, waarde, potentie'),
              ('uitnodiging', 'Lever een constructieve bijdrage.'),
              ('waarschuwing', 'Perfectionisme.'),
              ('symbolen',
               'hand, wolken, boog, bloemen, links, roos, lelie, pad, bergtop, '
               'blauw')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', '2'),
              ('naam', 'II'),
              ('opmerking', ''),
              ('kernwoord', 'JONGLEREN'),
              ('steekwoorden',
               'evenwicht zoeken/houden, uitgekiende inzet van middelen, '
               'oefenen, schijnplezier'),
              ('uitnodiging', 'Trek de zaak weer vlot.'),
              ('waarschuwing', 'Het ene gat met het andere stoppen.'),
              ('symbolen', 'lemniscaat, golven, boot, jonge man, blauw')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', '3'),
              ('naam', 'III'),
              ('opmerking', ''),
              ('kernwoord', 'PRESENTEREN'),
              ('steekwoorden',
               'waardering, vakmanschap, uitvoering, inzet, proef'),
              ('uitnodiging', 'Voer je plan uit.'),
              ('waarschuwing', 'Gevoelig voor kritiek.'),
              ('symbolen', 'monnik, hamer, grijs, zwart')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', '4'),
              ('naam', 'IV'),
              ('opmerking', ''),
              ('kernwoord', 'VASTHOUDEN'),
              ('steekwoorden',
               'houden wat je hebt, energiestroom blokkeren, hebzucht'),
              ('uitnodiging', 'Wees zuinig op je mogelijkheden.'),
              ('waarschuwing', 'Materialisme.'),
              ('symbolen', 'toren, paars')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', '5'),
              ('naam', 'V'),
              ('opmerking', ''),
              ('kernwoord', 'VREZEN'),
              ('steekwoorden',
               '(angst voor) ontbering, gebrek, kou, angst voor de toekoms'),
              ('uitnodiging', 'Wat heb je echt nodig?'),
              ('waarschuwing', 'Jezelf onderwaarderen.'),
              ('symbolen', 'bel')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', '6'),
              ('naam', 'VI'),
              ('opmerking', ''),
              ('kernwoord', 'BEDELEN'),
              ('steekwoorden',
               'Delen = vermenigvuldigen, arm vs rijk, zaaien, Bedelen vs '
               'beDElen'),
              ('uitnodiging', 'Geven en nemen.'),
              ('waarschuwing', 'Wrok over onrecht / te kort komen.'),
              ('symbolen',
               'rood kleed, zegening, boom, burcht, weegschaal, geel kleed, '
               'blauw kleed')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', '7'),
              ('naam', 'VII'),
              ('opmerking', ''),
              ('kernwoord', 'PIEKEREN'),
              ('steekwoorden', 'ongeduld, onvrede, beheren'),
              ('uitnodiging', 'Kijk het nog even aan. Zie je voortgang.'),
              ('waarschuwing', 'Toekijken, er buiten staan.'),
              ('symbolen', 'staf, paars')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', '8'),
              ('naam', 'VIII'),
              ('opmerking', ''),
              ('kernwoord', 'OEFENEN'),
              ('steekwoorden', 'oefenen, nederig werk, ambachten, kundigheid'),
              ('uitnodiging', 'Verbeter je effectiviteit.'),
              ('waarschuwing', 'Sleur, geen plezier in je werk.'),
              ('symbolen', 'hamer, geel')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', '9'),
              ('naam', 'IX'),
              ('opmerking', ''),
              ('kernwoord', 'GENIETEN'),
              ('steekwoorden', 'vervulling, verfraaien, zekerheid, meevaller'),
              ('uitnodiging', 'Geniet van wat je doet.'),
              ('waarschuwing', 'Gericht op uiterlijkheden.'),
              ('symbolen', 'druiven, kasteel, geel, valk, wijnhuisslak')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', '10'),
              ('naam', 'X'),
              ('opmerking', ''),
              ('kernwoord', 'DOORGEVEN'),
              ('steekwoorden',
               'traditie, iets opbouwen, zekerheid, welvaart, familiezaken'),
              ('uitnodiging', 'Draag bij aan het grotere geheel.'),
              ('waarschuwing', 'Gefixeerd op zekerheid.'),
              ('symbolen',
               'druiven, hond, burcht, toren, poort, weegschaal, oude man')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', ''),
              ('naam', 'Page'),
              ('opmerking', ''),
              ('kernwoord', 'LEERGIERIG'),
              ('steekwoorden',
               'behulpzaam, precies, kritisch, student, ijverig'),
              ('uitnodiging', 'Hoe kun je jezelf nuttig maken?'),
              ('waarschuwing', 'detaillistisch, vluchtige belangstelling'),
              ('symbolen',
               'natuur, heuvels, bloemen, groen kleed, stroom, geel')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', ''),
              ('naam', 'Ridder'),
              ('opmerking', ''),
              ('kernwoord', 'STANDVASTIG'),
              ('steekwoorden',
               'organisatievermogen, degelijk, plichtgetrouw, praktisch'),
              ('uitnodiging', 'Richt je op het haalbare.'),
              ('waarschuwing', 'Veeleisend.'),
              ('symbolen', 'paard, harnas, rood kleed, afgewend, geel')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', ''),
              ('naam', 'Koningin'),
              ('opmerking', ''),
              ('kernwoord', 'ZORGZAAM'),
              ('steekwoorden', 'innerlijke zekerheid, zelfwaardering, royaal'),
              ('uitnodiging', 'Rust en geleidelijkheid.'),
              ('waarschuwing', 'Behoudzucht.'),
              ('symbolen',
               'natuur, troon, kroon, bloemen, berg, cupido, geit, haas, '
               'afgewend, geel')]),
 OrderedDict([('kleur', 'Pentakels'),
              ('getal', ''),
              ('naam', 'Koning'),
              ('opmerking', ''),
              ('kernwoord', 'LEIDER'),
              ('steekwoorden',
               'standvastigheid, autoriteit, realiserende intelligentie, '
               'zakelijk, besluitvaardig'),
              ('uitnodiging', 'Realisme.'),
              ('waarschuwing', 'Rechtlijnig, onbuigzaam.'),
              ('symbolen', 'stier, druiven, troon, kroon, harnas, geel')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', ''),
              ('naam', 'Aas'),
              ('opmerking', ''),
              ('kernwoord', 'VISIE'),
              ('steekwoorden', 'helderheid van geest, objectiviteit'),
              ('uitnodiging', 'Een verstandelijke benadering.'),
              ('waarschuwing', 'In je hoofd zitten.'),
              ('symbolen',
               'wolken, hand, kroon, robijn, olijfblad, palmtak, zwaard '
               'geheven, blauw')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', '2'),
              ('naam', 'II'),
              ('opmerking', ''),
              ('kernwoord', 'TWIJFELEN'),
              ('steekwoorden',
               'relativeren, twee kanten van de medaille zien, dilemma'),
              ('uitnodiging', 'Analyseer voor en tegen.'),
              ('waarschuwing', 'Twijfelen.'),
              ('symbolen',
               'wit kleed, water, heuvels, kubus, blinddoek, maan, blauw')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', '3'),
              ('naam', 'III'),
              ('opmerking', ''),
              ('kernwoord', 'DOORBOREN'),
              ('steekwoorden', 'pijn, verdriet'),
              ('uitnodiging', 'Wind er geen doekjes om.'),
              ('waarschuwing', 'Onredelijkheid.'),
              ('symbolen', 'hartvorm, wolken, grijs')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', '4'),
              ('naam', 'IV'),
              ('opmerking', ''),
              ('kernwoord', 'BEZINNEN'),
              ('steekwoorden',
               'overwegen, rusten, herstellen, retraite, testament'),
              ('uitnodiging', 'Slaap er een nachtje over.'),
              ('waarschuwing', 'Besluiteloosheid.'),
              ('symbolen', 'grijs, ridder')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', '5'),
              ('naam', 'V'),
              ('opmerking', ''),
              ('kernwoord', 'MISGUNNEN'),
              ('steekwoorden',
               'debatteren, negatieve gedachtepatronen, verraad, degradatie, '
               'oneer'),
              ('uitnodiging', 'Wapen je met argumenten.'),
              ('waarschuwing', 'Altijd gelijk willen hebben.'),
              ('symbolen', 'afgewend, oranje, blauw')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', '6'),
              ('naam', 'VI'),
              ('opmerking', ''),
              ('kernwoord', 'OVERSTEKEN'),
              ('steekwoorden', 'je terug trekken, vlucht'),
              ('uitnodiging', 'Deze zaak is niet met argumenten te winnen.'),
              ('waarschuwing', 'Is het gras echt groener?'),
              ('symbolen', 'water, golven')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', '7'),
              ('naam', 'VII'),
              ('opmerking', ''),
              ('kernwoord', 'INTRIGEREN'),
              ('steekwoorden', 'slimheid, spitsvondigheid, oneerlijkheid'),
              ('uitnodiging', 'Verzin een list.'),
              ('waarschuwing', 'Je wordt in de maling genomen.'),
              ('symbolen', 'oranje')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', '8'),
              ('naam', 'VIII'),
              ('opmerking', ''),
              ('kernwoord', 'VASTLOPEN'),
              ('steekwoorden',
               'negatieve gedachtenpatronen, censuur, ziekte, schaamte, '
               'verdenking'),
              ('uitnodiging', 'Je redenering klopt niet.'),
              ('waarschuwing', 'Cirkelredeneringen.'),
              ('symbolen', 'blinddoek, burcht, stroom, berg, grijs')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', '9'),
              ('naam', 'IX'),
              ('opmerking', ''),
              ('kernwoord', 'ONTWAKEN'),
              ('steekwoorden', 'dagend inzicht, zelfverwijt, vertwijfeling'),
              ('uitnodiging', 'Laat dit eerst bezinken.'),
              ('waarschuwing', 'Verwarring.'),
              ('symbolen', 'afgewend, roos, wit kleed, oosten, vrouw, zwart')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', '10'),
              ('naam', 'X'),
              ('opmerking', ''),
              ('kernwoord', 'BEEINDIGEN'),
              ('steekwoorden', 'destructieve gedachten, voortijdig einde'),
              ('uitnodiging', 'Een overtuiging volkomen loslaten.'),
              ('waarschuwing', 'Faalangst.'),
              ('symbolen',
               'water, zon, heuvels, rood kleed, zegening, zwart')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', ''),
              ('naam', 'Page'),
              ('opmerking', ''),
              ('kernwoord', 'WAAKZAAM'),
              ('steekwoorden', 'verstand van zaken, opmerkzaam, escalatie'),
              ('uitnodiging', 'Stel jezelf op de hoogte.'),
              ('waarschuwing', 'Betweterigheid.'),
              ('symbolen', 'wolken, heuvels, vogel, stroom, grijs')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', ''),
              ('naam', 'Ridder'),
              ('opmerking', ''),
              ('kernwoord', 'ONSTUIMIG'),
              ('steekwoorden',
               'onverwachte doorbraak, confrontatie, bekwaamheid, dapperheid'),
              ('uitnodiging', 'Staan voor je overtuiging.'),
              ('waarschuwing', 'Te theoretisch.'),
              ('symbolen', 'oranje, rood kleed, paard, harnas, vogel')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', ''),
              ('naam', 'Koningin'),
              ('opmerking', ''),
              ('kernwoord', 'WIJS'),
              ('steekwoorden',
               'innerlijke overtuiging, eerlijkheid, levenswijsheid, '
               'heldere/rustige geest, deugdzaam, streng'),
              ('uitnodiging', 'Rechtvaardigheid.'),
              ('waarschuwing', 'Rechtlijnigheid.'),
              ('symbolen',
               'afgewend, wolken, troon, kroon, wit kleed, volwassen vrouw, '
               'zwaard geheven, cupido, vogel, grijs')]),
 OrderedDict([('kleur', 'Zwaarden'),
              ('getal', ''),
              ('naam', 'Koning'),
              ('opmerking', ''),
              ('kernwoord', 'DENKER'),
              ('steekwoorden',
               'De gedachte gaat aan de manifestatie vooraf, handhaver, '
               'rationeel, skeptisch, hard, dominant'),
              ('uitnodiging', 'Vel een oordeel.'),
              ('waarschuwing', 'Te rationeel. Wreed'),
              ('symbolen',
               'troon, kroon, blauw, paars kleed, wolken, heuvels, boom, '
               'zwaard geheven, vogel')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', ''),
              ('naam', 'Aas'),
              ('opmerking', ''),
              ('kernwoord', 'OVERVLOED'),
              ('steekwoorden',
               'verlangen naar eenheid en verbondenheid, overgave, '
               'bewustwording, de bron, de Graal.'),
              ('uitnodiging', 'Laat je gevoel stromen.'),
              ('waarschuwing', 'Over-emotioneel.'),
              ('symbolen',
               'rechts, hand, wolken, waterbron, duif, yod, lelie, hostie, '
               'blauw')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', '2'),
              ('naam', 'II'),
              ('opmerking', ''),
              ('kernwoord', 'VERBINDEN'),
              ('steekwoorden',
               'verlangen naar een partner (eventueel platonisch), gevoel vs '
               'verstand, valse liefde'),
              ('uitnodiging', 'Samenwerking, verbondenheid.'),
              ('waarschuwing', 'Gefixeerd op relatie.'),
              ('symbolen',
               'lauwerkrans, roos, slang, leeuw, heuvels, hermesvleugels')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', '3'),
              ('naam', 'III'),
              ('opmerking', ''),
              ('kernwoord', 'FEESTEN'),
              ('steekwoorden', 'plezier hebben, blijheid, genezing, troost'),
              ('uitnodiging', 'Laat jezelf eens gaan.'),
              ('waarschuwing', 'Losbandigheid.'),
              ('symbolen',
               'druiven, bloemen, rood kleed, geel kleed, wit kleed, blauw')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', '4'),
              ('naam', 'IV'),
              ('opmerking', ''),
              ('kernwoord', 'MEDITEREN'),
              ('steekwoorden', 'verlangen naar meer, lusteloosheid'),
              ('uitnodiging', 'Het is tijd voor verandering.'),
              ('waarschuwing', 'Onvervuld.'),
              ('symbolen', 'hand, wolken, boom, links')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', '5'),
              ('naam', 'V'),
              ('opmerking', ''),
              ('kernwoord', 'BETREUREN'),
              ('steekwoorden', 'teleurstelling, verlies, desillusie'),
              ('uitnodiging', 'Wat blijft er over?'),
              ('waarschuwing', 'Blijven hangen in verdriet.'),
              ('symbolen',
               'grijs, stroom, brug, burcht, afgewend, zwart kleed, bloed, '
               'groen')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', '6'),
              ('naam', 'VI'),
              ('opmerking', ''),
              ('kernwoord', 'HERINNEREN'),
              ('steekwoorden',
               'verbinden, delen vanuit overvloed, vreugde schenken, '
               'nostalgie'),
              ('uitnodiging', 'Verheug je in kleine dingen.'),
              ('waarschuwing', 'verloren onschuld, zinloze nostalgie'),
              ('symbolen', 'dwaas, vrouw, lelie, burcht')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', '7'),
              ('naam', 'VII'),
              ('opmerking', ''),
              ('kernwoord', 'MISLEIDEN'),
              ('steekwoorden',
               'visioenen, illusie, mystery guest, verbeelding, vergankelijke '
               'weelde'),
              ('uitnodiging', 'Wat heb je werkelijk nodig?'),
              ('waarschuwing', 'Klatergoud.'),
              ('symbolen',
               'slang, lauwerkrans, draak, edelstenen, burcht, engel, wolken, '
               'afgewend, doodshoofd, zwart')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', '8'),
              ('naam', 'VIII'),
              ('opmerking', ''),
              ('kernwoord', 'WEGLOPEN'),
              ('steekwoorden',
               'illusies achter je laten, het roer om, een nieuw pad kiezen'),
              ('uitnodiging', 'Laat het verleden los.'),
              ('waarschuwing', 'Een nieuwe illusie najagen.'),
              ('symbolen', 'maan, water, berg, rood kleed, blauw')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', '9'),
              ('naam', 'IX'),
              ('opmerking', ''),
              ('kernwoord', 'WAARDEREN'),
              ('steekwoorden',
               'evenwichtigheid, dromen zijn werkelijkheid geworden, innerlijk '
               'geluk'),
              ('uitnodiging', 'Bewaar je gemoedsrust.'),
              ('waarschuwing', 'Luiheid en arrogantie'),
              ('symbolen', 'blauw kleed')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', '10'),
              ('naam', 'X'),
              ('opmerking', ''),
              ('kernwoord', 'THUISKOMEN'),
              ('steekwoorden',
               'welzijn, voltooiing, samen (gezin/dorp/gemeente)'),
              ('uitnodiging', 'Definieer wat je gelukkig zou maken.'),
              ('waarschuwing', 'Ophemelen.'),
              ('symbolen', 'regenboog, stroom, gezin, huis, afgewend')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', ''),
              ('naam', 'Page'),
              ('opmerking', ''),
              ('kernwoord', 'VERWONDERD'),
              ('steekwoorden',
               'fantasie, verbeelding, puberteit, vlijtige jeugd'),
              ('uitnodiging', 'Ontwikkel je creativiteit.'),
              ('waarschuwing', 'Goedgelovigheid.'),
              ('symbolen', 'lotus, vis, golven, blauw')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', ''),
              ('naam', 'Ridder'),
              ('opmerking', ''),
              ('kernwoord', 'ONDERZOEKER'),
              ('steekwoorden',
               'aanvoelen, betrokkenheid, waarheidsvinding, voorstel'),
              ('uitnodiging', 'Zorg voor een goede verstandhouding.'),
              ('waarschuwing', 'Overbezorgheid.'),
              ('symbolen',
               'hermesvleugels, harnas, paard, stroom, heuvels, vis, afgewend, '
               'blauw')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', ''),
              ('naam', 'Koningin'),
              ('opmerking', ''),
              ('kernwoord', 'WAARNEMER'),
              ('steekwoorden',
               'inlevingsvermogen, innerlijk weten, visioenen/dromerig, '
               'gedistingeerd'),
              ('uitnodiging', 'Erover praten kan je beeld verhelderen.'),
              ('waarschuwing', 'Navelstaarderij.'),
              ('symbolen',
               'golven, troon, kroon, wit kleed, afgewend, blauw')]),
 OrderedDict([('kleur', 'Kelken'),
              ('getal', ''),
              ('naam', 'Koning'),
              ('opmerking', ''),
              ('kernwoord', 'INTEGER'),
              ('steekwoorden',
               'bewustwording, verdraagzaamheid, gevoelig man, onderhandelaar, '
               'brede belangstelling, wetsman, wetenschapper'),
              ('uitnodiging', 'Een rots in de branding.'),
              ('waarschuwing', 'Onderdrukte gevoelens'),
              ('symbolen',
               'golven, vis, boot, kroon, troon, scepter, geel kleed, blauw')])]

symbols = [OrderedDict([('naam', 'Grote Arcana'),
              ('zie', ''),
              ('betekenis', 'de grote geheimen van het leven, archetypes')]),
 OrderedDict([('naam', 'Grote Arcana 1-10'),
              ('zie', ''),
              ('betekenis',
               'verwerven van eigenschappen en innerlijke kwaliteiten')]),
 OrderedDict([('naam', 'Grote Arcana 11-20'),
              ('zie', ''),
              ('betekenis',
               'leren omgaan met de ervaringen die het leven brengt')]),
 OrderedDict([('naam', 'Kleine Arcana'),
              ('zie', ''),
              ('betekenis', 'geheimen van het alledaagse leven')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'getallen'),
              ('zie', ''),
              ('betekenis', 'Doen (dingen die je zelf in de hand hebt)')]),
 OrderedDict([('naam', 'hofkaart'),
              ('zie', ''),
              ('betekenis', 'Zijn (invloeden van/naar je omgeving)')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'Staven'),
              ('zie', 'vuur'),
              ('betekenis',
               'willen/initiatief, intuïtie/ideeën, uitvoerend, '
               'boeren/arbeiders')]),
 OrderedDict([('naam', 'Pentakels'),
              ('zie', 'Aarde, V'),
              ('betekenis',
               'doen, zintuigen/praktisch, operationeel, '
               'ambachtslieden/handelaars')]),
 OrderedDict([('naam', 'Zwaarden'),
              ('zie', 'lucht'),
              ('betekenis', 'denken, verstand, tactisch, adel')]),
 OrderedDict([('naam', 'Kelken'),
              ('zie', 'water'),
              ('betekenis',
               'voelen, emotie, strategisch, geestelijkheid/staatslieden')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'staf'), ('zie', 'staven'), ('betekenis', '')]),
 OrderedDict([('naam', 'Pentakel'), ('zie', 'pentakels'), ('betekenis', '')]),
 OrderedDict([('naam', 'zwaard'), ('zie', 'zwaarden'), ('betekenis', '')]),
 OrderedDict([('naam', 'Kelk'), ('zie', 'kelken'), ('betekenis', '')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'klavers'), ('zie', 'staven'), ('betekenis', '')]),
 OrderedDict([('naam', 'ruiten'), ('zie', 'pentakels'), ('betekenis', '')]),
 OrderedDict([('naam', 'schoppen'), ('zie', 'zwaarden'), ('betekenis', '')]),
 OrderedDict([('naam', 'harten'), ('zie', 'kelken'), ('betekenis', '')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'O'),
              ('zie', ''),
              ('betekenis', 'leegte, alomvattendheid, kosmische invloed')]),
 OrderedDict([('naam', 'I'),
              ('zie', ''),
              ('betekenis', 'Potentie, eenheid, oorsprong')]),
 OrderedDict([('naam', 'II'),
              ('zie', ''),
              ('betekenis', 'Dualiteit, spiegelbeeld')]),
 OrderedDict([('naam', 'III'),
              ('zie', 'Drie-eenheid'),
              ('betekenis', 'groei, vruchtbaarheid, gilden: leerling')]),
 OrderedDict([('naam', 'IV'),
              ('zie', 'elementen'),
              ('betekenis', 'stabiliteit, vorming, rechtvaardig, materie')]),
 OrderedDict([('naam', 'V'),
              ('zie', 'zintuigen'),
              ('betekenis', 'doorzetten, zoeken, zingeving, gilden: gezel')]),
 OrderedDict([('naam', 'VI'),
              ('zie', ''),
              ('betekenis', 'kantelpunt, dienstvaardigheid')]),
 OrderedDict([('naam', 'VII'),
              ('zie', ''),
              ('betekenis', 'Zelfkennnis, paradox, toeval, gilden: meester')]),
 OrderedDict([('naam', 'VIII'),
              ('zie', ''),
              ('betekenis', 'kiezen, karma, promiscu')]),
 OrderedDict([('naam', 'IX'),
              ('zie', ''),
              ('betekenis', 'vervulling, horizon, gilden: bouwmeester')]),
 OrderedDict([('naam', 'X'),
              ('zie', ''),
              ('betekenis', 'Climax, overgang, einde=begin')]),
 OrderedDict([('naam', 'XI'),
              ('zie', ''),
              ('betekenis', 'openbaring, inspiratie')]),
 OrderedDict([('naam', 'XII'),
              ('zie', ''),
              ('betekenis', 'volledigheid, perfectie, deelbaarheid')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'aas'),
              ('zie', 'I'),
              ('betekenis', 'waar je mee begint')]),
 OrderedDict([('naam', 'page'),
              ('zie', 'jonge man'),
              ('betekenis', 'boodschapper, nieuwsgierig, kans')]),
 OrderedDict([('naam', 'ridder'),
              ('zie', ''),
              ('betekenis', 'strijder, werker, beschermen van zwakkeren ')]),
 OrderedDict([('naam', 'koningin'),
              ('zie', 'volwassen vrouw'),
              ('betekenis', 'wijsheid, volwassenheid')]),
 OrderedDict([('naam', 'koning'),
              ('zie', 'volwassen man'),
              ('betekenis', 'gezag, competentie')]),
 OrderedDict([('naam', ''), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'aarde'), ('zie', ''), ('betekenis', 'vruchtbaarheid')]),
 OrderedDict([('naam', 'adept'), ('zie', 'monnik'), ('betekenis', '')]),
 OrderedDict([('naam', 'afgewend'),
              ('zie', ''),
              ('betekenis', 'terugblikken')]),
 OrderedDict([('naam', 'altaar'), ('zie', ''), ('betekenis', 'religie')]),
 OrderedDict([('naam', 'ankh'),
              ('zie', 'scepter'),
              ('betekenis', 'eeuwig leven')]),
 OrderedDict([('naam', 'ankh'), ('zie', 'jakhalsgod'), ('betekenis', '')]),
 OrderedDict([('naam', 'appelboom'),
              ('zie', ''),
              ('betekenis',
               'boom van kennis (van goed en kwaad), bewustzijn')]),
 OrderedDict([('naam', 'arcana'), ('zie', ''), ('betekenis', 'geheimen')]),
 OrderedDict([('naam', 'arend'),
              ('zie', 'water, feniks'),
              ('betekenis', 'god ziet de mens')]),
 OrderedDict([('naam', 'aureool'),
              ('zie', ''),
              ('betekenis', 'diepe trance, verandering in bewustzijn')]),
 OrderedDict([('naam', 'baldakijn'), ('zie', 'troonhemel'), ('betekenis', '')]),
 OrderedDict([('naam', 'bel'),
              ('zie', ''),
              ('betekenis', 'melaatsheid, ziekte')]),
 OrderedDict([('naam', 'berg'),
              ('zie', ''),
              ('betekenis', 'standvastigheid, aarde, mystieke reis')]),
 OrderedDict([('naam', 'bergtop'),
              ('zie', 'berg'),
              ('betekenis', 'plaats dicht bij god')]),
 OrderedDict([('naam', 'bisschop'),
              ('zie', 'geestelijke'),
              ('betekenis', 'uiterlijke religie')]),
 OrderedDict([('naam', 'blauw'),
              ('zie', ''),
              ('betekenis',
               'rust, vrede, intelligentie, stabiliteit, loyaal, conservatief, '
               'koelheid')]),
 OrderedDict([('naam', 'blauw kleed'), ('zie', 'blauw'), ('betekenis', '')]),
 OrderedDict([('naam', 'bliksem'),
              ('zie', ''),
              ('betekenis', 'goddelijke communicatie, vernietiging')]),
 OrderedDict([('naam', 'blinddoek'),
              ('zie', ''),
              ('betekenis',
               'onwetendheid, verblinding, overgeleverd zijn aan het lot')]),
 OrderedDict([('naam', 'bloed'),
              ('zie', ''),
              ('betekenis', 'liefde, levenskracht')]),
 OrderedDict([('naam', 'bloemen'),
              ('zie', ''),
              ('betekenis',
               'natuurlijke levenskracht, levensvreugde, actief en viriel')]),
 OrderedDict([('naam', 'Bloemenkrans'), ('zie', 'bloemen'), ('betekenis', '')]),
 OrderedDict([('naam', 'Boaz'),
              ('zie', ''),
              ('betekenis', 'bevestigen, strengheid (intentie)')]),
 OrderedDict([('naam', 'boek'), ('zie', ''), ('betekenis', 'kennisbron')]),
 OrderedDict([('naam', 'boekrol'),
              ('zie', 'boek'),
              ('betekenis', 'intuïtieve bron')]),
 OrderedDict([('naam', 'boog'), ('zie', 'poort'), ('betekenis', '')]),
 OrderedDict([('naam', 'boom'), ('zie', ''), ('betekenis', 'levenskracht')]),
 OrderedDict([('naam', 'boot'),
              ('zie', ''),
              ('betekenis', 'Verre reis (door de onderwereld?)')]),
 OrderedDict([('naam', 'borsten'),
              ('zie', ''),
              ('betekenis',
               'verborgen vruchtbaarheid, de mogelijkheid te creeëren en te '
               'vermenigvuldigen zonder de ander/Ander, androgyne figuur')]),
 OrderedDict([('naam', 'brug'), ('zie', ''), ('betekenis', 'overgang')]),
 OrderedDict([('naam', 'burcht'),
              ('zie', ''),
              ('betekenis', 'bescherming, veilige thuishaven')]),
 OrderedDict([('naam', 'cupido'), ('zie', ''), ('betekenis', 'liefde')]),
 OrderedDict([('naam', 'davidsster'), ('zie', ''), ('betekenis', 'harmonie')]),
 OrderedDict([('naam', 'doodshoofd'),
              ('zie', ''),
              ('betekenis', 'de dood, sterfelijkheid')]),
 OrderedDict([('naam', 'draak'),
              ('zie', 'vuur, slang'),
              ('betekenis', 'tegenstander, schatbewaker, onsterfelijkheid')]),
 OrderedDict([('naam', 'drie-eenheid'),
              ('zie', ''),
              ('betekenis',
               'geest/ziel/lichaam, vader/zoon/heilige geest, '
               'hemel/aarde/hel')]),
 OrderedDict([('naam', 'driehoek'),
              ('zie', 'III, vuur'),
              ('betekenis', 'geest')]),
 OrderedDict([('naam', 'druiven'),
              ('zie', ''),
              ('betekenis', 'overvloed, rijke oogst')]),
 OrderedDict([('naam', 'druppel'),
              ('zie', ''),
              ('betekenis', 'genade, vrede, hoop')]),
 OrderedDict([('naam', 'duif'),
              ('zie', ''),
              ('betekenis', 'brenger van vrede, heilige geest')]),
 OrderedDict([('naam', 'dwaas'), ('zie', 'de dwaas'), ('betekenis', '')]),
 OrderedDict([('naam', 'edelstenen'),
              ('zie', ''),
              ('betekenis', 'hebzucht, materialisme')]),
 OrderedDict([('naam', 'elementen'),
              ('zie', 'water, vuur, lucht, aarde'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'engel'),
              ('zie', 'lucht'),
              ('betekenis', 'boodschapper van god, oorsprong van de mens')]),
 OrderedDict([('naam', 'feniks'),
              ('zie', ''),
              ('betekenis',
               'verjonging (door drievoudige onderdompeling in water), '
               'herboren ziel')]),
 OrderedDict([('naam', 'geel'),
              ('zie', ''),
              ('betekenis',
               '(zon) levenskracht en warmte, nadenken, vrolijkheid, '
               'creativiteit, afgunst, onrust')]),
 OrderedDict([('naam', 'geel kleed'), ('zie', 'geel'), ('betekenis', '')]),
 OrderedDict([('naam', 'geestelijke'),
              ('zie', 'hiërofant'),
              ('betekenis', 'toewijding, toetreding')]),
 OrderedDict([('naam', 'geit'),
              ('zie', ''),
              ('betekenis',
               'voedster, doorzettingsvermogen, seksueel plezier')]),
 OrderedDict([('naam', 'gezin'),
              ('zie', ''),
              ('betekenis', 'huiselijk geluk')]),
 OrderedDict([('naam', 'globe'),
              ('zie', ''),
              ('betekenis', 'de wereld ontdekken/veroveren')]),
 OrderedDict([('naam', 'golven'),
              ('zie', 'water'),
              ('betekenis', 'wisselende stemmingen, wisselend succes')]),
 OrderedDict([('naam', 'graan'), ('zie', 'koren'), ('betekenis', '')]),
 OrderedDict([('naam', 'granaatappel'),
              ('zie', ''),
              ('betekenis', 'mensen in groep')]),
 OrderedDict([('naam', 'grijs'),
              ('zie', 'zwart, wit'),
              ('betekenis',
               'harmonie (zwart en wit gemengd), rust en onopvallendheid, '
               'evenwicht, wijsheid')]),
 OrderedDict([('naam', 'grijs kleed'),
              ('zie', 'grijs'),
              ('betekenis', 'eenvoud, bewust leven')]),
 OrderedDict([('naam', 'groen'),
              ('zie', 'blauw, geel'),
              ('betekenis',
               'groei, ontwikkeling, harmonie, ontspanning, verveling, '
               'weerstand')]),
 OrderedDict([('naam', 'groen kleed'),
              ('zie', 'groen'),
              ('betekenis', 'afremmen, rusten, verlagen')]),
 OrderedDict([('naam', 'groene omgeving'),
              ('zie', 'natuur'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'haag'), ('zie', 'muur'), ('betekenis', '')]),
 OrderedDict([('naam', 'haas'),
              ('zie', ''),
              ('betekenis', 'vruchtbaarheid, opofferingsgezindheid, loyaal')]),
 OrderedDict([('naam', 'hamer'),
              ('zie', ''),
              ('betekenis', 'kracht, activiteit')]),
 OrderedDict([('naam', 'hand'), ('zie', ''), ('betekenis', 'hand van god')]),
 OrderedDict([('naam', 'harnas'),
              ('zie', ''),
              ('betekenis', 'mannelijkheid, beschermer, streng, onbuigzaam')]),
 OrderedDict([('naam', 'hartvorm'),
              ('zie', ''),
              ('betekenis',
               'vrouw, aantrekkingskracht, emoties, het onbewuste')]),
 OrderedDict([('naam', 'hermanubis'),
              ('zie', 'jakhalsgod'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'hermes'),
              ('zie', ''),
              ('betekenis', 'boodschapper van de goden')]),
 OrderedDict([('naam', 'hermesvleugels'),
              ('zie', 'hermes'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'heuvels'),
              ('zie', ''),
              ('betekenis', 'initiatie, vruchtbaarheid')]),
 OrderedDict([('naam', 'hiërofant'),
              ('zie', 'hogepriester'),
              ('betekenis', '')]),
 OrderedDict([('naam', 'hond'),
              ('zie', ''),
              ('betekenis',
               'trouw, waakzaam, getemd, kent de weg, ongebreidelde lust, '
               'instinct')]),
 OrderedDict([('naam', 'hond + wolf'),
              ('zie', ''),
              ('betekenis', 'getemde en ongetemde energiën (in de mens)')]),
 OrderedDict([('naam', 'hostie'), ('zie', ''), ('betekenis', 'offer')]),
 OrderedDict([('naam', 'huis'),
              ('zie', 'gezin'),
              ('betekenis', 'geborgenheid, thuis')]),
 OrderedDict([('naam', 'iris'), ('zie', ''), ('betekenis', 'boodschappers')]),
 OrderedDict([('naam', 'Jachin'),
              ('zie', ''),
              ('betekenis', 'kracht, mededogen (vorm)')]),
 OrderedDict([('naam', 'jakhalsgod'),
              ('zie', ''),
              ('betekenis',
               'voorbode van de dood, begeleider van zielen naar '
               'onderwereld')]),
 OrderedDict([('naam', 'Jahwe'),
              ('zie', ''),
              ('betekenis', 'de geheime, onuitspreekbare naam van God')]),
 OrderedDict([('naam', 'jod'), ('zie', 'yod'), ('betekenis', '')]),
 OrderedDict([('naam', 'jonge man'),
              ('zie', 'man'),
              ('betekenis', 'energie, initiatief')]),
 OrderedDict([('naam', 'jonge vrouw'),
              ('zie', 'vrouw'),
              ('betekenis', 'vruchtbaar, zuiver')]),
 OrderedDict([('naam', 'kasteel'), ('zie', 'burcht'), ('betekenis', '')]),
 OrderedDict([('naam', 'ketens'),
              ('zie', ''),
              ('betekenis', 'gebondenheid, verbondenheid')]),
 OrderedDict([('naam', 'kind'),
              ('zie', ''),
              ('betekenis',
               'goddelijke onschuld, het resultaat van de samensmelting tussen '
               'de mannelijke en vrouwelijke energie, einde van de dualiteit, '
               'vernieuwde eenheid')]),
 OrderedDict([('naam', 'knapzak'),
              ('zie', ''),
              ('betekenis', 'wereldse bezittingen')]),
 OrderedDict([('naam', 'koren'),
              ('zie', ''),
              ('betekenis',
               'rijke oogst, toegeweid moederschap, scheppende kracht')]),
 OrderedDict([('naam', 'kreeft'),
              ('zie', ''),
              ('betekenis',
               'primitief dier, de angsten en illusies willen zich '
               'manifesteren, rusteloosheid')]),
 OrderedDict([('naam', 'kringloop'),
              ('zie', ''),
              ('betekenis', 'circulair proces, eenheid van alles')]),
 OrderedDict([('naam', 'kroon'),
              ('zie', ''),
              ('betekenis', 'wereldse macht, talent, meesterschap')]),
 OrderedDict([('naam', 'kruis'), ('zie', ''), ('betekenis', 'religie')]),
 OrderedDict([('naam', 'kubus'), ('zie', ''), ('betekenis', 'het aardse')]),
 OrderedDict([('naam', 'kwik'), ('zie', ''), ('betekenis', 'geest')]),
 OrderedDict([('naam', 'lantaarn'), ('zie', ''), ('betekenis', 'wegwijzen')]),
 OrderedDict([('naam', 'lauwerkrans '),
              ('zie', ''),
              ('betekenis',
               'vergankelijke macht, zegeviering na (innerlijke) strijd')]),
 OrderedDict([('naam', 'leeuw'),
              ('zie', 'vuur'),
              ('betekenis',
               'moedige bewaker van grenzen, gevestigde macht, eenling, koning '
               'der dieren')]),
 OrderedDict([('naam', 'lelie'),
              ('zie', ''),
              ('betekenis',
               'hartverlangens, maagdelijkheid, reinheid, onschuld, goddelijke '
               'genade/gaven')]),
 OrderedDict([('naam', 'lemniscaat'),
              ('zie', ''),
              ('betekenis', 'oneindige verbondenheid, heilige geest')]),
 OrderedDict([('naam', 'lingam'),
              ('zie', ''),
              ('betekenis', 'fallussymbool (zie ook yoni)')]),
 OrderedDict([('naam', 'links'),
              ('zie', ''),
              ('betekenis', 'vrouwelijke kant, intuïtie, binnen, verleden')]),
 OrderedDict([('naam', 'linksboven'),
              ('zie', ''),
              ('betekenis', 'gedachtenwereld')]),
 OrderedDict([('naam', 'lotus'),
              ('zie', ''),
              ('betekenis',
               'spiritualiteit, kunst, inzicht, zelfvernieuwing')]),
 OrderedDict([('naam', 'lucht'),
              ('zie', ''),
              ('betekenis', 'denken, liefhebben, van iedereen')]),
 OrderedDict([('naam', 'maagd'),
              ('zie', 'jonge vrouw'),
              ('betekenis', '(nog) niet seksueel actief')]),
 OrderedDict([('naam', 'maan'),
              ('zie', 'vrouw'),
              ('betekenis',
               'gids in donkere tijden (de maan reflecteert het licht van de '
               'zon), passiviteit')]),
 OrderedDict([('naam', 'man'),
              ('zie', ''),
              ('betekenis', 'zichtbare, spirituele leider')]),
 OrderedDict([('naam', 'mirte'),
              ('zie', ''),
              ('betekenis', 'liefde, huwelijk, vruchtbaarheid')]),
 OrderedDict([('naam', 'monnik'),
              ('zie', ''),
              ('betekenis', 'aanbidding, onderwerping')]),
 OrderedDict([('naam', 'muur'),
              ('zie', ''),
              ('betekenis',
               'veiligheid, bescherming, het sensitieve leven is afgescheiden '
               'van het goddelijke leven')]),
 OrderedDict([('naam', 'naaktheid'),
              ('zie', ''),
              ('betekenis', 'vrijheid, niets te verbergen, kwetsbaarheid')]),
 OrderedDict([('naam', 'natuur'),
              ('zie', ''),
              ('betekenis', 'werken met en in de natuur')]),
 OrderedDict([('naam', 'olijfblad'), ('zie', ''), ('betekenis', 'vrede')]),
 OrderedDict([('naam', 'ondersteboven'),
              ('zie', ''),
              ('betekenis', 'omgekeerde zienswijze')]),
 OrderedDict([('naam', 'oosten'), ('zie', ''), ('betekenis', 'zegebrengend')]),
 OrderedDict([('naam', 'oranje'),
              ('zie', 'geel, rood'),
              ('betekenis',
               'passie, hartstocht, optimisme, overdaad, losbandig')]),
 OrderedDict([('naam', 'oude man'),
              ('zie', ''),
              ('betekenis', 'ervaren, bewust van zijn pad')]),
 OrderedDict([('naam', 'oude man'), ('zie', ''), ('betekenis', 'wijsheid')]),
 OrderedDict([('naam', 'ourobouros'),
              ('zie', 'kringloop'),
              ('betekenis', 'slangengordel')]),
 OrderedDict([('naam', 'paard'),
              ('zie', ''),
              ('betekenis',
               'kracht en vitaliteit, edel en intelligent, fierheid, '
               'werklust')]),
 OrderedDict([('naam', 'paars'),
              ('zie', ''),
              ('betekenis',
               'inventiviteit, inspiratie, originaliteit, spiritualiteit, '
               'boete doen')]),
 OrderedDict([('naam', 'paars kleed'), ('zie', 'paars'), ('betekenis', '')]),
 OrderedDict([('naam', 'pad'),
              ('zie', ''),
              ('betekenis', 'reis, bestemming, herkomst')]),
 OrderedDict([('naam', 'palmhart'),
              ('zie', ''),
              ('betekenis', 'stijgen naar hoger niveau')]),
 OrderedDict([('naam', 'palmtak'), ('zie', ''), ('betekenis', 'overwinning')]),
 OrderedDict([('naam', 'parels'),
              ('zie', ''),
              ('betekenis', 'vrouw, verleiding')]),
 OrderedDict([('naam', 'pentagram'),
              ('zie', 'pentakel, zintuigen'),
              ('betekenis',
               'de nieuwe mens, het universum, elementen + ether (geest)')]),
 OrderedDict([('naam', 'pilaren'),
              ('zie', ''),
              ('betekenis', 'wijsheid, evenwicht in de wereld')]),
 OrderedDict([('naam', 'poort'),
              ('zie', ''),
              ('betekenis', 'doorgang, toegang, naar hemel/hel')]),
 OrderedDict([('naam', 'pyramide'),
              ('zie', ''),
              ('betekenis', 'energie, occulte wijsheid, universele wetten')]),
 OrderedDict([('naam', 'rad'), ('zie', ''), ('betekenis', 'cyclus')]),
 OrderedDict([('naam', 'ram'),
              ('zie', ''),
              ('betekenis',
               'daadkracht, onvoorzichtig, onvoorspelbaar, autoriteit, '
               'leiderschap, aggressiviteit')]),
 OrderedDict([('naam', 'rechtsonder'),
              ('zie', ''),
              ('betekenis', 'fysieke wereld')]),
 OrderedDict([('naam', 'rechts'),
              ('zie', 'oosten'),
              ('betekenis', 'mannelijke kant, verstand, buiten, toekomst')]),
 OrderedDict([('naam', 'regenboog'),
              ('zie', ''),
              ('betekenis',
               'zegen van boven, goddelijke bescherming, (geestelijke) '
               'rijkdom')]),
 OrderedDict([('naam', 'rijksappel'),
              ('zie', ''),
              ('betekenis', 'macht over aarde')]),
 OrderedDict([('naam', 'rivier'), ('zie', ''), ('betekenis', 'waterbron')]),
 OrderedDict([('naam', 'robijn'),
              ('zie', ''),
              ('betekenis',
               'koninklijke waardigheid, hartstochtelijke liefde, '
               'levenskracht')]),
 OrderedDict([('naam', 'rood'),
              ('zie', ''),
              ('betekenis',
               'Hartstocht, fysieke manifestatie, actie, macht, '
               'levenskracht')]),
 OrderedDict([('naam', 'rood kleed'), ('zie', 'rood'), ('betekenis', '')]),
 OrderedDict([('naam', 'roos'), ('zie', ''), ('betekenis', 'hartverlangens')]),
 OrderedDict([('naam', 'saffier'),
              ('zie', ''),
              ('betekenis',
               'geeft gemoedsrust,  fysieke/geestelijke/spirituele harmonie, '
               'helpt te concentreren, verlicht stress, verbondenheid met de '
               'Goddelijke wereld')]),
 OrderedDict([('naam', 'salamander'),
              ('zie', 'vuur'),
              ('betekenis', 'geestelijk inzicht, ziel')]),
 OrderedDict([('naam', 'scepter'),
              ('zie', ''),
              ('betekenis', 'wereldse macht')]),
 OrderedDict([('naam', 'schip'), ('zie', 'boot'), ('betekenis', '')]),
 OrderedDict([('naam', 'schriftrol'), ('zie', 'tora'), ('betekenis', '')]),
 OrderedDict([('naam', 'sfinx'),
              ('zie', ''),
              ('betekenis',
               'wijsheid, levensvragen, macht, middelpunt, balans')]),
 OrderedDict([('naam', 'slang'),
              ('zie', 'kringloop'),
              ('betekenis', 'verleiding, onderwereld, dodenrijk')]),
 OrderedDict([('naam', 'sleutel'),
              ('zie', ''),
              ('betekenis',
               'meesterschap, toegang (tot de hemel), open en sluiten')]),
 OrderedDict([('naam', 'sluier'),
              ('zie', ''),
              ('betekenis', 'mysterie, ontdekken')]),
 OrderedDict([('naam', 'stadsmuur'), ('zie', ''), ('betekenis', 'herkomst')]),
 OrderedDict([('naam', 'ster (achtpuntig)'),
              ('zie', ''),
              ('betekenis',
               'verdrijft als ochtendster de duisternis,  vruchtbaarheid')]),
 OrderedDict([('naam', 'sterren'), ('zie', ''), ('betekenis', 'hemel')]),
 OrderedDict([('naam', 'stier'),
              ('zie', 'aarde'),
              ('betekenis',
               'offeren, mannelijke vruchtbaarheid, agressie, vechtlust')]),
 OrderedDict([('naam', 'stroom'),
              ('zie', 'waterbron'),
              ('betekenis', 'zichtbare mysterie')]),
 OrderedDict([('naam', 'toorts'),
              ('zie', ''),
              ('betekenis', 'goddelijke energie, verschroeïng')]),
 OrderedDict([('naam', 'tora'),
              ('zie', ''),
              ('betekenis', 'goddelijke wet of leer')]),
 OrderedDict([('naam', 'toren'),
              ('zie', ''),
              ('betekenis',
               'menselijke hoogmoed, huis van God, toren van Babel, de hel')]),
 OrderedDict([('naam', 'bazuin'),
              ('zie', ''),
              ('betekenis', 'oproep van de Hogere Natuur ')]),
 OrderedDict([('naam', 'troon'), ('zie', ''), ('betekenis', 'macht')]),
 OrderedDict([('naam', 'troonhemel'), ('zie', 'troon'), ('betekenis', '')]),
 OrderedDict([('naam', 'tweesprong'), ('zie', ''), ('betekenis', 'keuze')]),
 OrderedDict([('naam', 'vaandel'),
              ('zie', ''),
              ('betekenis', 'zijn wapen is het leven zelf')]),
 OrderedDict([('naam', 'valk'),
              ('zie', ''),
              ('betekenis', 'adel, koninklijk, alziend oog, onkwetsbaar')]),
 OrderedDict([('naam', 'venussymbool'),
              ('zie', ''),
              ('betekenis', 'godin van liefde en vruchtbaarheid')]),
 OrderedDict([('naam', 'vierkant'),
              ('zie', 'IV, aarde'),
              ('betekenis', 'materie')]),
 OrderedDict([('naam', 'vijgenblad'),
              ('zie', ''),
              ('betekenis', 'verschuilen')]),
 OrderedDict([('naam', 'vis'),
              ('zie', ''),
              ('betekenis', 'diepgaande transformatie, inwijding')]),
 OrderedDict([('naam', 'vleermuisvleugels'),
              ('zie', ''),
              ('betekenis',
               'onze tijd van leven vervliegt bij dag en nacht, bij goed en '
               'kwaad')]),
 OrderedDict([('naam', 'vogel'),
              ('zie', ''),
              ('betekenis', 'vrijheid, van ver halen')]),
 OrderedDict([('naam', 'vogelpoten'), ('zie', ''), ('betekenis', '')]),
 OrderedDict([('naam', 'volwassen man'),
              ('zie', 'man'),
              ('betekenis', 'viriele, beschermende kracht')]),
 OrderedDict([('naam', 'Volwassen vrouw'),
              ('zie', 'vrouw'),
              ('betekenis', 'actieve, vruchtbare kracht, moeder')]),
 OrderedDict([('naam', 'voorhang (bij pilaren)'),
              ('zie', ''),
              ('betekenis',
               'verborgen, innerlijk (tegenovergesteld bij ontbreken)')]),
 OrderedDict([('naam', 'vrouw'), ('zie', ''), ('betekenis', 'intuïtie')]),
 OrderedDict([('naam', 'vuur'),
              ('zie', ''),
              ('betekenis', 'kracht, zowel verterend als reinigend')]),
 OrderedDict([('naam', 'water'),
              ('zie', ''),
              ('betekenis',
               'Emoties, gevoelens, oerzee, spiegel, de diepte van de ziel, '
               'het nog niet gemanifesteerde')]),
 OrderedDict([('naam', 'waterbron'),
              ('zie', 'water'),
              ('betekenis', 'geneeskrachtig')]),
 OrderedDict([('naam', 'weegschaal'),
              ('zie', ''),
              ('betekenis',
               'evenwicht, rechtvaardigheid, juiste verhoudingen, voortdurende '
               'aanpassing om gerechtigheid te garanderen')]),
 OrderedDict([('naam', 'wereldbol'), ('zie', 'globe'), ('betekenis', '')]),
 OrderedDict([('naam', 'wijnhuisslak'),
              ('zie', ''),
              ('betekenis', 'wedergeboorte, opstanding')]),
 OrderedDict([('naam', 'wit'),
              ('zie', ''),
              ('betekenis',
               "onschuld, open, zuiver, ‘ware' spiritualiteit, naïviteit, "
               'leegte, perfectionisme')]),
 OrderedDict([('naam', 'wit kleed'), ('zie', 'wit'), ('betekenis', '')]),
 OrderedDict([('naam', 'wolken'),
              ('zie', ''),
              ('betekenis',
               'scheiding tussen zichtbare en onzichtbare wereld')]),
 OrderedDict([('naam', 'Y-vorm'),
              ('zie', ''),
              ('betekenis', 'zie tweesprong')]),
 OrderedDict([('naam', 'yod'),
              ('zie', 'druppel'),
              ('betekenis',
               'het kleinste teken van het Hebreeuwse alfabet '
               '(druppel/blad-vorm) en de eerste letter van de naam van God: '
               'JHWH')]),
 OrderedDict([('naam', 'yoni'),
              ('zie', ''),
              ('betekenis', 'vrouwelijke geslachtsorganen (zie lingam)')]),
 OrderedDict([('naam', 'zegening'),
              ('zie', ''),
              ('betekenis', 'creeëren van evenwicht')]),
 OrderedDict([('naam', 'zintuigen'),
              ('zie', ''),
              ('betekenis', 'horen, zien, ruiken, proeven, voelen')]),
 OrderedDict([('naam', 'zon'),
              ('zie', ''),
              ('betekenis',
               'het licht dat de mensheid leidt, schepper, God, '
               'levenskracht')]),
 OrderedDict([('naam', 'zonnebloem'),
              ('zie', 'zon'),
              ('betekenis',
               'waarheidslievend, wilskracht en vitaliteit, roem en '
               'overwinning')]),
 OrderedDict([('naam', 'zout'), ('zie', ''), ('betekenis', 'fysiek lichaam')]),
 OrderedDict([('naam', 'zwaard geheven'),
              ('zie', ''),
              ('betekenis', 'scherpzinnigheid, gerechtigheid')]),
 OrderedDict([('naam', 'zwart'),
              ('zie', ''),
              ('betekenis', 'nacht, duisternis, rebellie, mysterie')]),
 OrderedDict([('naam', 'zwart kleed'),
              ('zie', 'zwart'),
              ('betekenis', 'rouw, verdriet')]),
 OrderedDict([('naam', 'zwarte kat'),
              ('zie', 'zwart'),
              ('betekenis',
               'Vrijheidsdrang, intuïtieve gaven, magie, ongeluk, '
               'waarschuwer')]),
 OrderedDict([('naam', 'zwavel'), ('zie', ''), ('betekenis', 'ziel')])]
